// GENERATED FILE - do not edit by hand.
// Regenerated by scratchpad/make_report_cards.py from pbcc/ui.js + pbcc/index.html.
// Report-card module for the pbcc tool: renders every chart from the tool's
// zones report modal into the pbcc-card.html fragment on a report page.
// Data endpoints can be redirected (e.g. to area-level aggregates) by setting
// window.REPORT_CARD_ENDPOINTS = { '<default path>': <override> } where the
// override is either '<replacement path>' (another pbcc-data folder) or
// { bin: '<dataset>' } (a capBin single-binary dataset, which the page must
// have capBin.register()ed - see reports/la-report.js).

function pbccCard_fetchJSON(url) {
  // 'bin:<dataset>/<id>.json' pseudo-URLs come from the { bin: ... } override
  // form of REPORT_CARD_ENDPOINTS and are served by capBin range requests.
  if (url.lastIndexOf('bin:', 0) === 0) {
    var rest = url.slice(4);
    var slash = rest.indexOf('/');
    return capBin.fetchRecord(rest.slice(0, slash), rest.slice(slash + 1).replace(/\.json$/, ''));
  }
  return fetch(url).then(function (r) {
    if (!r.ok) { throw new Error('HTTP ' + r.status); }
    return r.json();
  });
}

function pbccCard_endpoint(path) {
  var override = (window.REPORT_CARD_ENDPOINTS || {})[path];
  if (override && typeof override === 'object' && override.bin) { return 'bin:' + override.bin + '/'; }
  return 'https://pbcc.blob.core.windows.net/pbcc-data/' + (override || path);
}

// Tab switcher scoped to this card's own fragment, so multiple tool cards can
// coexist on one report page without cross-talk.
function pbccCard_modalTab(evt, tabName) {
  var root = evt.currentTarget.closest('.report-fullcard');
  if (!root) { return; }
  root.querySelectorAll('.tabcontent').forEach(function (el) { el.style.display = 'none'; });
  root.querySelectorAll('.tablinks').forEach(function (el) { el.className = el.className.replace(' active', ''); });
  var target = root.querySelector('#' + tabName);
  if (target) { target.style.display = 'block'; }
  evt.currentTarget.className += ' active';
}

// Local Chart Mangement
var pbccCard_overviewChart;
var pbccCard_historicalChart;

var pbccCard_consumptionFoodChart;
var pbccCard_consumptionAlcoholChart;
var pbccCard_consumptionFurnishingsChart;
var pbccCard_consumptionOtherHousingChart;
var pbccCard_consumptionClothingChart;
var pbccCard_consumptionCommunicationChart;
var pbccCard_consumptionRecreationChart;
var pbccCard_consumptionRestaurantsChart;
var pbccCard_consumptionHealthChart;
var pbccCard_consumptionEducationChart;
var pbccCard_consumptionMiscellaneousChart;
var pbccCard_consumptionFlightsChart;
var pbccCard_consumptionVehiclePurchaseChart;
var pbccCard_consumptionVehicleOtherChart;
var pbccCard_consumptionTotalChart;

var pbccCard_gasChart;
var pbccCard_electricChart;
var pbccCard_carEmissionsChart;
var pbccCard_vanEmissionsChart;
var pbccCard_bikeCompanyChart;
var pbccCard_publicTransportChart;

var pbccCard_otherHeatingChart;
var pbccCard_otherHousingChart;

var pbccCard_plefIgnoreChart;
var pbccCard_plefSteerChart;
var pbccCard_plefShiftChart;
var pbccCard_plefTransformChart;

var pbccCard_populationChart;

var pbccCard_locationData = {};
var pbccCard_voa2020LocationData = {};
var pbccCard_voa2010LocationData = {};
var pbccCard_communityPicLocationData = {};
var pbccCard_populationLocationData = {};
var pbccCard_lsoaOverviewData = {};
var pbccCard_laHistoricalData = {};
var pbccCard_oacHistoricalData = {};
// Legend label for the local authority comparison. Set to the authority's own
// name where we know it, so a reader can see which one is being compared -
// this matters most on constituency reports, where a constituency can straddle
// several authorities and only the largest is shown.
var pbccCard_laLabel = 'Local Authority';
var pbccCard_gbHistoricalData = {};

var pbccCard_dwellingsctChart;
var pbccCard_dwellingstypeChart;
var pbccCard_dwellingsbedroomsChart;
var pbccCard_dwellingsageChart;

pbccCard_manageCharts = function (locationId) {
	console.log('Managing Charts');

	// Primary chained requests that feed multiple charts
	const urlsPrimary = [
		pbccCard_endpoint('historical_emissions/v2/') + locationId + '.json',
		pbccCard_endpoint('population/') + locationId + '.json',
		pbccCard_endpoint('lsoa_overview/v1/') + locationId + '.json',
		// The GB comparison row lives in the la_emissions dataset under the ID
		// 'GB' (see make_la_summary() in build/R/la_summaries.R), so it follows
		// whatever the host page maps 'la_emissions/v2/' to rather than being
		// pinned to the old JSON folder.
		pbccCard_endpoint('la_emissions/v2/') + 'GB.json'
	];

	const primary = Promise.all(urlsPrimary.map(function (u) { return pbccCard_fetchJSON(u).catch(function () { return null; }); }))
		.then(([historicalData, populationData, overviewArr, GBData]) => {
			if (!historicalData) { return; }
			pbccCard_locationData = historicalData;
			pbccCard_populationLocationData = populationData || {};
			pbccCard_lsoaOverviewData = (overviewArr ? overviewArr[0] : null);
			pbccCard_gbHistoricalData = GBData || {};

			// Which comparisons this report can draw.
			//
			// "Similar areas" is the area classification of a NEIGHBOURHOOD, so it
			// only exists at LSOA level and is left out entirely above it.
			//
			// The local authority comparison needs a parent authority. At LSOA
			// level that comes from the overview record; on the area reports there
			// is no overview record, so the host page supplies it via
			// window.REPORT_CARD_PARENT_LA (see reports/la-report.js). A local
			// authority report sets none, because comparing an authority with
			// itself would just draw the same line twice.
			const parentLA = window.REPORT_CARD_PARENT_LA || null;
			const laCode = (pbccCard_lsoaOverviewData && pbccCard_lsoaOverviewData.LAD25CD) ||
				(parentLA && parentLA.code) || null;
			// At LSOA level the authority is unambiguous and the generic label
			// keeps this card matching the tool's own modal. On the area reports
			// the authority is named, because a constituency can straddle several
			// and a bare "Local Authority" would imply it had only one.
			pbccCard_laLabel = (!pbccCard_lsoaOverviewData && parentLA && parentLA.name)
				? parentLA.name
				: 'Local Authority';

			const urlsSecondary = [
				pbccCard_lsoaOverviewData
					? pbccCard_endpoint('oac_emissions/v2/') + pbccCard_lsoaOverviewData.lsoa_class_code + '.json'
					: null,
				laCode ? pbccCard_endpoint('la_emissions/v2/') + laCode + '.json' : null
			];

			return Promise.all(urlsSecondary.map(function (u) {
					return u ? pbccCard_fetchJSON(u).catch(function () { return null; }) : Promise.resolve(null);
				}))
				.then(([oacData, laData]) => {
					pbccCard_laHistoricalData = laData || {};
					pbccCard_oacHistoricalData = oacData || {};

					pbccCard_makeChartHistorical();
					pbccCard_makeChartPopulation();
					//console.log(lsoaHeadlineData);
					if (pbccCard_lsoaOverviewData) { pbccCard_switchPenPortSub(pbccCard_lsoaOverviewData.lsoa_class_name); }
					if (pbccCard_lsoaOverviewData) { pbccCard_switchPenPortSup(pbccCard_lsoaOverviewData.lsoa_class_name); }
					if (pbccCard_lsoaOverviewData) { pbccCard_lsoaCharacteristicsTable(pbccCard_lsoaOverviewData); }
				});
		})
		.catch(error => {
			console.error('Failed to load primary pbcc datasets:', error);
		});

	// Independent fetches
	/* Will be moved to retrofit tool
	const pVOA2010 = pbccCard_fetchJSON(pbccCard_endpoint('voa_2010/') + locationId + '.json')
		.then(data => { pbccCard_voa2010LocationData = data; pbccCard_makeChartVOA2010(); })
		.catch(err => { console.error('VOA2010 failed:', err); });

	const pVOA2020 = pbccCard_fetchJSON(pbccCard_endpoint('voa_2020/') + locationId + '.json')
		.then(data => { pbccCard_voa2020LocationData = data; pbccCard_makeChartVOA2020(); })
		.catch(err => { console.error('VOA2020 failed:', err); });
	*/
	const pCommunity = pbccCard_fetchJSON(pbccCard_endpoint('community_photo/v1/') + locationId + '.json')
		.then(data => { pbccCard_communityPicLocationData = data; pbccCard_makeCommunityPic(); })
		.catch(err => { console.error('Community photo failed:', err); });

    return Promise.all([primary,  pCommunity]); //pVOA2010, pVOA2020,
};

pbccCard_makeCommunityPic = function(){
  
  const names = pbccCard_communityPicLocationData["id"];
  const numbers = pbccCard_communityPicLocationData["pic"];
  const repeatedNames = numbers.flatMap((num, index) => Array(num).fill(names[index]));
  
  repeatedNames.forEach((name, index) => {
      const img = document.getElementById(`ff${index}`);
      if (img) {
          img.src = `/images/ui/family_photos/${name}.webp`;
          img.setAttribute('title', `${name}`.replaceAll('_', ' '));
      }
  });
}


pbccCard_makeChartOverview = function(){
  
  // overview Chart
  // Destroy old chart
	if(pbccCard_overviewChart){
		pbccCard_overviewChart.destroy();
	}
	
	
  // Create an object to store data for each category
  
  var component = [
		    // Label, field (e.g. Gas => dgkp2020), background colour, border colour
				['Gas', 'dgkp', 'rgba(166,206,227, 0.8)', 'rgba(166,206,227, 1)'],
				['Electricity', 'dekp', 'rgba(31,120,180, 0.8)', 'rgba(31,120,180, 1)'],
				['Other Heating', 'hokp', 'rgba(202,178,214, 0.8)', 'rgba(202,178,214, 1)'],
				['Other Housing', 'Bhokp', 'rgba(51,160,44, 0.8)', 'rgba(51,160,44, 1)'],
				['Cars', 'cep', 'rgba(251,154,153, 0.8)', 'rgba(251,154,153, 1)'],
				['Vans', 'vep', 'rgba(227,26,28, 0.8)', 'rgba(227,26,28, 1)'],
				['Bikes and Company Cars', 'cbep', 'rgba(227,26,28, 0.8)', 'rgba(227,26,28, 1)'],
				['Flights', 'Cfkp', 'rgba(255,127,0, 0.8)', 'rgba(255,127,0, 1)'],
				['Food & Drink', 'nep', 'rgba(202,178,214, 0.8)', 'rgba(202,178,214, 1)'],
				['Alchohol & Tobacco', 'akp', 'rgba(202,178,214, 0.8)', 'rgba(202,178,214, 1)'],
				['Clothing', 'ckp', 'rgba(106,61,154, 0.8)', 'rgba(106,61,154, 1)'],
				['Communication', 'Bckp', 'rgba(106,61,154, 0.8)', 'rgba(106,61,154, 1)'],
				['Furnishing', 'Bfkp', 'rgba(106,61,154, 0.8)', 'rgba(106,61,154, 1)'],
				['Recreation', 'rkp', 'rgba(255,255,153, 0.8)', 'rgba(255,255,153, 1)'],
				['Health', 'hkp', 'rgba(255,255,153, 0.8)', 'rgba(255,255,153, 1)'],
				['Education', 'ekp', 'rgba(255,255,153, 0.8)', 'rgba(255,255,153, 1)'],
				['Restaurant & Hotels', 'Brkp', 'rgba(177,89,40, 0.8)', 'rgba(177,89,40, 1)'],
				['Miscellaneous', 'Brkp', 'rgba(177,89,40, 0.8)', 'rgba(177,89,40, 1)'],
		  ]
  
  // NOTE: pbccCard_makeChartOverview is currently unused — the live overview is rendered by
  // pbccCard_makeChartHistorical (which is fully data-driven). Years are derived from the
  // data so this stays correct across the extended 2010-2022 range if revived.
  var years = (pbccCard_locationData['year'] || ['2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2020','2021','2022']).map(String);
  // Assemble the datasets to be shown
  
	const data = {datasets: []};

	component.forEach(comp => {
		data.datasets.push({
			label: comp[0],
			data: years.map(year => pbccCard_locationData[comp[1] + year]),
			backgroundColor: comp[2],
			borderColor: comp[3],
			borderWidth: 1
		});
	});

  data.labels = years;
  
  var overviewctx = document.getElementById('overview-chart').getContext('2d');
	pbccCard_consumptionFoodChart = new Chart(overviewctx, {
    type: 'bar',
					data: data,
					options: {
						scales: {
							y: {
								stacked: true,
								title: {
									display: true,
									text: 'kgCO₂e per person'
								},
								ticks: {
									beginAtZero: true,
								}
							},
							x: {
								stacked: true
							},
						},
						responsive: true,
						maintainAspectRatio: false
					}
  });
  
  
}


pbccCard_makeChartHistorical = function(){
  
  	// Destroy old charts
	if(pbccCard_overviewChart){pbccCard_overviewChart.destroy()}
	if(pbccCard_historicalChart){pbccCard_historicalChart.destroy()}
	if(pbccCard_consumptionFoodChart){pbccCard_consumptionFoodChart.destroy()}
	if(pbccCard_consumptionAlcoholChart){pbccCard_consumptionAlcoholChart.destroy()}
	if(pbccCard_consumptionFurnishingsChart){pbccCard_consumptionFurnishingsChart.destroy()}
	if(pbccCard_consumptionClothingChart){pbccCard_consumptionClothingChart.destroy()}
	if(pbccCard_consumptionCommunicationChart){pbccCard_consumptionCommunicationChart.destroy()}
	if(pbccCard_consumptionRecreationChart){pbccCard_consumptionRecreationChart.destroy()}
	if(pbccCard_consumptionRestaurantsChart){pbccCard_consumptionRestaurantsChart.destroy()}
	if(pbccCard_consumptionHealthChart){pbccCard_consumptionHealthChart.destroy()}
	if(pbccCard_consumptionEducationChart){pbccCard_consumptionEducationChart.destroy()}
	if(pbccCard_consumptionMiscellaneousChart){pbccCard_consumptionMiscellaneousChart.destroy()}
	if(pbccCard_consumptionTotalChart){pbccCard_consumptionTotalChart.destroy()}
	if(pbccCard_consumptionFlightsChart){pbccCard_consumptionFlightsChart.destroy()}
	if(pbccCard_consumptionVehiclePurchaseChart){pbccCard_consumptionVehiclePurchaseChart.destroy()}
	if(pbccCard_consumptionVehicleOtherChart){pbccCard_consumptionVehicleOtherChart.destroy()}
	if(pbccCard_gasChart){pbccCard_gasChart.destroy()}
	if(pbccCard_electricChart){pbccCard_electricChart.destroy()}
	if(pbccCard_otherHeatingChart){pbccCard_otherHeatingChart.destroy()}
	if(pbccCard_otherHousingChart){pbccCard_otherHousingChart.destroy()}
	if(pbccCard_carEmissionsChart){pbccCard_carEmissionsChart.destroy()}
	if(pbccCard_vanEmissionsChart){pbccCard_vanEmissionsChart.destroy()}
	if(pbccCard_bikeCompanyChart){pbccCard_bikeCompanyChart.destroy()}
	if(pbccCard_publicTransportChart){pbccCard_publicTransportChart.destroy()}
  
  
  	// Create an object to store data for each category
	var component = [
		    // Label, field (e.g. Gas => dgkp), background colour, border colour, gradelable, tableValue, tableGrade
				['Gas'                  , 'dom_gas_kgco2e_percap', 'rgb(184, 216, 233)', 'rgb(0,0,0)', 'dom_gas_grade' ,'data_gas_emissions_household','data_gas_emissions_grade'],
				['Electricity'          , 'dom_elec_kgco2e_percap', 'rgb(71,142,190)'   , 'rgb(0,0,0)', 'dom_elec_grade' ,'data_elec_emissions_household','data_elec_emissions_grade'],
				['Other Heating'        , 'heating_other_kgco2e_percap', 'rgb(1,108,89)'     , 'rgb(0,0,0)', 'heating_other_grade' ,'data_other_heating_emissions','data_other_heating_emissions_grade'],
				['Other Housing'        , 'housing_other_kgco2e_percap','rgb(37,52,148)'    , 'rgb(0,0,0)', 'housing_other_grade','data_other_housing_emissions','data_other_housing_emissions_grade'],
				['Furnishings'          , 'furnish_kgco2e_percap', 'rgb(141,211,199)'  , 'rgb(0,0,0)', 'furnish_grade' ,'data_furnishings_emissions','data_furnishings_emissions_grade'],
				['Food & Drink'         , 'food_kgco2e_percap' , 'rgb(213, 193, 222)', 'rgb(0,0,0)', 'food_grade' ,'data_food_emissions','data_food_emissions_grade'],
				['Alcohol & Tobacco'    , 'alcohol_kgco2e_percap' , 'rgb(136, 100, 174)', 'rgb(0,0,0)', 'alcohol_grade'  ,'data_alcohol_emissions','data_alcohol_emissions_grade'],
				['Clothing'             , 'clothing_kgco2e_percap' , 'rgb(231,41,138)'   , 'rgb(0,0,0)', 'clothing_grade' ,'data_clothing_emissions','data_clothing_emissions_grade'],
				['Communications'       , 'communication_kgco2e_percap', 'rgb(217,217,217)'  , 'rgb(0,0,0)', 'communication_grade' ,'data_communications_emissions','data_communications_emissions_grade'],
				['Recreation'           , 'recreation_kgco2e_percap' , 'rgb(255, 255, 173)', 'rgb(0,0,0)', 'recreation_grade'  ,'data_recreation_emissions','data_recreation_emissions_grade'],
				['Restaurants & Hotels' , 'restaurant_kgco2e_percap', 'rgb(252, 246, 61)' , 'rgb(0,0,0)', 'restaurant_grade' ,'data_restaurants_emissions','data_restaurants_emissions_grade'],
				['Health'               , 'health_kgco2e_percap' , 'rgb(102,194,164)'  , 'rgb(0,0,0)', 'health_grade'  ,'data_health_emissions','data_health_emissions_grade'],
				['Education'            , 'education_kgco2e_percap' , 'rgb(229,245,249)'  , 'rgb(0,0,0)', 'education_grade'  ,'data_education_emissions','data_education_emissions_grade'],
				['Miscellaneous'        , 'misc_kgco2e_percap', 'rgb(75,75,75)'     , 'rgb(0,0,0)', 'misc_grade'  ,'data_miscellaneous_emissions','data_miscellaneous_emissions_grade'],
				['Vehicle Purchase'     , 'transport_vehiclepurchase_kgco2e_percap', 'rgb(255, 0, 0)'    , 'rgb(0,0,0)', 'transport_vehiclepurchase_grade' ,'data_vehicle_purchase_emissions','data_vehicle_purchase_emissions_grade'],
				['Cars'                 , 'car_kgco2e_percap' , 'rgb(127,0,0)'      , 'rgb(0,0,0)', 'car_grade'  ,'data_car_emissions','data_car_emissions_grade'],
				['Vans'                 , 'van_kgco2e_percap' , 'rgb(179,0,0)'      , 'rgb(0,0,0)', 'van_grade'  ,'data_van_emissions','data_van_emissions_grade'],
				['Bikes & Company Vehicles' , 'company_bike_kgco2e_percap', 'rgb(215,48,31)'    , 'rgb(0,0,0)', 'company_bike_grade' ,'data_bikes_company_emissions','data_bikes_company_emissions_grade'],
				['Vehicle Maintenance'   , 'transport_optranequip_other_kgco2e_percap','rgb(253,187,132)'  , 'rgb(0,0,0)', 'transport_optranequip_other_grade','data_vehicle_maintaince_emissions','data_vehicle_maintaince_emissions_grade'],
				['Public Transport'     , 'transport_pt_kgco2e_percap', 'rgb(254,232,200)'  , 'rgb(0,0,0)', 'transport_pt_grade' ,'data_public_transport_emissions','data_public_transport_emissions_grade'],
				['Flights'              , 'flights_kgco2e_percap', 'rgb(254,178,76)'   , 'rgb(0,0,0)', 'flights_grade'  ,'data_flights_emissions','data_flights_emissions_grade'],
				['Goods & Services'     , 'goods_services_combined_kgco2e_percap', 'rgb(254,178,76)'  , 'rgb(0,0,0)', 'goods_services_combined_grade','data_consumption_emissions','data_consumption_emissions_grade']
		  ]
	
  var component_la = [
    // Label, field (e.g. Gas => dgkp), background colour, border colour, gradelable, tableValue, tableGrade
		['Gas LA'                  , 'dom_gas_kgco2e_percap', 'rgb(157,130,255)', 'rgb(0,0,0)'],
		['Electricity LA'          , 'dom_elec_kgco2e_percap', 'rgb(157,130,255)'   , 'rgb(0,0,0)'],
		['Other Heating LA'        , 'heating_other_kgco2e_percap', 'rgb(157,130,255)'     , 'rgb(0,0,0)'],
		['Other Housing LA'        , 'housing_other_kgco2e_percap','rgb(157,130,255)'    , 'rgb(0,0,0)'],
		['Furnishings LA'          , 'furnish_kgco2e_percap', 'rgb(157,130,255)'  , 'rgb(0,0,0)'],
		['Food & Drink LA'         , 'food_kgco2e_percap' , 'rgb(157,130,255)', 'rgb(0,0,0)'],
		['Alcohol & Tobacco LA'    , 'alcohol_kgco2e_percap' , 'rgb(157,130,255)', 'rgb(0,0,0)'],
		['Clothing LA'             , 'clothing_kgco2e_percap' , 'rgb(157,130,255)'   , 'rgb(0,0,0)'],
		['Communications LA'       , 'communication_kgco2e_percap', 'rgb(157,130,255)'  , 'rgb(0,0,0)'],
		['Recreation LA'           , 'recreation_kgco2e_percap' , 'rgb(157,130,255)', 'rgb(0,0,0)'],
		['Restaurants & Hotels LA' , 'restaurant_kgco2e_percap', 'rgb(157,130,255)' , 'rgb(0,0,0)'],
		['Health LA'               , 'health_kgco2e_percap' , 'rgb(157,130,255)'  , 'rgb(0,0,0)'],
		['Education LA'            , 'education_kgco2e_percap' , 'rgb(157,130,255)'  , 'rgb(0,0,0)'],
		['Miscellaneous LA'        , 'misc_kgco2e_percap', 'rgb(157,130,255)'     , 'rgb(0,0,0)'],
		['Vehicle Purchase LA'     , 'transport_vehiclepurchase_kgco2e_percap', 'rgb(157,130,255)', 'rgb(0,0,0)'],
		['Cars LA'                 , 'car_kgco2e_percap' , 'rgb(157,130,255)'      , 'rgb(0,0,0)'],
		['Vans LA'                 , 'van_kgco2e_percap' , 'rgb(157,130,255)'      , 'rgb(0,0,0)'],
		['Bikes & Company Vehicles LA' , 'company_bike_kgco2e_percap', 'rgb(157,130,255)'    , 'rgb(0,0,0)'],
		['Vehicle Maintenance LA'   , 'transport_optranequip_other_kgco2e_percap','rgb(157,130,255)', 'rgb(0,0,0)'  ],
		['Public Transport LA'     , 'transport_pt_kgco2e_percap', 'rgb(157,130,255)'  , 'rgb(0,0,0)'],
		['Flights LA'              , 'flights_kgco2e_percap', 'rgb(157,130,255)'   , 'rgb(0,0,0)'],
		['Goods & Services LA'     , 'goods_services_combined_kgco2e_percap', 'rgb(157,130,255)', 'rgb(0,0,0)']
  ]
  
  var component_oac = [
    // Label, field (e.g. Gas => dgkp), background colour, border colour, gradelable, tableValue, tableGrade
		['Gas Similar Areas'                  , 'dom_gas_kgco2e_percap', 'rgb(255, 130, 157)', 'rgb(0,0,0)'],
		['Electricity Similar Areas'          , 'dom_elec_kgco2e_percap', 'rgb(255, 130, 157)'   , 'rgb(0,0,0)'],
		['Other Heating Similar Areas'        , 'heating_other_kgco2e_percap', 'rgb(255, 130, 157)'     , 'rgb(0,0,0)'],
		['Other Housing Similar Areas'        , 'housing_other_kgco2e_percap','rgb(255, 130, 157)'    , 'rgb(0,0,0)'],
		['Furnishings Similar Areas'          , 'furnish_kgco2e_percap', 'rgb(255, 130, 157)'  , 'rgb(0,0,0)'],
		['Food & Drink Similar Areas'         , 'food_kgco2e_percap' , 'rgb(255, 130, 157)', 'rgb(0,0,0)'],
		['Alcohol & Tobacco Similar Areas'    , 'alcohol_kgco2e_percap' , 'rgb(255, 130, 157)', 'rgb(0,0,0)'],
		['Clothing Similar Areas'             , 'clothing_kgco2e_percap' , 'rgb(255, 130, 157)'   , 'rgb(0,0,0)'],
		['Communications Similar Areas'       , 'communication_kgco2e_percap', 'rgb(255, 130, 157)'  , 'rgb(0,0,0)'],
		['Recreation Similar Areas'           , 'recreation_kgco2e_percap' , 'rgb(255, 130, 157)', 'rgb(0,0,0)'],
		['Restaurants & Hotels Similar Areas' , 'restaurant_kgco2e_percap', 'rgb(255, 130, 157)' , 'rgb(0,0,0)'],
		['Health Similar Areas'               , 'health_kgco2e_percap' , 'rgb(255, 130, 157)'  , 'rgb(0,0,0)'],
		['Education Similar Areas'            , 'education_kgco2e_percap' , 'rgb(255, 130, 157)'  , 'rgb(0,0,0)'],
		['Miscellaneous Similar Areas'        , 'misc_kgco2e_percap', 'rgb(255, 130, 157)'     , 'rgb(0,0,0)'],
		['Vehicle Purchase Similar Areas'     , 'transport_vehiclepurchase_kgco2e_percap', 'rgb(255, 130, 157)', 'rgb(0,0,0)'],
		['Cars Similar Areas'                 , 'car_kgco2e_percap' , 'rgb(255, 130, 157)'      , 'rgb(0,0,0)'],
		['Vans Similar Areas'                 , 'van_kgco2e_percap' , 'rgb(255, 130, 157)'      , 'rgb(0,0,0)'],
		['Bikes & Company Vehicles Similar Areas' , 'company_bike_kgco2e_percap', 'rgb(255, 130, 157)'    , 'rgb(0,0,0)'],
		['Vehicle Maintenance Similar Areas'   , 'transport_optranequip_other_kgco2e_percap','rgb(255, 130, 157)', 'rgb(0,0,0)'  ],
		['Public Transport Similar Areas'     , 'transport_pt_kgco2e_percap', 'rgb(255, 130, 157)'  , 'rgb(0,0,0)'],
		['Flights Similar Areas'              , 'flights_kgco2e_percap', 'rgb(255, 130, 157)'   , 'rgb(0,0,0)'],
		['Goods & Services Similar Areas'     , 'goods_services_combined_kgco2e_percap', 'rgb(255, 130, 157)', 'rgb(0,0,0)']
  ]
  
  var component_GB = [
    // Label, field (e.g. Gas => dgkp), background colour, border colour, gradelable, tableValue, tableGrade
		['Gas GB'                  , 'dom_gas_kgco2e_percap', 'rgb(130,255,61)', 'rgb(0,0,0)'],
		['Electricity GB'          , 'dom_elec_kgco2e_percap', 'rgb(130,255,61)'   , 'rgb(0,0,0)'],
		['Other Heating GB'        , 'heating_other_kgco2e_percap', 'rgb(130,255,61)'     , 'rgb(0,0,0)'],
		['Other Housing GB'        , 'housing_other_kgco2e_percap','rgb(130,255,61)'    , 'rgb(0,0,0)'],
		['Furnishings GB'          , 'furnish_kgco2e_percap', 'rgb(130,255,61)'  , 'rgb(0,0,0)'],
		['Food & Drink GB'         , 'food_kgco2e_percap' , 'rgb(130,255,61)', 'rgb(0,0,0)'],
		['Alcohol & Tobacco GB'    , 'alcohol_kgco2e_percap' , 'rgb(130,255,61)', 'rgb(0,0,0)'],
		['Clothing GB'             , 'clothing_kgco2e_percap' , 'rgb(130,255,61)'   , 'rgb(0,0,0)'],
		['Communications GB'       , 'communication_kgco2e_percap', 'rgb(130,255,61)'  , 'rgb(0,0,0)'],
		['Recreation GB'           , 'recreation_kgco2e_percap' , 'rgb(130,255,61)', 'rgb(0,0,0)'],
		['Restaurants & Hotels GB' , 'restaurant_kgco2e_percap', 'rgb(130,255,61)' , 'rgb(0,0,0)'],
		['Health GB'               , 'health_kgco2e_percap' , 'rgb(130,255,61)'  , 'rgb(0,0,0)'],
		['Education GB'            , 'education_kgco2e_percap' , 'rgb(130,255,61)'  , 'rgb(0,0,0)'],
		['Miscellaneous GB'        , 'misc_kgco2e_percap', 'rgb(130,255,61)'     , 'rgb(0,0,0)'],
		['Vehicle Purchase GB'     , 'transport_vehiclepurchase_kgco2e_percap', 'rgb(130,255,61)', 'rgb(0,0,0)'],
		['Cars GB'                 , 'car_kgco2e_percap' , 'rgb(130,255,61)'      , 'rgb(0,0,0)'],
		['Vans GB'                 , 'van_kgco2e_percap' , 'rgb(130,255,61)'      , 'rgb(0,0,0)'],
		['Bikes & Company Vehicles GB' , 'company_bike_kgco2e_percap', 'rgb(130,255,61)'    , 'rgb(0,0,0)'],
		['Vehicle Maintenance GB'   , 'transport_optranequip_other_kgco2e_percap','rgb(130,255,61)', 'rgb(0,0,0)'  ],
		['Public Transport GB'     , 'transport_pt_kgco2e_percap', 'rgb(130,255,61)'  , 'rgb(0,0,0)'],
		['Flights GB'              , 'flights_kgco2e_percap', 'rgb(130,255,61)'   , 'rgb(0,0,0)'],
		['Goods & Services GB'     , 'goods_services_combined_kgco2e_percap', 'rgb(130,255,61)', 'rgb(0,0,0)']
  ]
  
	const data = {datasets: []};
	const data_la = {datasets: []};
	const data_oac = {datasets: []};
	const data_gb = {datasets: []};

	component.forEach(comp => {
		data.datasets.push({
			label: comp[0],
			data: pbccCard_locationData[comp[1]],
			gradelabel: pbccCard_locationData[comp[4]],
			backgroundColor: comp[2],
			borderColor: comp[3],
			borderWidth: 1,
			order: 0,
			stack: 'Stack 0'
		});
	});
	
	//console.log(pbccCard_laHistoricalData);
	component_la.forEach(comp => {
		const values = pbccCard_laHistoricalData[comp[1]] || [];
		
		data_la.datasets.push({
		label: comp[0],
		data: values,
		gradelabel: Array.isArray(values) ? new Array(values.length).fill('') : [],
		backgroundColor: comp[2],
		borderColor: comp[3],
		borderWidth: 1,
		stack: 'Stack 1'
		});
	});
  
	component_oac.forEach(comp => {
		const values = pbccCard_oacHistoricalData[comp[1]] || [];
		
		data_oac.datasets.push({
		label: comp[0],
		data: values,
		gradelabel: Array.isArray(values) ? new Array(values.length).fill('') : [],
		backgroundColor: comp[2],
		borderColor: comp[3],
		borderWidth: 1,
		stack: 'Stack 2'
		});
	});
  
	component_GB.forEach(comp => {
		const values = pbccCard_gbHistoricalData[comp[1]] || [];
		
		data_gb.datasets.push({
		label: comp[0],
		data: values,
		gradelabel: Array.isArray(values) ? new Array(values.length).fill('') : [],
		backgroundColor: comp[2],
		borderColor: comp[3],
		borderWidth: 1,
		stack: 'Stack 3'
		});
	});

  data.labels = pbccCard_locationData['year'];
  
  
  function getStandardLabel(stack) {
    switch (stack) {
      case 'Stack 0': return 'This area';
      case 'Stack 1': return pbccCard_laLabel;
      case 'Stack 2': return 'Similar Areas';
      case 'Stack 3': return 'Great Britain';
      default: return stack;
    }
  }

  // A comparison with no data must not reach the charts. Chart.js still draws a
  // legend entry for an empty dataset, so leaving them in advertises lines that
  // are never plotted: before this, every area report promised four comparisons
  // and drew two.
  const hasValues = function (ds) {
    return Array.isArray(ds.data) && ds.data.some(function (v) {
      return v !== null && v !== undefined && !(typeof v === 'number' && isNaN(v));
    });
  };

  

 //console.log(data_la);

  const combinedData = {
    labels: pbccCard_locationData['year'],
    datasets: [
      ...data.datasets.map(ds => ({ ...ds, standardLabel: getStandardLabel(ds.stack) })),
      ...data_la.datasets.map(ds => ({ ...ds, standardLabel: getStandardLabel(ds.stack) })),
      ...data_oac.datasets.map(ds => ({ ...ds, standardLabel: getStandardLabel(ds.stack) })),
      ...data_gb.datasets.map(ds => ({ ...ds, standardLabel: getStandardLabel(ds.stack) }))
    ].filter(hasValues)
  };

  //console.log(combinedData);

  // Make Overview table
  // Use the latest available year for the headline grade/figure, derived from
  // the data so it tracks the extended 2010-2022 timeseries automatically
  // (previously hard-coded to 2019).
  const yearIndex = data.labels.length - 1;

  // Headline Grade
  // Set grade image and alt text. Grades are relative to other areas of the
  // same type, so not every feed carries them (the GB row in la_emissions is
  // ungraded, for one). Only show the badge when a grade exists - otherwise
  // gradelabel[yearIndex] would be read off undefined and throw,
  // aborting the whole chart build.
  const Totalgrade = (pbccCard_locationData['total_grade'] || [])[yearIndex];
  const TotalgradeImg = document.getElementById('data_total_emissions_grade');
  if (TotalgradeImg) {
    if (Totalgrade) {
      TotalgradeImg.src = `/images/grades/${Totalgrade}.webp`;
      TotalgradeImg.alt = `Grade ${Totalgrade}`;
    } else {
      TotalgradeImg.style.display = 'none';
    }
  }
  document.getElementById("data_total_emissions_percap").innerHTML =
    (pbccCard_locationData['total_kgco2e_percap'] || [])[yearIndex] +
    ' kgCO<sub>2</sub>e per person per year in ' +
    data.labels[yearIndex];
  
  //console.log(pbccCard_locationData['total_grade'][yearIndex]);
  //document.getElementById("data_total_emissions_grade").innerHTML = pbccCard_locationData[comp[4]];
  //document.getElementById("data_total_emissions_percap").innerHTML = data.dekp2019;

  // Fill the overview table
  component.forEach(comp => {
    const [label, field, , , gradeField, valueId, gradeId] = comp;
    const dataset = data.datasets.find(ds => ds.label === label);
    if (!dataset) return;
    // Set the per-person emissions value. A null means the pipeline suppressed
    // this component for this zone-year - company vehicles in a neighbourhood
    // where a fleet is registered at one address, for instance. Those are left
    // out of the total and out of the chart, so print NA rather than "null".
    const value = (dataset.data || [])[yearIndex];
    document.getElementById(valueId).innerHTML =
      (value === null || value === undefined ? 'NA' : value);

    // Set grade image and alt text (only if this feed carries grades)
    const grade = (dataset.gradelabel || [])[yearIndex];
    const gradeImg = document.getElementById(gradeId);
    if (!gradeImg) return;
    if (grade) {
      gradeImg.src = `/images/grades/${grade}.webp`;
      gradeImg.alt = `Grade ${grade}`;
    } else {
      gradeImg.style.display = 'none';
    }
  });

		// We draw the horizontal threshold line via a plugin so it always appears on top
		// and does not create a legend entry. (No dataset is pushed here.)
		//console.log(data.datasets);

		// Define the threshold plugin here so we can attach it to the historical chart as well.
		const thresholdLinePlugin = {
			id: 'thresholdLinePlugin',
			afterDatasetsDraw(chart, args, options) {
				const pluginOpts = (chart.options && chart.options.plugins && chart.options.plugins.thresholdLinePlugin) || options || {};
				const value = pluginOpts.value;
				if (typeof value !== 'number') return;
				const ctx = chart.ctx;
				const yScale = chart.scales['y'];
				if (!yScale) return;
				const y = yScale.getPixelForValue(value);
				ctx.save();
				ctx.strokeStyle = pluginOpts.color || 'black';
				ctx.lineWidth = pluginOpts.width || 2;
				if (Array.isArray(pluginOpts.dash) && pluginOpts.dash.length) ctx.setLineDash(pluginOpts.dash);
				ctx.beginPath();
				ctx.moveTo(chart.chartArea.left, y);
				ctx.lineTo(chart.chartArea.right, y);
				ctx.stroke();
				ctx.restore();
			}
		};

	pbccCard_historicalChart = new Chart(document.getElementById('historical-chart').getContext('2d'), {
    type: 'bar',
    data: {
 		  labels: data.labels.filter(d => d.label != 'Goods & Services'),
 		  datasets: data.datasets.filter(d => d.label != 'Goods & Services')
 		},
 		plugins: [thresholdLinePlugin],
 		options: {
			scales: {
				y: {
					stacked: true,
						title: {
									display: true,
									text: 'kgCO₂e per person'
								},
					ticks: {
						beginAtZero: true,
					}
				},
				x: {
					stacked: true
				},
			},
			plugins: {
				// plugin options for thresholdLinePlugin (draws a single line on top)
				thresholdLinePlugin: {
					value: 2849,
					color: 'black',
					width: 3,
					dash: []
				},
				legend: {
					position: 'right',
					reverse: true,
				labels: {
						font: { size: 11 },
						// Reduce spacing between legend items and tighten rows
						padding: 4,
						boxWidth: 10
					}
				}
	      },
			responsive: true,
			maintainAspectRatio: false
		}
		});
		const data_overview = {datasets: []};

		// All four sources are now bins covering the same 2010-2022 range, but
		// they are rebuilt and deployed independently, so line them up on the
		// year VALUE rather than assuming a shared index. If a source is ever
		// redeployed one year behind the others, this leaves its bar out of the
		// comparison instead of silently showing an older year's figure beside
		// the current one (or reading past the end of the array for no bar).
		// Sources absent altogether on area reports give -1 -> undefined, as
		// before.
		const latestYear = (pbccCard_locationData['year'] || [])[yearIndex];
		const yearIndexIn = function (source) {
			const i = (source['year'] || []).indexOf(latestYear);
			return (i === -1 ? undefined : i);
		};
		// One column per comparison that actually has a figure for the latest
		// year. A source that is absent at this level (there is no "similar
		// areas" grouping above LSOA, and a local authority report has no parent
		// authority) drops out rather than standing as an empty column under a
		// label, and the labels follow the columns that remain.
		const overviewSources = [
			{ label: 'This Area', data: pbccCard_locationData },
			{ label: pbccCard_laLabel, data: pbccCard_laHistoricalData },
			{ label: 'Similar Areas', data: pbccCard_oacHistoricalData },
			{ label: 'Great Britain', data: pbccCard_gbHistoricalData }
		].map(function (s) {
			return { label: s.label, data: s.data, idx: yearIndexIn(s.data || {}) };
		}).filter(function (s) {
			return s.idx !== undefined && s.data && Object.keys(s.data).length > 0;
		});

		component.forEach(comp => {
			data_overview.datasets.push({
				label: comp[0],
				// Each source is still guarded with || []: a feed can carry the
				// latest year but not every category, and indexing undefined would
				// throw and abort the whole chart build (consumption, energy, etc.).
				data: overviewSources.map(function (s) { return (s.data[comp[1]] || [])[s.idx]; }),
				backgroundColor: comp[2],
				borderColor: comp[3],
				borderWidth: 1,
				stack: 'Stack 0'
			});
		});

		data_overview.datasets = data_overview.datasets.filter(d => !d.label.includes('Goods & Services'));

        data_overview.labels = overviewSources.map(function (s) { return s.label; });



pbccCard_overviewChart = new Chart(document.getElementById('overview-chart').getContext('2d'), {
    type: 'bar',
		data: data_overview,
		plugins: [thresholdLinePlugin],
		options: {
			scales: {
				y: {
					stacked: true,
						title: {
									display: true,
									text: 'kgCO₂e per person'
								},
					ticks: {
						beginAtZero: true,
					}
				},
				x: {
					stacked: true
				},
			},
			plugins: {
				// plugin options for thresholdLinePlugin
				thresholdLinePlugin: {
					value: 2849,
					color: 'black',
					width: 3,
					dash: []
				},
				legend: {
					position: 'right',
					reverse: true,
					labels: {
						font: { size: 11 },
						// Reduce spacing between legend items and tighten rows
						padding: 4,
						boxWidth: 10
					}
				}
			},
			responsive: true,
			maintainAspectRatio: false
		}
  });
  
 
  var barChartOptions = {
						scales: {
							y: {
								stacked: true,
								title: {
									display: true,
									text: 'kgCO₂e per person'
								},
								ticks: {
									beginAtZero: true,
								}
							},
							x: {
								stacked: true
							},
						},
						responsive: true,
						maintainAspectRatio: false
					};
					
	// Lables above bar plugin
	const taxLabelPlugin = {
  id: 'taxLabelPlugin',
  afterDatasetsDraw(chart, args, options) {
			const { ctx } = chart;
			chart.data.datasets.forEach((dataset, datasetIndex) => {
				const meta = chart.getDatasetMeta(datasetIndex);
				if (!meta || !Array.isArray(meta.data)) return;
				meta.data.forEach((bar, index) => {
					// only draw labels if gradelabel exists for this dataset
					const hasGradeArray = dataset && Array.isArray(dataset.gradelabel);
					const value = hasGradeArray ? dataset.gradelabel[index] : undefined;
					if (value === undefined || value === null || value === '') return;
					ctx.save();
					ctx.fillStyle = 'black';
					ctx.font = '12px sans-serif';
					ctx.textAlign = 'center';
					ctx.textBaseline = 'bottom';
					// Coordinates exist for bars and points as x/y; fallback to center if not present
					const x = (bar && typeof bar.x === 'number') ? bar.x : ((bar && bar.left && bar.right) ? (bar.left + bar.right) / 2 : 0);
					const y = (bar && typeof bar.y === 'number') ? bar.y : ((bar && bar.top && bar.bottom) ? (bar.top + bar.bottom) / 2 : 0);
					ctx.fillText(`${value}`, x, y - 5);
					ctx.restore();
				});
			});
    }
  };
  
  function makeStandardConsumptionChart(id,filter){
		// Create options for line charts based on the shared barChartOptions
		const lineOptions = {
			...barChartOptions,
			scales: {
				y: {
					// ensure y-axis always starts at zero
					min: 0,
					ticks: {
						beginAtZero: true
					}
				},
				x: {
					// lines shouldn't be stacked
					stacked: false
				}
			}
		};

		// fixed colour for the "This area" line across all charts
		const THIS_AREA_COLOUR = 'rgb(31,120,180)';

		const datasets = combinedData.datasets
			.filter(d => d.label.includes(filter))
			.map(d => {
				// use a consistent colour for 'This area', otherwise use the dataset's background colour
				const baseColour = (d.standardLabel === 'This area') ? THIS_AREA_COLOUR : (d.backgroundColor || d.borderColor || 'rgb(0,0,0)');

				return {
					label: d.standardLabel,
					data: d.data,
					// preserve gradelabel so the label plugin can draw annotations
					gradelabel: d.gradelabel,
					// colour the line itself
					borderColor: baseColour,
					// use same colour for points
					backgroundColor: baseColour,
					pointBackgroundColor: baseColour,
					pointBorderColor: baseColour,
					fill: false,
					tension: 0.2,
					borderWidth: 2
				};
			});

		// compute max value across all datasets so we can ensure the y-axis max is at least 500
		let dataMax = -Infinity;
		datasets.forEach(ds => {
			if (!Array.isArray(ds.data)) return;
			ds.data.forEach(v => {
				const n = Number(v);
				if (!Number.isNaN(n) && n > dataMax) dataMax = n;
			});
		});
		if (dataMax === -Infinity) dataMax = 0;

		// Choose a "nice" rounded max above the data max so axis ticks land on round numbers.
		// Use approximately 8 intervals (so small charts get steps like 200, larger ones 1000, etc.).
		const desiredIntervals = 8;
		let niceMax = dataMax;

		if (dataMax <= 0) {
			niceMax = 500;
		} else {
			// compute a raw step and round it up to a "nice" step (1, 2, 2.5, 5, 10 * 10^exp)
			const rawStep = dataMax / desiredIntervals;
			const exp = Math.floor(Math.log10(Math.max(rawStep, 1e-12)));
			const pow = Math.pow(10, exp);
			const frac = rawStep / pow;

			let niceFrac;
			if (frac <= 1) niceFrac = 1;
			else if (frac <= 2) niceFrac = 2;
			else if (frac <= 2.5) niceFrac = 2.5;
			else if (frac <= 5) niceFrac = 5;
			else niceFrac = 10;

			const niceStep = niceFrac * pow;
			niceMax = niceStep * Math.ceil(dataMax / niceStep);
			// ensure we never go below 500
			if (niceMax < 500) niceMax = 500;
		}

		// apply the computed nice max to the line chart options
		lineOptions.scales.y.max = niceMax;

		const chart = new Chart(document.getElementById(id).getContext('2d'), {
			type: 'line',
			data: {
				labels: combinedData.labels,
				datasets: datasets
			},
			options: lineOptions,
			plugins: [taxLabelPlugin]
		});

		return chart;
	}
  
  pbccCard_consumptionTotalChart = makeStandardConsumptionChart('consumptionTotal-chart','Goods & Services');
  pbccCard_consumptionFoodChart = makeStandardConsumptionChart('consumptionFood-chart','Food & Drink');
  pbccCard_consumptionAlcoholChart = makeStandardConsumptionChart('consumptionAlcohol-chart','Alcohol & Tobacco');
  pbccCard_consumptionFurnishingsChart = makeStandardConsumptionChart('consumptionFurnishings-chart','Furnishings');
  pbccCard_consumptionClothingChart = makeStandardConsumptionChart('consumptionClothing-chart','Clothing');
  pbccCard_consumptionCommunicationChart = makeStandardConsumptionChart('consumptionCommunication-chart','Communications');
  pbccCard_consumptionRecreationChart = makeStandardConsumptionChart('consumptionRecreation-chart','Recreation');
  pbccCard_consumptionRestaurantsChart = makeStandardConsumptionChart('consumptionRestaurants-chart','Restaurants & Hotels');
  pbccCard_consumptionHealthChart = makeStandardConsumptionChart('consumptionHealth-chart','Health');
  pbccCard_consumptionEducationChart = makeStandardConsumptionChart('consumptionEducation-chart','Education');
  pbccCard_consumptionMiscellaneousChart = makeStandardConsumptionChart('consumptionMiscellaneous-chart','Miscellaneous');
  pbccCard_consumptionFlightsChart = makeStandardConsumptionChart('consumptionFlights-chart','Flights');
  pbccCard_consumptionVehiclePurchaseChart = makeStandardConsumptionChart('consumptionVehiclePurchase-chart','Vehicle Purchase');
  pbccCard_consumptionVehicleOtherChart = makeStandardConsumptionChart('consumptionVehicleOther-chart','Vehicle Maintenance');
  pbccCard_gasChart = makeStandardConsumptionChart('gasEmissions-chart','Gas');
  pbccCard_electricChart = makeStandardConsumptionChart('electricityEmissions-chart','Electricity');
  pbccCard_otherHeatingChart = makeStandardConsumptionChart('heatingOther-chart','Other Heating');
  pbccCard_otherHousingChart = makeStandardConsumptionChart('housingOther-chart','Other Housing');
  pbccCard_carEmissionsChart = makeStandardConsumptionChart('carEmissions-chart','Cars');
  pbccCard_vanEmissionsChart = makeStandardConsumptionChart('vanEmissions-chart','Vans');
  pbccCard_bikeCompanyChart = makeStandardConsumptionChart('bikeCompany-chart','Bikes & Company Vehicles');
  pbccCard_publicTransportChart = makeStandardConsumptionChart('publicTransport-chart','Public Transport');

}

pbccCard_makeChartVOA2010 = function(){
  
  	// overview Chart
  	// Destroy old chart
	if(pbccCard_dwellingsctChart){
		pbccCard_dwellingsctChart.destroy();
	}
  
  	//console.log(pbccCard_voa2010LocationData);
 
	const years = pbccCard_voa2010LocationData['year'];	  
	const bA = pbccCard_voa2010LocationData['banda'];
  	const bB = pbccCard_voa2010LocationData['bandb'];
  	const bC = pbccCard_voa2010LocationData['bandc'];
  	const bD = pbccCard_voa2010LocationData['bandd'];
  	const bE = pbccCard_voa2010LocationData['bande'];
  	const bF = pbccCard_voa2010LocationData['bandf'];
  	const bG = pbccCard_voa2010LocationData['bandg'];
  	const bH = pbccCard_voa2010LocationData['bandh'];
  	const bI = pbccCard_voa2010LocationData['bandi'];
  
  
  var dwellingsctctx = document.getElementById('dwellingsct-chart').getContext('2d');
	pbccCard_dwellingsctChart = new Chart(dwellingsctctx, {
		type: 'bar',
		data: {
			labels: years,
			datasets: [{
				label: 'A',
				data: bA,
				backgroundColor: 'rgba(77,146,33, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: 'B',
				data: bB,
				backgroundColor: 'rgba(127,188,65, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: 'C',
				data: bC,
				backgroundColor: 'rgba(184,225,134, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: 'D',
				data: bD,
				backgroundColor: 'rgba(230,245,208, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: 'E',
				data: bE,
				backgroundColor: 'rgba(247,247,247, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
      {
				label: 'F',
				data: bF,
				backgroundColor: 'rgba(253,224,239, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
      {
				label: 'G',
				data: bG,
				backgroundColor: 'rgba(241,182,218, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
      {
				label: 'H',
				data: bH,
				backgroundColor: 'rgba(222,119,174, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
      {
				label: 'I',
				data: bI,
				backgroundColor: 'rgba(197,27,125, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			]
		},
		options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
							y: {
								stacked: true,
								ticks: {
									beginAtZero: true
								}
							},
							x: {
								stacked: true
							}
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    }
	});
  
  
}


pbccCard_makeChartVOA2020 = function(){
  
  // Destroy old chart
	if(pbccCard_dwellingstypeChart){
		pbccCard_dwellingstypeChart.destroy();
	}
	
	if(pbccCard_dwellingsbedroomsChart){
		pbccCard_dwellingsbedroomsChart.destroy();
	}
	
	if(pbccCard_dwellingsageChart){
		pbccCard_dwellingsageChart.destroy();
	}
  
	const years = pbccCard_voa2020LocationData['year'];	  

  var dwellingstypectx = document.getElementById('dwellingstype-chart').getContext('2d');
	pbccCard_dwellingstypeChart = new Chart(dwellingstypectx, {
		type: 'bar',
		data: {
			labels: years,
			datasets: [{
				label: 'Bungalow',
				data: pbccCard_voa2020LocationData['bungalow'],
				backgroundColor: 'rgba(105, 60, 153, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: 'Flat/Maisonette',
				data: pbccCard_voa2020LocationData['flatmais'],
				backgroundColor: 'rgba(227, 26, 28, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: 'Terraced',
				data: pbccCard_voa2020LocationData['terraced'],
				backgroundColor: 'rgba(17, 219, 13, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: 'Semi-Detached',
				data: pbccCard_voa2020LocationData['semi'],
				backgroundColor: 'rgba(14, 156, 11, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: 'Detached',
				data: pbccCard_voa2020LocationData['detached'],
				backgroundColor: 'rgba(8, 82, 7, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
      {
				label: 'Annexe',
				data: pbccCard_voa2020LocationData['annexe'],
				backgroundColor: 'rgba(31, 120, 180, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
      {
				label: 'Caravan/Boat/Mobile home',
				data: pbccCard_voa2020LocationData['caravanboatmobilehome'],
				backgroundColor: 'rgba(250, 124, 0, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
      {
				label: 'Unknown',
				data: pbccCard_voa2020LocationData['unknown'],
				backgroundColor: 'rgba(135, 136, 138, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			}
			]
		},
		options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
							y: {
								stacked: true,
								ticks: {
									beginAtZero: true
								}
							},
							x: {
								stacked: true
							}
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    }
	});
	
	
	var dwellingsbedroomsctx = document.getElementById('dwellingsbedrooms-chart').getContext('2d');
	pbccCard_dwellingsbedroomsChart = new Chart(dwellingsbedroomsctx, {
		type: 'bar',
		data: {
			labels: years,
			datasets: [{
				label: '1',
				data: pbccCard_voa2020LocationData['bed1'],
				backgroundColor: 'rgba(204,235,197, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: '2',
				data: pbccCard_voa2020LocationData['bed2'],
				backgroundColor: 'rgba(168,221,181, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: '3',
				data: pbccCard_voa2020LocationData['bed3'],
				backgroundColor: 'rgba(123,204,196, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: '4',
				data: pbccCard_voa2020LocationData['bed4'],
				backgroundColor: 'rgba(78,179,211, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: '5',
				data: pbccCard_voa2020LocationData['bed5'],
				backgroundColor: 'rgba(43,140,190, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
      {
				label: '6+',
				data: pbccCard_voa2020LocationData['bed6'],
				backgroundColor: 'rgba(8,88,158, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			}
			]
		},
		options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
							y: {
								stacked: true,
								ticks: {
									beginAtZero: true
								}
							},
							x: {
								stacked: true
							}
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    }
	});
	
	
	var dwellingsagectx = document.getElementById('dwellingsage-chart').getContext('2d');
	pbccCard_dwellingsageChart = new Chart(dwellingsagectx, {
		type: 'bar',
		data: {
			labels: years,
			datasets: [{
				label: 'pre 1900',
				data: pbccCard_voa2020LocationData['bppre1900'],
				backgroundColor: 'rgba(158, 1, 66, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: '1900-18',
				data: pbccCard_voa2020LocationData['bp19001918'],
				backgroundColor: 'rgba(213, 62, 79, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: '1919-29',
				data: pbccCard_voa2020LocationData['bp19191929'],
				backgroundColor: 'rgba(244, 109, 67, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: '1930-39',
				data: pbccCard_voa2020LocationData['bp19301939'],
				backgroundColor: 'rgba(244, 109, 67, 0.8)',
				borderColor: 'rgba(253, 174, 97)',
				borderWidth: 1,
				order: 1
			},
			{
				label: '1945-54',
				data: pbccCard_voa2020LocationData['bp19451954'],
				backgroundColor: 'rgba(254,224,139, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
      {
				label: '1955-64',
				data: pbccCard_voa2020LocationData['bp19551964'],
				backgroundColor: 'rgba(255,255,191, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
      {
				label: '1965-72',
				data: pbccCard_voa2020LocationData['bp19651972'],
				backgroundColor: 'rgba(230,245,152, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
      {
				label: '1973-82',
				data: pbccCard_voa2020LocationData['bp19731982'],
				backgroundColor: 'rgba(171,221,164, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
      {
				label: '1983-92',
				data: pbccCard_voa2020LocationData['bp19831992'],
				backgroundColor: 'rgba(102,194,165, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},			
      {
				label: '1993-99',
				data: pbccCard_voa2020LocationData['bp19931999'],
				backgroundColor: 'rgba(50,136,189, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},			
      {
				label: '2000-08',
				data: pbccCard_voa2020LocationData['bp20002008'],
				backgroundColor: 'rgba(94,79,162, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},			
      {
				label: '2009-21',
				data: pbccCard_voa2020LocationData['bp20092021'],
				backgroundColor: 'rgba(144, 77, 159, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},			
      {
				label: '2022-24',
				data: pbccCard_voa2020LocationData['bp20222024'],
				backgroundColor: 'rgba(217, 22, 74, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
      {
				label: 'Unknown',
				data: pbccCard_voa2020LocationData['bpunkw'],
				backgroundColor: 'rgba(135, 136, 138, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			}	
			]
		},
		options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
							y: {
								stacked: true,
								ticks: {
									beginAtZero: true
								}
							},
							x: {
								stacked: true
							}
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    }
	});
  
  
}


pbccCard_makeChartPopulation = function(){
  
  // Destroy old chart
	if(pbccCard_populationChart){
		pbccCard_populationChart.destroy();
	}

  // Create an object to store data for each category
  var component = [
		    // Label, field (matches columns in the population bin dataset), background colour, border colour
				['0-4'  , 'a04'  , 'rgb(255, 0, 0)', 'rgb(0,0,0)'],
				['5-9'  , 'a59' , 'rgb(255, 64, 0)'   , 'rgb(0,0,0)'],
				['10-14', 'a1014' , 'rgb(255, 128, 0)'     , 'rgb(0,0,0)'],
				['15-19', 'a1519' , 'rgb(255, 192, 0)'    , 'rgb(0,0,0)'],
				['20-24', 'a2024' , 'rgb(255, 255, 0)'  , 'rgb(0,0,0)'],
				['25-29', 'a2529' , 'rgb(192, 255, 0)', 'rgb(0,0,0)'],
				['30-34', 'a3034' , 'rgb(128, 255, 0)', 'rgb(0,0,0)'],
				['35-39', 'a3539' , 'rgb(64, 255, 0)'   , 'rgb(0,0,0)'],
				['40-44', 'a4044' , 'rgb(0, 255, 0)'  , 'rgb(0,0,0)'],
				['45-49', 'a4549' , 'rgb(0, 255, 64)', 'rgb(0,0,0)'],
				['50-54', 'a5054' , 'rgb(0, 255, 128)' , 'rgb(0,0,0)'],
				['55-59', 'a5559' , 'rgb(0, 255, 192)'  , 'rgb(0,0,0)'],
				['60-64', 'a6064' , 'rgb(0, 255, 255)'  , 'rgb(0,0,0)'],
				['65-69', 'a6569' , 'rgb(0, 192, 255)'     , 'rgb(0,0,0)'],
				['70-74', 'a7074' , 'rgb(0, 128, 255)'    , 'rgb(0,0,0)'],
				['75-79', 'a7579' , 'rgb(0, 64, 255)'     , 'rgb(0,0,0)'],
				['80-84', 'a8084' , 'rgb(0, 0, 255)'     , 'rgb(0,0,0)'],
				['85+'  , '85+'  , 'rgb(128, 0, 255)'    , 'rgb(0,0,0)'],
				['Households'  , 'households_est'  , 'rgb(0, 0, 0)'    , 'rgb(0,0,0)'],
				['Dwellings'  , 'all_properties'  , 'rgb(255, 0, 0)'    , 'rgb(255,0,0)']
		  ]
  
  
  // Year labels come from the record itself, never a hard-coded list. The
  // population series runs 2010-2024 in England and Wales but only 2010-2022 in
  // Scotland, and Chart.js pairs data to labels by index: too few labels silently
  // drop the newest years, too many invent years Scotland has no data for.
  var years = (pbccCard_populationLocationData['year'] || []).map(String);
  // Assemble the datasets to be shown
  
	const data = {datasets: []};
	

	component.forEach(comp => {
		data.datasets.push({
			label: comp[0],
			data: pbccCard_populationLocationData[comp[1]],
			backgroundColor: comp[2],
			borderColor: comp[3],
			borderWidth: 1,
			order: 3,
			stack: 'barStack'
		});
	});
  
  // Update type property for the last two datasets
  data.datasets[18].type = 'line';
  data.datasets[19].type = 'line';
  data.datasets[18].borderWidth  = 4;
  data.datasets[19].borderWidth  = 4;
  
  data.datasets[18].order  = 1;
  data.datasets[19].order  = 2;
  data.datasets[18].stack  = undefined;
  data.datasets[19].stack  = undefined;

  
  //console.log(data);
  
  data.labels = years;

  var populationctx = document.getElementById('population-chart').getContext('2d');
	pbccCard_populationChart = new Chart(populationctx, {
    type: 'bar',
					data: data,
					options: {
						scales: {
							y: {
								//stacked: true,
								title: {
									display: true,
									text: 'population'
								},
								ticks: {
									beginAtZero: true,
								}
							},
							x: {
								stacked: true
							},
						},
						plugins: {
                legend: {
                    position: 'right',
                    reverse: true,
                    labels: {
                      font: {
                          size: 8 // Adjust this value to make the text smaller
                      }
                    }
                }
            },
						responsive: true,
						maintainAspectRatio: false
					}
  });
	
  
}

/*
pbccCard_makeChartPLEF = function(){
  
  // overview Chart
  // Destroy old chart
	if(pbccCard_plefIgnoreChart){
		pbccCard_plefIgnoreChart.destroy();
	}
	
	if(pbccCard_plefShiftChart){
		pbccCard_plefShiftChart.destroy();
	}
	
	if(pbccCard_plefSteerChart){
		pbccCard_plefSteerChart.destroy();
	}
	
	if(pbccCard_plefTransformChart){
		pbccCard_plefTransformChart.destroy();
	}
  
  //console.log(chartDefinition.component[0]);
  //console.log(chartDefinition.years[0]);
  
  //const plefdata = Object.keys(pbccCard_locationData).find(function(q){return /P/gi.test(q)});
  
  
  const dataIgnore = {
  labels: ["2020","2030","2040","2050"],
  datasets: [
    // Ignore - Grandfather
    {
      label: 'Residential',
      data: [pbccCard_locationData.Pr2020, pbccCard_locationData.Prgi2030, pbccCard_locationData.Prgi2040, pbccCard_locationData.Prgi2050],
      backgroundColor: '#6b4c89',
      stack: 'Stack 0',
    },
    {
      label: 'Transport',
      data: [pbccCard_locationData.Pt2020, pbccCard_locationData.Ptgi2030, pbccCard_locationData.Ptgi2040, pbccCard_locationData.Ptgi2050],
      backgroundColor: '#497bbe',
      stack: 'Stack 0',
    },
    {
      label: 'Agriculture',
      data: [pbccCard_locationData.Pa2020, pbccCard_locationData.Pagi2030, pbccCard_locationData.Pagi2040, pbccCard_locationData.Pagi2050],
      backgroundColor: '#39b6ad',
      stack: 'Stack 0',
    },
    {
      label: 'Industry',
      data: [pbccCard_locationData.Pi2020, pbccCard_locationData.Pigi2030, pbccCard_locationData.Pigi2040, pbccCard_locationData.Pigi2050],
      backgroundColor: '#4fbfd8',
      stack: 'Stack 0',
    },
    {
      label: 'Non-domestic',
      data: [pbccCard_locationData.Pn2020, pbccCard_locationData.Pngi2030, pbccCard_locationData.Pngi2040, pbccCard_locationData.Pngi2050],
      backgroundColor: '#aa3871',
      stack: 'Stack 0',
    },
    // Ignore - Equity
    {
      //label: 'Residential',
      data: [pbccCard_locationData.Pr2020, pbccCard_locationData.Prei2030, pbccCard_locationData.Prei2040, pbccCard_locationData.Prei2050],
      backgroundColor: '#6b4c89',
      stack: 'Stack 1',
    },
    {
      //label: 'Transport',
      data: [pbccCard_locationData.Pt2020, pbccCard_locationData.Ptei2030, pbccCard_locationData.Ptei2040, pbccCard_locationData.Ptei2050],
      backgroundColor: '#497bbe',
      stack: 'Stack 1',
    },
    {
      //label: 'Agriculture',
      data: [pbccCard_locationData.Pa2020, pbccCard_locationData.Paei2030, pbccCard_locationData.Paei2040, pbccCard_locationData.Paei2050],
      backgroundColor: '#39b6ad',
      stack: 'Stack 1',
    },
    {
      //label: 'Industry',
      data: [pbccCard_locationData.Pi2020, pbccCard_locationData.Piei2030, pbccCard_locationData.Piei2040, pbccCard_locationData.Piei2050],
      backgroundColor: '#4fbfd8',
      stack: 'Stack 1',
    },
    {
      //label: 'Non-domestic',
      data: [pbccCard_locationData.Pn2020, pbccCard_locationData.Pnei2030, pbccCard_locationData.Pnei2040, pbccCard_locationData.Pnei2050],
      backgroundColor: '#aa3871',
      stack: 'Stack 1',
    },
    
  ]
};
  
  
  const dataSteer = {
  labels: ["2020","2030","2040","2050"],
  datasets: [
    // Steer - Grandfather
    {
      label: 'Residential',
      data: [pbccCard_locationData.Pr2020, pbccCard_locationData.Prgs2030, pbccCard_locationData.Prgs2040, pbccCard_locationData.Prgs2050],
      backgroundColor: '#6b4c89',
      stack: 'Stack 0',
    },
    {
      label: 'Transport',
      data: [pbccCard_locationData.Pt2020, pbccCard_locationData.Ptgs2030, pbccCard_locationData.Ptgs2040, pbccCard_locationData.Ptgs2050],
      backgroundColor: '#497bbe',
      stack: 'Stack 0',
    },
    {
      label: 'Agriculture',
      data: [pbccCard_locationData.Pa2020, pbccCard_locationData.Pags2030, pbccCard_locationData.Pags2040, pbccCard_locationData.Pags2050],
      backgroundColor: '#39b6ad',
      stack: 'Stack 0',
    },
    {
      label: 'Industry',
      data: [pbccCard_locationData.Pi2020, pbccCard_locationData.Pigs2030, pbccCard_locationData.Pigs2040, pbccCard_locationData.Pigs2050],
      backgroundColor: '#4fbfd8',
      stack: 'Stack 0',
    },
    {
      label: 'Non-domestic',
      data: [pbccCard_locationData.Pn2020, pbccCard_locationData.Pngi2030, pbccCard_locationData.Pngs2040, pbccCard_locationData.Pngs2050],
      backgroundColor: '#aa3871',
      stack: 'Stack 0',
    },
    // Steer - Equity
    {
      //label: 'Residential',
      data: [pbccCard_locationData.Pr2020, pbccCard_locationData.Pres2030, pbccCard_locationData.Pres2040, pbccCard_locationData.Pres2050],
      backgroundColor: '#6b4c89',
      stack: 'Stack 1',
    },
    {
      //label: 'Transport',
      data: [pbccCard_locationData.Pt2020, pbccCard_locationData.Ptes2030, pbccCard_locationData.Ptes2040, pbccCard_locationData.Ptes2050],
      backgroundColor: '#497bbe',
      stack: 'Stack 1',
    },
    {
      //label: 'Agriculture',
      data: [pbccCard_locationData.Pa2020, pbccCard_locationData.Paes2030, pbccCard_locationData.Paes2040, pbccCard_locationData.Paes2050],
      backgroundColor: '#39b6ad',
      stack: 'Stack 1',
    },
    {
      //label: 'Industry',
      data: [pbccCard_locationData.Pi2020, pbccCard_locationData.Pies2030, pbccCard_locationData.Pies2040, pbccCard_locationData.Pies2050],
      backgroundColor: '#4fbfd8',
      stack: 'Stack 1',
    },
    {
      //label: 'Non-domestic',
      data: [pbccCard_locationData.Pn2020, pbccCard_locationData.Pnes2030, pbccCard_locationData.Pnes2040, pbccCard_locationData.Pnes2050],
      backgroundColor: '#aa3871',
      stack: 'Stack 1',
    },
    
  ]
};

  const dataShift = {
  labels: ["2020","2030","2040","2050"],
  datasets: [
    // Shift - Grandfather
    {
      label: 'Residential',
      data: [pbccCard_locationData.Pr2020, pbccCard_locationData.BPrgs2030, pbccCard_locationData.BPrgs2040, pbccCard_locationData.BPrgs2050],
      backgroundColor: '#6b4c89',
      stack: 'Stack 0',
    },
    {
      label: 'Transport',
      data: [pbccCard_locationData.Pt2020, pbccCard_locationData.BPtgs2030, pbccCard_locationData.BPtgs2040, pbccCard_locationData.BPtgs2050],
      backgroundColor: '#497bbe',
      stack: 'Stack 0',
    },
    {
      label: 'Agriculture',
      data: [pbccCard_locationData.Pa2020, pbccCard_locationData.BPags2030, pbccCard_locationData.BPags2040, pbccCard_locationData.BPags2050],
      backgroundColor: '#39b6ad',
      stack: 'Stack 0',
    },
    {
      label: 'Industry',
      data: [pbccCard_locationData.Ps2020, pbccCard_locationData.BPigs2030, pbccCard_locationData.BPigs2040, pbccCard_locationData.BPigs2050],
      backgroundColor: '#4fbfd8',
      stack: 'Stack 0',
    },
    {
      label: 'Non-domestic',
      data: [pbccCard_locationData.Pn2020, pbccCard_locationData.BPngs2030, pbccCard_locationData.BPngs2040, pbccCard_locationData.BPngs2050],
      backgroundColor: '#aa3871',
      stack: 'Stack 0',
    },
    // Shift - Equity
    {
      //label: 'Residential',
      data: [pbccCard_locationData.Pr2020, pbccCard_locationData.BPres2030, pbccCard_locationData.BPres2040, pbccCard_locationData.BPres2050],
      backgroundColor: '#6b4c89',
      stack: 'Stack 1',
    },
    {
      //label: 'Transport',
      data: [pbccCard_locationData.Pt2020, pbccCard_locationData.BPtes2030, pbccCard_locationData.BPtes2040, pbccCard_locationData.BPtes2050],
      backgroundColor: '#497bbe',
      stack: 'Stack 1',
    },
    {
      //label: 'Agriculture',
      data: [pbccCard_locationData.Pa2020, pbccCard_locationData.BPaes2030, pbccCard_locationData.BPaes2040, pbccCard_locationData.BPaes2050],
      backgroundColor: '#39b6ad',
      stack: 'Stack 1',
    },
    {
      //label: 'Industry',
      data: [pbccCard_locationData.Ps2020, pbccCard_locationData.BPies2030, pbccCard_locationData.BPies2040, pbccCard_locationData.BPies2050],
      backgroundColor: '#4fbfd8',
      stack: 'Stack 1',
    },
    {
      //label: 'Non-domestic',
      data: [pbccCard_locationData.Pn2020, pbccCard_locationData.Pnes2030, pbccCard_locationData.Pnes2040, pbccCard_locationData.Pnes2050],
      backgroundColor: '#aa3871',
      stack: 'Stack 1',
    },
    
  ]
};

  const dataTransform = {
  labels: ["2020","2030","2040","2050"],
  datasets: [
    // Transform - Grandfather
    {
      label: 'Residential',
      data: [pbccCard_locationData.Pr2020, pbccCard_locationData.Prgt2030, pbccCard_locationData.Prgt2040, pbccCard_locationData.Prgt2050],
      backgroundColor: '#6b4c89',
      stack: 'Stack 0',
    },
    {
      label: 'Transport',
      data: [pbccCard_locationData.Pt2020, pbccCard_locationData.Ptgt2030, pbccCard_locationData.Ptgt2040, pbccCard_locationData.Ptgt2050],
      backgroundColor: '#497bbe',
      stack: 'Stack 0',
    },
    {
      label: 'Agriculture',
      data: [pbccCard_locationData.Pa2020, pbccCard_locationData.Pagt2030, pbccCard_locationData.Pagt2040, pbccCard_locationData.Pagt2050],
      backgroundColor: '#39b6ad',
      stack: 'Stack 0',
    },
    {
      label: 'Industry',
      data: [pbccCard_locationData.Pt2020, pbccCard_locationData.Pigt2030, pbccCard_locationData.Pigt2040, pbccCard_locationData.Pigt2050],
      backgroundColor: '#4fbfd8',
      stack: 'Stack 0',
    },
    {
      label: 'Non-domestic',
      data: [pbccCard_locationData.Pn2020, pbccCard_locationData.Pngt2030, pbccCard_locationData.Pngt2040, pbccCard_locationData.Pngt2050],
      backgroundColor: '#aa3871',
      stack: 'Stack 0',
    },
    // Transform - Equity
    {
      //label: 'Residential',
      data: [pbccCard_locationData.Pr2020, pbccCard_locationData.Pret2030, pbccCard_locationData.Pret2040, pbccCard_locationData.Pret2050],
      backgroundColor: '#6b4c89',
      stack: 'Stack 1',
    },
    {
      //label: 'Transport',
      data: [pbccCard_locationData.Pt2020, pbccCard_locationData.Ptet2030, pbccCard_locationData.Ptet2040, pbccCard_locationData.Ptet2050],
      backgroundColor: '#497bbe',
      stack: 'Stack 1',
    },
    {
      //label: 'Agriculture',
      data: [pbccCard_locationData.Pa2020, pbccCard_locationData.Paet2030, pbccCard_locationData.Paet2040, pbccCard_locationData.Paet2050],
      backgroundColor: '#39b6ad',
      stack: 'Stack 1',
    },
    {
      //label: 'Industry',
      data: [pbccCard_locationData.Pt2020, pbccCard_locationData.Piet2030, pbccCard_locationData.Piet2040, pbccCard_locationData.Piet2050],
      backgroundColor: '#4fbfd8',
      stack: 'Stack 1',
    },
    {
     //label: 'Non-domestic',
      data: [pbccCard_locationData.Pn2020, pbccCard_locationData.Pnet2030, pbccCard_locationData.Pnet2040, pbccCard_locationData.Pnet2050],
      backgroundColor: '#aa3871',
      stack: 'Stack 1',
    },
    
  ]
};
 
  
}

*/

// Click on modal tab open by default


// Function to switch chart description tabs
switchChartTab = function (evt, tabName) {
  // Find the parent chart-description-tabs container
  var tabsContainer = evt.currentTarget.closest('.chart-description-tabs');
  
  // Get all tab content divs within this container and hide them
  var tabContents = tabsContainer.querySelectorAll('.chart-description-tab-content');
  tabContents.forEach(function(content) {
    content.classList.remove('active');
    content.style.display = 'none';
  });
  
  // Get all tab buttons within this container and remove the "active" class
  var tabButtons = tabsContainer.querySelectorAll('.chart-tab-btn');
  tabButtons.forEach(function(button) {
    button.classList.remove('active');
  });
  
  // Show the current tab and add "active" class to button
  var selectedContent = document.getElementById(tabName);
  if (selectedContent) {
    selectedContent.classList.add('active');
    selectedContent.style.display = 'block';
    evt.currentTarget.classList.add('active');
  }
}

// Function to switch Pen Portrait description
function pbccCard_switchPenPortSub(SOAC11NM) {
  
  var pp = "No Desc";
  switch(SOAC11NM) {
  case "Achieving neighbourhoods":
    pp = `<p>This group is the least densely populated of the four groups comprising the ethnically-diverse professionals supergroup and with a lower median age (36 years) than for the parent supergroup (38 years).</p>

<p>Residents are slightly more likely to be born in the UK or Ireland and to live in a terraced property than the parent supergroup and households are more likely to own or have shared ownership of their property (74.4% of all households). Workers are more likely than the parent supergroup to use private transport to get to work and to work in the public administration or defence; compulsory social security industries. </p>`;
    break;
  case "Affluent communities":
    pp = `<p>This group has the joint-highest median age (47 years) of all the groups and a higher proportion of persons living in communal establishments than with the parent supergroup, and aged 90 years or over.</p>

<p>There is a higher proportion of all non-White ethnic groups compared with the parent supergroup. Households are more likely to live in a detached property (over half of all households), more likely to live in a flat and marginally more likely to own or have shared ownership of a property. Workers are more likely to use public transport to get to work (though only 9.0% do so) and to work in the information and communication or professional-related industries.</p>`;
    break;
  case "Ageing rural neighbourhoods":
    pp = `<p>Residents within this group cluster have the highest joint-median age (47 years) of all the 24 groups and compared with the parent supergroup, there is a noticeably higher proportion of residents living in a communal establishment and an observably higher proportion aged 90 years and over. A higher proportion of residents have mixed ethnicity or are from multiple ethnic groups.</p>

<p>Households are more likely to live in a terraced property or a flat (though for these two housing types combined, less than one-quarter of all households do so) and to privately rent than for the parent supergroup, though most households live in a detached property (55.2%). Employed residents are also marginally more likely to use public transport, cycle or walk to work and to work in the accommodation or food service activities industries than for the parent supergroup. </p>`;
    break;
  case "Ageing suburbanites":
    pp = `<p>This group has the joint highest median age (47 years) of all the groups.Compared with the parent supergroup, households are more likely to live in a semi-detached property (comprising a half of all households) and marginally more likely to own or have shared ownership of a property – this covers 89.9% of all households, the highest percentage for any of the 24 groups. Workers are marginally more likely to use private transport to get to work (and was the stated main method of transport for over three-quarters of all workers aged 16 to 74 years) and to work in the manufacturing industry.</p>`;
    break;
  case "Ageing urban communities":
    pp = `<p>This group has the highest median age (46) of the five groups comprising the industrious communities supergroup (median age 42 years).</p>

<p>Compared with the supergroup, there is a noticeably higher proportion of residents who live in a communal establishment (nearly 5% of all residents) and a noticeably higher proportion of residents aged 90 years and over. Amongst households there is a higher proportion who live in a detached property and a higher proportion who live in a flat.</p>

<p>Educational qualifications are generally higher than the supergroup and for those in employment a higher proportion walk or cycle to work. There is also a higher prevalence of workers in the information and communication or professional-related activities. </p>`;
    break;
  case "Asian traits":
    pp = `<p>This group has a higher median age (40 years) than for the parent supergroup (38 years). There is also an observably higher proportion of residents from the Indian and Pakistani ethnic groups and a higher proportion of residents whose main language is not English and cannot speak English well or at all. Households are more likely to live in a detached property (25.9% of all households) or a semi-detached property (47.6% of households) and to have two or more cars (40.7% of households).</p>

<p>Workers are more likely to use public transport to travel to work and to work in the education sector than the parent supergroup.</p>`;
    break;
  case "Aspiring urban households":
    pp = `<p>This group has the lowest median age (39 years) of the five groups comprising the industrious communities supergroup (median age 42 years) and the highest population density (17.1 persons per hectare).</p>

<p>The proportion of persons of non-White ethnic group is generally higher than for the supergroup, whilst households are more likely to live in a terraced property (36.7% of all households) and to be privately renting.</p>

<p>Unemployment rates are below that for the supergroup, whilst for those in employment there was a marginally higher proportion of full-time workers and a higher proportion working in financial-related industries.</p>`;
    break;
  case "Challenged white communities":
    pp = `<p>Of the four groups within the supergroup, this group has the lowest population density (26.3 persons per hectare). Residents belonging to this group are more likely to have been born in the UK or Ireland than for the parent supergroup. Households are also more likely to live in a semi-detached property (36.8% of all households) or terraced property (41.5% of all households).</p>

<p>Households are also marginally more likely to own or have shared ownership of a property and to live in socially-rented accommodation (41.4% of households).</p>

<p>For residents in employment, they are marginally more likely than the parent supergroup to use private transport to get to work and more likely to work in the energy, water or air conditioning supply industries than the parent supergroup. </p>`;
    break;
  case "Comfortable neighbourhoods":
    pp = `<p>The characteristics of this group are very similar to the parent supergroup. There is though a higher proportion of households who live in a flat (covering one-fifth of all households) and who live in socially-rented accommodation (covering one-fifth of all households). Educational qualifications are higher than for the supergroup and workers are more likely to use public transport to get to work and to work in financial-related industries. </p>`;
    break;
  case "Comfortable suburbia":
    pp = `<p>This group has the lowest median age (40 years) of the three groups within the supergroup and a slightly higher proportion of persons in all the non-White ethnic groups than for the parent supergroup. Households are more likely to live in a terraced property (though only 16.9% of households do so) and to either privately rent or live in social rented accommodation, though the large majority of households either own outright or have shared ownership of their property. Workers are more likely to work in the transport or storage industries.</p>`;
    break;
  case "Constrained renters":
    pp = `<p>Compared with the parent supergroup, residents are more likely to be living in a communal establishment and more likely to be in privately-rented accommodation (over a quarter of all households) and to be living in a terraced property (47.2% of households, the highest percentage for any of the 24 groups).</p>

<p>Workers are more likely to work full-time and to work in the agriculture, forestry and fishing industries. </p>`;
    break;
  case "Cosmopolitan student neighbourhoods":
    pp = `<p>The group and parent group are the same in terms of SOA representation. The description for the cosmopolitan student neighbourhoods supergroup therefore also applies for this group, which bears the same name as the parent supergroup.</p>`;
    break;
  case "Endeavouring social renters":
    pp = `<p>The characteristics of this group are also very similar to the parent supergroup. There is though a higher proportion of households who live in a semi-detached property (covering nearly a half of all households) and who live in socially-rented accommodation (covering over a fifth of all households).</p>

<p>Unemployment is higher than for the supergroup and compared with the parent supergroup, workers are more likely to use public transport to get to work (though over three-quarters of workers in fact use private transport to get to work) and to work in the energy, water or air conditioning supply industries. </p>`;
    break;
  case "Hampered neighbourhoods":
    pp = `<p>Of the four groups within the parent supergroup, this group has the lowest median age (35 years), with higher proportions of residents in the 0 to 4 years and 5 to 14 years age groups. A noticeably higher proportion of residents have mixed ethnicity or are from multiple ethnic groups. All non-White ethnic groups have a higher representation than for the supergroup.</p>

<p>Compared with the parent supergroup, households are more likely to live in a semi-detached property (over one-third of all households) – though households who live in a terraced property are slightly more prevalent and households are also more likely to be socially renting (42.7% of households). Workers are more likely to use public transport to get to work and to work in the education sector.</p>`;
    break;
  case "Hard-pressed flat dwellers":
    pp = `<p>Of the groups within the parent supergroup, this group has the highest median age (39 years), the same as the UK median age and has the highest population density (36.8 persons per hectare) and lowest proportion of land area. As implied by the name for this group, there is a noticeably higher proportion of households who live in a flat (70.8% of all households) than for the parent supergroup, and social renting is also more prevalent (a half of all households socially-rented – the highest for any of the 24 groups).</p>

<p>Unemployment is also higher than for the parent supergroup (at 8.6% of all residents aged 16 to 74 years, this was the highest level out of all the 24 groups) and workers are more likely to work in financial-related industries.</p>`;
    break;
  case "Highly qualified professionals":
    pp = `<p>Compared with the supergroup, there is an observably higher proportion of persons aged 90 years and over. Residents are marginally more likely to live in a detached property, but also markedly more likely to live in a flat (41.2% of households) than for the supergroup. Households are more likely to privately rent their accommodation than the parent supergroup. Of the four groups within the ethnically diverse professionals supergroup, adults within this group have the highest qualification levels.</p>

<p>Residents in employment are more likely to work within the information-related industries (16.9% of all workers aged 16 to 74 years).</p>`;
    break;
  case "Households in terraces and flats":
    pp = `<p>This group has the highest population density (30.3 persons per hectare) of all the four groups within the parent supergroup.</p>

<p>Compared with the parent supergroup, the groups have a higher proportion of persons whose ethnic group is recorded as Black, African, Caribbean or Black British. Residents are also much more likely to live in a terraced property (over one-third of all households) and marginally more likely to live in a flat (as do a quarter of all households) and to live in socially-rented accommodation.</p>

<p>Unemployment is higher for this group than for the other three groups within the parent supergroup, whilst those in employment are more likely to work in the transport or storage industries.</p>`;
    break;
  case "Inner city cosmopolitan":
    pp = `<p>The group and parent group are the same in terms of SOA representation. The description for the inner city cosmopolitan supergroup therefore also applies for this group, which bears the same name as the parent supergroup.</p>`;
    break;
  case "Primary sector workers":
    pp = `<p>This group has the lowest population density of the five groups within the supergroup. There is a higher prevalence of households living in a detached property (a quarter of all households) and living in a flat than with the parent supergroup. Households are also more likely to live in socially-rented accommodation.</p>

<p>Workers are more likely to walk or cycle to work and to work in the agriculture, forestry and fishing industries, and the accommodation or food service activities industries.</p>`;
    break;
  case "Prospering countryside life":
    pp = `<p>Compared with the parent supergroup, a higher proportion of residents have mixed ethnicity or are from multiple ethnic groups. Residents are also more likely to have a higher level of qualifications. Nearly four-fifths of households own or have shared ownership of their property. Car ownership is also slightly higher than for the parent supergroup – with 57.7% of households having access to two or more cars, which is the highest percentage for any of the 24 groups.</p>

<p>Workers are more likely to use public transport to travel to work than for the parent supergroup and are also more likely to be employed in the information and communication or professional, scientific and technical activities industries and financial-related industries.</p>`;
    break;
  case "Remoter communities":
    pp = `<p>The population of this group live in remoter parts of the UK, though covering half of the total UK land area. This group has the lowest population density of any of the 24 groups (0.2 persons per hectare). Residents are more likely than the parent supergroup to live in a detached property (69.4% of all households do so – the highest percentage for any group). Residents are also marginally more likely to be privately renting, though households owning their own property or have shared ownership is far more prevalent – 77.5% of households.</p>

<p>An observably higher proportion of workers are employed in the agriculture, forestry and fishing industries than with the parent supergroup (the highest for any group at 8.9% of all employed residents aged 16 to 74 years), there is also a higher prevalence of working in the mining, quarrying or construction industries (the highest for any group at 10.2% of all employed residents aged 16 to 74 years). </p>`;
    break;
  case "Rural traits":
    pp = `<p>Of the four groups within the parent supergroup countryside living, the rural traits group has the lowest median age (45 years) though this is above the UK median age (39 years).</p>

<p>Residents are more likely to live in a semi-detached, terraced property, or flat than the parent supergroup and to live in socially-rented accommodation, though owned or shared ownership of a property is also relatively high (74.6% of all households).</p>

<p>Workers are also marginally more likely to walk, cycle or use an alternative method to get to work and to be employed in the energy, water or air conditioning supply industries than for the parent supergroup.</p>`;
    break;
  case "Urban cultural mix":
    pp = `<p>This group has a higher proportion of persons who are White than with the parent group and higher proportion of persons born in the UK or Ireland. Households are more likely to live in a flat (over one-third of all households) and to live in socially-rented accommodation (one-third of all households).</p>

<p>Workers are more likely to work in the energy, water or air conditioning supply industries and human health and social work activities industries.</p>`;
    break;
  case "Young ethnic communities":
    pp = `<p>The population of this group have the second-lowest median age (30 years) of all the 24 groups. There is a higher proportion of persons for most of the non-White ethnic groups than with the parent supergroup. Households are more likely to live in a detached property (though just 8.1% of households do so) and to live in privately-rented accommodation (over a quarter of all households).</p>

<p>Qualifications levels are generally higher than with the parent supergroup, whilst workers are more likely to work part-time (one-third do so) and to work in the accommodation or food service activities industries. </p>`;
    break;
  default:
    pp = `<p>No Description</p>`;
  } 
  
  document.getElementById("penportsub").innerHTML = pp;
}


function pbccCard_switchPenPortSup(SOAC11NM) {
  
  var pp1 = `<p>The population of this supergroup typically live in cities and major towns across the UK containing universities, and because of this, there is a large student population, characterised by a relatively large proportion of households with full-time students (8.5%).</p>

<p>Residents are much more likely to live in communal establishments – such as university halls of residences and flats. Residents are also more likely than nationally to live in private or social rented accommodation (applies to 62.0% of all households). There is a much younger age structure than nationally, with a median age of 26 years – the lowest of any of the eight supergroups. The supergroup has an above average ethnic mix and below average proportion of residents UK and Irish born.</p>

<p>Qualification levels are higher than nationally, and for those in employment, a higher proportion use public transport or walk and cycle to get to work (over half of all employed residents).</p>

<p>Employed residents aged 16 to 74 years are more likely to work in the accommodation or food service activities industries (11.0% of employed residents, the highest percentage for any supergroup) and to work part-time (31.5% of employed residents, the highest percentage for any supergroup). </p>`;
  
  
  var pp2 = `<p>The population of this supergroup live in rural areas across the whole of the UK, the SOAs covered by this supergroup cover 87% of the total UK land area.</p>

<p>Residents are much more likely to live in detached housing (57.1% of households – the highest percentage for any supergroup) and to own their own property. The supergroup has a below average ethnic mix and above average proportion of UK and Irish born residents. Residents are far more likely to be represented in older age groups than nationally. The median age of 46 years is the highest of all the supergroups. Rates of divorce or separation are lower than nationally and the proportion of persons aged 16 years and over with higher qualifications is above the national average.</p>

<p>Unemployment rates are below the national average, whilst employed residents are noticeably more likely to work in the agriculture, forestry and fishing industries. Households are more likely to own two or more cars or vans and to use private transport to get to work. </p>`;

var pbccCard_pp3 = `<p>The population of this supergroup typically live largely within cities, fringes of cities or in other urban areas across the UK.</p>

<p>Residents are more likely to live in a flat (a quarter of all households do so). The supergroup has an above average ethnic mix and slightly below average proportion of UK and Irish born residents. Residents are more likely to be represented in the younger age groups than nationally. Rates of divorce or separation are marginally lower than nationally and the proportion of persons aged 16 years and over with higher qualifications is above the national average.</p>

<p>Unemployment rates are below the national average, and for employed residents, they are more likely to work in the information and communication industries and financial-related industries than nationally, to work full-time, and are more likely to travel to work using public transport, though households owning two or more cars are also more prevalent than nationally.</p>`;

var pbccCard_pp4 = `<p>The population of this supergroup typically live largely in either current or former industrial areas, in cities and larger towns across the UK.</p>

<p>Residents are much more likely to live in a terraced property or a flat (over two-thirds of all households) and to live in social rented accommodation. The supergroup has a below average ethnic mix and an above average of UK and Irish born residents. Residents are more likely to be represented in younger age groups than nationally. Rates of divorce or separation are higher than nationally, and the proportion of persons aged 16 years and over with higher qualifications is below the national average.</p>

<p>Unemployment rates are observably higher than the national average – at 7.5% the highest for any supergroup. Employed residents are more likely to work in the transport or storage industries and administrative or support services industries and marginally more likely to work part-time than nationally and to travel to work using public transport.</p>`;

var pbccCard_pp5 = `<p>The population of this supergroup typically live largely in industrial areas across the UK and is the largest supergroup in terms of resident population – comprising one-fifth of the total UK population.</p>

<p>Residents are more likely to live in detached, semi-detached or terraced housing (89.2% of all households), and to live in social rented accommodation. The supergroup has a below-average ethnic mix and above-average number of UK and Irish born. Residents are more likely to be represented in the older age groups and the proportion of residents aged over 16 years with higher qualifications is below the national average.</p>

<p>Employed residents are more likely to work in the manufacturing industry and mining, quarrying or construction industries and are more likely to travel to work using private transport than nationally. </p>`;

var pbccCard_pp6 = `<p>The population of this supergroup is very localised in its distribution, concentrated in Inner London, but also parts of Outer London, Birmingham, Bristol, Edinburgh, Glasgow, Manchester and Reading, plus small numbers of SOAs in other cities and major towns.</p>

<p>Areas covered by this supergroup are characterised as having a very high population density (average 93.9 persons per hectare), but covering just 0.2% of the UK land area. Residents are far more likely to live in a flat than nationally (79.2% of all households) and to live in private or socially-rented accommodation. The supergroup has a noticeably high ethnic mix, and below average number of UK and Irish born residents. Residents are far more likely to be represented in the 25 to 44 years age group than nationally and the proportion of persons aged 16 years and over with higher qualifications is above the national average.</p>

<p>Unemployment rates are higher than the national average and for employed residents, they are more likely to work in the information and communication industries (over one-fifth of all workers) and financial-related industries than nationally. Workers are also far more likely to work full-time and to use public transport to travel to work (57.8% of all workers – by far the highest for any supergroup).  </p>`;

var pbccCard_pp7 = `<p>The population of this supergroup are represented in the larger urban areas in the UK, except for Northern Ireland. The distribution of SOAs for this supergroup is noticeably localised.</p>

<p>Residents are more likely to live in terraced housing or flats (70.7% of all households) and to rent either privately or through social housing (half of all households). The supergroup has a noticeably high ethnic mix and below-average number of UK and Irish born.</p>

<p>Residents are far more likely to be represented in the 0 to 4 years and 5 to 14 years age group than nationally. Qualification levels are similar to national levels.</p>

<p>Unemployment rates are higher than the national average and employed residents are more likely to work in the transport or storage industries, to work part-time and to use public transport to travel to work (just under one-third of all workers).  </p>`;

var pbccCard_pp8 = `<p>The population of this supergroup typically live largely in areas within or close proximity to larger urban areas across the UK.</p>

<p>Residents are much more likely to live in a detached property (46.5% of all households) and to own their own property (88.7% of all households). The supergroup has a below-average ethnic mix and a higher proportion of UK and Irish born residents than nationally. Residents are far more likely to be represented in older age groups than nationally and there is a relatively high median age of 45 years (compared with 39 years nationally). The proportion of persons aged 16 years and over with higher qualifications is above the national average, as is car ownership (nearly half of all households have two or more cars).</p>

<p>Unemployment rates are noticeably below the national average (at 2.5% the lowest for any supergroup) and for employed residents, they are more likely to work in financial-related industries,and to use private transport to travel to work (three-quarters of all workers used private transport – the highest percentage for any supergroup).</p>`;
  
  var pp = "No Desc";
  switch(SOAC11NM) {
  case "Achieving neighbourhoods":
    pp = pbccCard_pp3;
    break;
  case "Affluent communities":
    pp = pbccCard_pp8;
    break;
  case "Ageing rural neighbourhoods":
    pp = pp2;
    break;
  case "Ageing suburbanites":
    pp = pbccCard_pp8;
    break;
  case "Ageing urban communities":
    pp = pbccCard_pp5;
    break;
  case "Asian traits":
    pp = pbccCard_pp3;
    break;
  case "Aspiring urban households":
    pp = pbccCard_pp5;
    break;
  case "Challenged white communities":
    pp = pbccCard_pp4;
    break;
  case "Comfortable neighbourhoods":
    pp = pbccCard_pp5;
    break;
  case "Comfortable suburbia":
    pp = pbccCard_pp8;
    break;
  case "Constrained renters":
    pp = pbccCard_pp4;
    break;
  case "Cosmopolitan student neighbourhoods":
    pp = pp1;
    break;
  case "Endeavouring social renters":
    pp = pbccCard_pp5;
    break;
  case "Hampered neighbourhoods":
    pp = pbccCard_pp4;
    break;
  case "Hard-pressed flat dwellers":
    pp = pbccCard_pp4;
    break;
  case "Highly qualified professionals":
    pp = pbccCard_pp3;
    break;
  case "Households in terraces and flats":
    pp = pbccCard_pp3;
    break;
  case "Inner city cosmopolitan":
    pp = pbccCard_pp6;
    break;
  case "Primary sector workers":
    pp = pbccCard_pp5;
    break;
  case "Prospering countryside life":
    pp = pp2;
    break;
  case "Remoter communities":
    pp = pp2;
    break;
  case "Rural traits":
    pp = pp2;
    break;
  case "Urban cultural mix":
    pp = pbccCard_pp7;
    break;
  case "Young ethnic communities":
    pp = pbccCard_pp7;
    break;
  default:
    pp = `<p>No Description</p>`;
  } 
  
  document.getElementById("penportsup").innerHTML = pp;
}

function pbccCard_lsoaCharacteristicsTable(lsoadata) {
  	document.getElementById("data_SOAC11NM").innerHTML = lsoadata.lsoa_class_name;
  	document.getElementById("data_LAD25CD").innerHTML = lsoadata.LAD25CD;
  	document.getElementById("data_LAD25NM").innerHTML = lsoadata.LAD25NM;
	document.getElementById("data_WD25NM").innerHTML = lsoadata.WD25NM;
	document.getElementById("data_PAR23NM").innerHTML = lsoadata.PAR23NM;
	document.getElementById("data_PCON24NM").innerHTML = lsoadata.PCON24NM;
	document.getElementById("data_supergroup_name").innerHTML = 'Supergroup Description: "' + lsoadata.supergroup_name + '"';
	document.getElementById("data_lsoa_class_name").innerHTML = 'Subgroup Description: "' + lsoadata.lsoa_class_name + '"';
}




// Registration: the report page calls window.reportCards.pbcc.load(locationId)
window.reportCards = window.reportCards || {};
window.reportCards.pbcc = {
  load: function (locationId) { return pbccCard_manageCharts(locationId, 'zones'); },
  defaultOpen: 'pbcc-defaultOpen'
};
