// GENERATED FILE - do not edit by hand.
// Regenerated by scratchpad/make_report_cards.py from retrofit/ui.js + retrofit/index.html.
//
// EXCEPTION, 2026-09-02: the Dwelling Stock tab was added by hand, to this file
// and to retrofit-card.html. The four council tax charts (bands, type, bedrooms,
// build period) had moved out of the PBCC tool into this one, but the cards were
// generated before that, so the PBCC card carries them commented out and this
// card never had them - the charts had silently disappeared from every report
// page. Ported verbatim from retrofit/ui.js (voaSetAvailable, makeChartVOABands,
// makeChartVOAStock) and retrofit/index.html (the "stock" tabcontent block) with
// the generator's usual retrofitCard_ prefixing. Re-running the generator will
// pick all of it up from the tool and overwrite this note.
// Report-card module for the retrofit tool: renders every chart from the tool's
// zones report modal into the retrofit-card.html fragment on a report page.
// Data endpoints can be redirected (e.g. to area-level aggregates) by setting
// window.REPORT_CARD_ENDPOINTS = { '<default path>': <override> } where the
// override is either '<replacement path>' (another pbcc-data folder) or
// { bin: '<dataset>' } (a capBin single-binary dataset, which the page must
// have capBin.register()ed - see reports/la-report.js).

function retrofitCard_fetchJSON(url) {
  // 'bin:<dataset>/<id>.json' pseudo-URLs come from the { bin: ... } override
  // form of REPORT_CARD_ENDPOINTS and are served by capBin range requests.
  if (url.lastIndexOf('bin:', 0) === 0) {
    var rest = url.slice(4);
    var slash = rest.indexOf('/');
    return capBin.fetchRecord(rest.slice(0, slash), rest.slice(slash + 1).replace(/\.json$/, ''));
  }
  return fetch(url).then(function (r) {
    if (!r.ok) { throw new Error('HTTP ' + r.status); }
    return r.json();
  });
}

function retrofitCard_endpoint(path) {
  var override = (window.REPORT_CARD_ENDPOINTS || {})[path];
  if (override && typeof override === 'object' && override.bin) { return 'bin:' + override.bin + '/'; }
  return 'https://pbcc.blob.core.windows.net/pbcc-data/' + (override || path);
}

// Tab switcher scoped to this card's own fragment, so multiple tool cards can
// coexist on one report page without cross-talk.
function retrofitCard_modalTab(evt, tabName) {
  var root = evt.currentTarget.closest('.report-fullcard');
  if (!root) { return; }
  root.querySelectorAll('.tabcontent').forEach(function (el) { el.style.display = 'none'; });
  root.querySelectorAll('.tablinks').forEach(function (el) { el.className = el.className.replace(' active', ''); });
  var target = root.querySelector('#' + tabName);
  if (target) { target.style.display = 'block'; }
  evt.currentTarget.className += ' active';
}

// Local Chart Management
var retrofitCard_emissionsChart;
var retrofitCard_gasChart;
var retrofitCard_electricityChart;
var retrofitCard_metersChart;

var retrofitCard_emissionsLSOAChart;
var retrofitCard_gasLSOAChart;
var retrofitCard_electricityLSOAChart;
var retrofitCard_metersLSOAChart;
var retrofitCard_energybillsLSOAChart;

var retrofitCard_epcratingChart;
var retrofitCard_buildingtypeChart;
var retrofitCard_tenureChart;
var retrofitCard_ageChart;
var retrofitCard_floorChart;
var retrofitCard_floordChart;
var retrofitCard_windowChart;
var retrofitCard_waterChart;
var retrofitCard_waterdChart;
var retrofitCard_glazingChart;
var retrofitCard_wallChart;
var retrofitCard_walldChart;
var retrofitCard_roofChart;
var retrofitCard_roofdChart;
var retrofitCard_mainheatChart;
var retrofitCard_mainheatdescChart;
var retrofitCard_mainfuelChart;
var retrofitCard_mainheatcontrolChart;
var retrofitCard_controldChart;
var retrofitCard_lightChart;
var retrofitCard_solarpvChart;
var retrofitCard_solarthermalChart;

var retrofitCard_pricesChart;
var retrofitCard_transactionsChart;

var retrofitCard_postcodeLocationData = {};
var retrofitCard_lsoaLocationData = {};
var retrofitCard_pricesLocationData = {};
var retrofitCard_lsoaEnergyData = {};
var retrofitCard_voaBandsLocationData = {};
var retrofitCard_voaStockLocationData = {};

var retrofitCard_dwellingsctChart;
var retrofitCard_dwellingstypeChart;
var retrofitCard_dwellingsbedroomsChart;
var retrofitCard_dwellingsageChart;

retrofitCard_manageCharts =  function (locationId, mapLayerId){
  if(mapLayerId == 'zones'){

    const pEPC = retrofitCard_fetchJSON(retrofitCard_endpoint('epc_dom/v4/') + locationId + '.json')
      .then(data => { retrofitCard_lsoaLocationData = data[0]; retrofitCard_makeChartLSOA(); })
      .catch(err => { console.error('EPC failed:', err); });  
    
    const pEnergy = retrofitCard_fetchJSON(retrofitCard_endpoint('lsoa_gas_electric/v2/') + locationId + '.json')
      .then(data => { retrofitCard_lsoaEnergyData = data; retrofitCard_makeChartLSOAEnergy(); })
      .catch(err => { console.error('Energy failed:', err); });  
    
    const pPrices = retrofitCard_fetchJSON(retrofitCard_endpoint('prices/v1/') + locationId + '.json')
      .then(data => { retrofitCard_pricesLocationData = data; retrofitCard_makeChartPrices(); })
      .catch(err => { 
        console.error('Prices failed:', err);
        if(retrofitCard_pricesChart){
          retrofitCard_pricesChart.destroy();
        }
        if(retrofitCard_transactionsChart){
          retrofitCard_transactionsChart.destroy();
        }
      });

    // Dwelling stock from the council tax registers. These charts live in the
    // retrofit tool (retrofit/ui.js, "Dwelling stock charts") but were missing
    // from this card: they were moved into that tool out of the PBCC one, where
    // the card still carries them commented out, and were never carried across.
    //
    // voa_2010 (council tax bands) is GB-wide. voa_2020 (type/bedrooms/age) is
    // England and Wales only, so a Scottish zone legitimately has no record and
    // the fetch rejects; that is the expected outcome rather than a failure, and
    // the charts are replaced by the note already in the card fragment. Area
    // reports have no VOA aggregate at all, so both reject there and both groups
    // are replaced by their notes.
    const pVOABands = retrofitCard_fetchJSON(retrofitCard_endpoint('voa_2010/') + locationId + '.json')
      .then(data => {
        retrofitCard_voaBandsLocationData = data;
        retrofitCard_voaSetAvailable(['dwellingsct'], 'dwellingsct-nodata', true);
        retrofitCard_makeChartVOABands();
      })
      .catch(err => {
        if(retrofitCard_dwellingsctChart){ retrofitCard_dwellingsctChart.destroy(); }
        retrofitCard_voaSetAvailable(['dwellingsct'], 'dwellingsct-nodata', false);
      });

    const pVOAStock = retrofitCard_fetchJSON(retrofitCard_endpoint('voa_2020/') + locationId + '.json')
      .then(data => {
        retrofitCard_voaStockLocationData = data;
        retrofitCard_voaSetAvailable(['dwellingstype','dwellingsbedrooms','dwellingsage'], 'dwellingsstock-nodata', true);
        retrofitCard_makeChartVOAStock();
      })
      .catch(err => {
        if(retrofitCard_dwellingstypeChart){ retrofitCard_dwellingstypeChart.destroy(); }
        if(retrofitCard_dwellingsbedroomsChart){ retrofitCard_dwellingsbedroomsChart.destroy(); }
        if(retrofitCard_dwellingsageChart){ retrofitCard_dwellingsageChart.destroy(); }
        retrofitCard_voaSetAvailable(['dwellingstype','dwellingsbedrooms','dwellingsage'], 'dwellingsstock-nodata', false);
      });

    return Promise.all([pEPC, pPrices, pEnergy, pVOABands, pVOAStock]);
    //return p;
  } else if (mapLayerId == 'postcodes'){
    const p = retrofitCard_fetchJSON(retrofitCard_endpoint('postcode_energy/v2/') + locationId + '.json')
        .then(function (postcodeData) {
            retrofitCard_postcodeLocationData = postcodeData;
            retrofitCard_makeChartPostcode(locationId);
        })
        .catch(function (error) {
            console.warn('Failed to get access data for this location, or to process it correctly. Please try refreshing the page.');
            console.log(error);
        });

    return p;
  } else {
    console.log('Unknown layer for chart management: ' + mapLayerId);
    return Promise.resolve();
  }
}

retrofitCard_makeChartPostcode = function(locationId){
  
  console.log("Make postcode charts");
  // Access Chart
  // Destroy old chart
	if(retrofitCard_emissionsChart){
		retrofitCard_emissionsChart.destroy();
	}
	if(retrofitCard_gasChart){
		retrofitCard_gasChart.destroy();
	}
	if(retrofitCard_electricityChart){
		retrofitCard_electricityChart.destroy();
	}
  if(retrofitCard_metersChart){
		retrofitCard_metersChart.destroy();
	}

  // Set modal title
  const title = locationId + ' postcode summary';
	document.querySelector('#postcodes-chartsmodal .modal-title').innerHTML = title;
  
  // Get Control Settings
  const setting_emissions = document.getElementById("select_emissions").value;
	const setting_gas = document.getElementById("select_gas").value;
  const setting_electricity = document.getElementById("select_electricity").value;
  
  let data_emissions_gas;
  let data_emissions_elec;
  let data_elec_all;
  let data_elec_std;
  let data_elec_eco7;
  let data_gas;
  

  // Get data
  // Not doing emissions for standard and eco7 meters
  if(setting_emissions == "total"){
     data_emissions_gas = retrofitCard_postcodeLocationData['gas_totalkgco2e'];
     data_emissions_elec = retrofitCard_postcodeLocationData['elec_totalkgco2e_all'];
  } else if (setting_emissions == "mean") {
     data_emissions_gas = retrofitCard_postcodeLocationData['gas_meankgco2e'];
     data_emissions_elec = retrofitCard_postcodeLocationData['elec_meankgco2e_all'];
  } else if (setting_emissions == "median") {
     data_emissions_gas = retrofitCard_postcodeLocationData['gas_mediankgco2e'];
     data_emissions_elec = retrofitCard_postcodeLocationData['elec_mediankgco2e_all'];
  }
  
  if(setting_electricity == "total"){
     data_elec_all = retrofitCard_postcodeLocationData['elec_totalkwh_all'];
     data_elec_std = retrofitCard_postcodeLocationData['elec_totalkwh_std'];
     data_elec_eco7 = retrofitCard_postcodeLocationData['elec_totalkwh_eco7'];
  } else if (setting_electricity == "mean") {
     data_elec_all = retrofitCard_postcodeLocationData['elec_meankwh_all'];
     data_elec_std = retrofitCard_postcodeLocationData['elec_meankwh_std'];
     data_elec_eco7 = retrofitCard_postcodeLocationData['elec_meankwh_eco7'];
  } else if (setting_electricity == "median") {
     data_elec_all = retrofitCard_postcodeLocationData['elec_mediankwh_all'];
     data_elec_std = retrofitCard_postcodeLocationData['elec_mediankwh_std'];
     data_elec_eco7 = retrofitCard_postcodeLocationData['elec_mediankwh_eco7'];
  }
  
  if(setting_gas == "total"){
     data_gas = retrofitCard_postcodeLocationData['gas_totalkwh'];
  } else if (setting_gas == "mean") {
     data_gas = retrofitCard_postcodeLocationData['gas_meankwh'];
  } else if (setting_gas == "median") {
     data_gas = retrofitCard_postcodeLocationData['gas_mediankwh'];
  }
  
  
  
  const labels = retrofitCard_postcodeLocationData['year'];
  const dataMeters = {
    labels: labels,
    datasets: [
      {
        label: 'Gas',
        data: retrofitCard_postcodeLocationData['gas_meters'],
        backgroundColor: '#2b8cbe',
        stack: 'Stack 0',
      },
      {
        label: 'Electric (all)',
        data: retrofitCard_postcodeLocationData['elec_meters_all'],
        backgroundColor: '#b30000',
        stack: 'Stack 1',
      },
      {
        label: 'Electric (Standard)',
        data: retrofitCard_postcodeLocationData['elec_meters_std'],
        backgroundColor: '#e34a33',
        stack: 'Stack 2',
      },
      {
        label: 'Electric (Economy 7)',
        data: retrofitCard_postcodeLocationData['elec_meters_eco7'],
        backgroundColor: '#fdcc8a',
        stack: 'Stack 2',
      }
    ]
  };
  
  
  const dataEmissions = {
    labels: labels,
      datasets: [
        {
          label: 'Gas',
          data: data_emissions_gas,
          borderColor: '#2b8cbe',
          backgroundColor: '#2b8cbe',
        },
        {
          label: 'Electricity',
          data: data_emissions_elec,
          borderColor: '#b30000',
          backgroundColor: '#b30000',
        }
      ]
    };
	
	const dataElectricity = {
    labels: labels,
      datasets: [
        {
          label: 'All meters',
          data: data_elec_all,
          borderColor: '#b30000',
          backgroundColor: '#b30000',
        },
        {
          label: 'Standard Meters',
          data: data_elec_std,
          borderColor: '#e34a33',
          backgroundColor: '#e34a33',
        },
        {
          label: 'Economy 7 Meters',
          data: data_elec_eco7,
          borderColor: '#fdcc8a',
          backgroundColor: '#fdcc8a',
        }
      ]
    };
	
	
	const dataGas = {
    labels: labels,
      datasets: [
        {
          label: 'All meters',
          data: data_gas,
          borderColor: '#2b8cbe',
          backgroundColor: '#2b8cbe',
        }
      ]
    };
	
	var metersctx = document.getElementById('meters-chart').getContext('2d');
	retrofitCard_metersChart = new Chart(metersctx, {
    type: 'bar',
      data: dataMeters,
      options: {
        responsive: true,
        maintainAspectRatio: false,
        interaction: {
          intersect: false,
        },
        scales: {
          x: {
            stacked: true,
            title: {
              display: true,
              text: 'Year'
            }
          },
          y: {
            stacked: true,
            title: {
              display: true,
              text: 'Meters'
            }
          }
        }
      }
  });
	
	var emissionsctx = document.getElementById('emissions-chart').getContext('2d');
	retrofitCard_emissionsChart = new Chart(emissionsctx, {
    type: 'line',
    data: dataEmissions,
    options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
        y: {
          title: {
            display: true,
            text: 'Emissions kgCO2e'
          },
          beginAtZero: true
        },
        x: {
          title: {
            display: true,
            text: 'Year'
          }
        }
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    },
  });
  
  var gasctx = document.getElementById('gas-chart').getContext('2d');
	retrofitCard_gasChart = new Chart(gasctx, {
    type: 'line',
    data: dataGas,
    options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
        y: {
          title: {
            display: true,
            text: 'Gas Consumption kWh'
          },
          beginAtZero: true
        },
        x: {
          title: {
            display: true,
            text: 'Year'
          }
        }
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    },
  });
	
	var electricityctx = document.getElementById('electricity-chart').getContext('2d');
	retrofitCard_electricityChart = new Chart(electricityctx, {
    type: 'line',
    data: dataElectricity,
    options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
        y: {
          title: {
            display: true,
            text: 'Consumption kWh'
          },
          beginAtZero: true
        },
        x: {
          title: {
            display: true,
            text: 'Year'
          }
        }
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    },
  });
  
}

retrofitCard_makeChartLSOAEnergy = function(locationId){
  
  console.log("Make LSOA Energy Charts charts");
  // Access Chart
  // Destroy old chart
	if(retrofitCard_emissionsLSOAChart){
		retrofitCard_emissionsLSOAChart.destroy();
	}
	if(retrofitCard_gasLSOAChart){
		retrofitCard_gasLSOAChart.destroy();
	}
	if(retrofitCard_electricityLSOAChart){
		retrofitCard_electricityLSOAChart.destroy();
	}
  if(retrofitCard_metersLSOAChart){
		retrofitCard_metersLSOAChart.destroy();
	}
  if(retrofitCard_energybillsLSOAChart){
		retrofitCard_energybillsLSOAChart.destroy();
	}

  // Get Control Settings
  const setting_emissions = document.getElementById("select_emissionsLSOA").value;
	const setting_gas = document.getElementById("select_gasLSOA").value;
  const setting_electricity = document.getElementById("select_electricityLSOA").value;
  
  let data_emissions_gas;
  let data_emissions_elec;
  let data_elec_all;

  // Get data
  
  if(setting_emissions == "total"){
     data_emissions_gas = retrofitCard_lsoaEnergyData['total_gas_kgco2e'];
     data_emissions_elec = retrofitCard_lsoaEnergyData['total_elec_kgco2e'];
     data_emissions_other = retrofitCard_lsoaEnergyData['total_other_kgco2e'];
  } else if (setting_emissions == "mean") {
     data_emissions_gas = retrofitCard_lsoaEnergyData['mean_gas_kgco2e'];
     data_emissions_elec = retrofitCard_lsoaEnergyData['mean_elec_kgco2e'];
     data_emissions_other = retrofitCard_lsoaEnergyData['mean_other_kgco2e'];
  } else if (setting_emissions == "median") {
     data_emissions_gas = retrofitCard_lsoaEnergyData['median_gas_kgco2e'];
     data_emissions_elec = retrofitCard_lsoaEnergyData['median_elec_kgco2e'];
     data_emissions_other = retrofitCard_lsoaEnergyData['mean_other_kgco2e']; // Using mean for other as median not available
  }
  
  if(setting_electricity == "total"){
     data_elec_all = retrofitCard_lsoaEnergyData['total_elec_kwh'];
  } else if (setting_electricity == "mean") {
     data_elec_all = retrofitCard_lsoaEnergyData['mean_elec_kwh'];
  } else if (setting_electricity == "median") {
     data_elec_all = retrofitCard_lsoaEnergyData['median_elec_kwh'];
  }
  
  if(setting_gas == "total"){
     data_gas = retrofitCard_lsoaEnergyData['total_gas_kwh'];
  } else if (setting_gas == "mean") {
     data_gas = retrofitCard_lsoaEnergyData['mean_gas_kwh'];
  } else if (setting_gas == "median") {
     data_gas = retrofitCard_lsoaEnergyData['median_gas_kwh'];
  }
  
  
  
  const labels = retrofitCard_lsoaEnergyData.year;
  const dataMeters = {
    labels: labels,
    datasets: [
      {
        label: 'Gas',
        data: retrofitCard_lsoaEnergyData['meters_gas'],
        backgroundColor: '#2b8cbe',
        stack: 'Stack 0',
      },
      {
        label: 'Electric',
        data: retrofitCard_lsoaEnergyData['meters_elec'],
        backgroundColor: '#b30000',
        stack: 'Stack 1',
      }
    ]
  };
  
  
  const dataEmissions = {
    labels: labels,
      datasets: [
        {
          label: 'Gas',
          data: data_emissions_gas,
          borderColor: '#2b8cbe',
          backgroundColor: '#2b8cbe',
        },
        {
          label: 'Electricity',
          data: data_emissions_elec,
          borderColor: '#b30000',
          backgroundColor: '#b30000',
        },
        {
          label: 'Other',
          data: data_emissions_other,
          borderColor: '#008000',
          backgroundColor: '#008000',
        }
      ]
    };
	
	const dataElectricity = {
    labels: labels,
      datasets: [
        {
          label: 'Domestic Electricity',
          data: data_elec_all,
          borderColor: '#b30000',
          backgroundColor: '#b30000',
        }
      ]
    };
	
	
	const dataGas = {
    labels: labels,
      datasets: [
        {
          label: 'Domestic Gas',
          data: data_gas,
          borderColor: '#2b8cbe',
          backgroundColor: '#2b8cbe',
        }
      ]
    };
	
    const dataEnergyBills = {
    labels: labels,
      datasets: [
        {
          label: 'Gas',
          data: retrofitCard_lsoaEnergyData['gas_average_bill'],
          borderColor: '#2b8cbe',
          backgroundColor: '#2b8cbe',
        },
        {
          label: 'Electricity',
          data: retrofitCard_lsoaEnergyData['elec_average_bill'],
          borderColor: '#b30000',
          backgroundColor: '#b30000',
        },
        {
          label: 'Other',
          data: retrofitCard_lsoaEnergyData['otherheating_average_bill'],
          borderColor: '#008000',
          backgroundColor: '#008000',
        },
        {
          label: 'Total',
          data: retrofitCard_lsoaEnergyData['energy_average_bill'],
          borderColor: '#420144',
          backgroundColor: '#420144',
        }
      ]
    };

	var metersctx = document.getElementById('metersLSOA-chart').getContext('2d');
	retrofitCard_metersLSOAChart = new Chart(metersctx, {
    type: 'bar',
      data: dataMeters,
      options: {
        responsive: true,
        maintainAspectRatio: false,
        interaction: {
          intersect: false,
        },
        scales: {
          x: {
            stacked: true,
            title: {
              display: true,
              text: 'Year'
            }
          },
          y: {
            stacked: true,
            title: {
              display: true,
              text: 'Meters'
            }
          }
        }
      }
  });
	
	var emissionsctx = document.getElementById('emissionsLSOA-chart').getContext('2d');
	retrofitCard_emissionsLSOAChart = new Chart(emissionsctx, {
    type: 'line',
    data: dataEmissions,
    options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
        y: {
          title: {
            display: true,
            text: 'Emissions kgCO2e'
          },
          beginAtZero: true
        },
        x: {
          title: {
            display: true,
            text: 'Year'
          }
        }
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    },
  });

  var energybillsctx = document.getElementById('energybillsLSOA-chart').getContext('2d');
	retrofitCard_energybillsLSOAChart = new Chart(energybillsctx, {
    type: 'line',
    data: dataEnergyBills,
    options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
        y: {
          title: {
            display: true,
            text: 'Average Bill (£)'
          },
          beginAtZero: true
        },
        x: {
          title: {
            display: true,
            text: 'Year'
          }
        }
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    },
  });
  
  var gasctx = document.getElementById('gasLSOA-chart').getContext('2d');
	retrofitCard_gasLSOAChart = new Chart(gasctx, {
    type: 'line',
    data: dataGas,
    options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
        y: {
          title: {
            display: true,
            text: 'Gas Consumption kWh'
          },
          beginAtZero: true
        },
        x: {
          title: {
            display: true,
            text: 'Year'
          }
        }
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    },
  });
	
	var electricityctx = document.getElementById('electricityLSOA-chart').getContext('2d');
	retrofitCard_electricityLSOAChart = new Chart(electricityctx, {
    type: 'line',
    data: dataElectricity,
    options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
        y: {
          title: {
            display: true,
            text: 'Consumption kWh'
          },
          beginAtZero: true
        },
        x: {
          title: {
            display: true,
            text: 'Year'
          }
        }
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    },
  });
  
}


retrofitCard_makeChartPrices = function(){
  
  console.log("Make prices charts");
  
  // Destroy old charts
  if(retrofitCard_pricesChart){
    retrofitCard_pricesChart.destroy();
  }
  if(retrofitCard_transactionsChart){
    retrofitCard_transactionsChart.destroy();
  }
  
  // Prepare data for box and whisker chart (prices)
  // Using line chart to show median with range indicators
  const pricesData = {
    labels: retrofitCard_pricesLocationData.year,
    datasets: [
      {
        label: 'Maximum Price',
        data: retrofitCard_pricesLocationData.price_max,
        borderColor: '#c0c0c0',
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderDash: [5, 5],
        fill: false,
        pointRadius: 0,
        tension: 0.1,
        hidden: true
      },
      {
        label: 'Upper Quartile (Q3)',
        data: retrofitCard_pricesLocationData.price_75,
        borderColor: '#a8d5e8',
        backgroundColor: 'transparent',
        borderWidth: 1,
        fill: false,
        pointRadius: 0,
        tension: 0.1
      },
      {
        label: 'Median Price',
        data: retrofitCard_pricesLocationData.price_median,
        borderColor: '#2b8cbe',
        backgroundColor: '#2b8cbe',
        borderWidth: 2,
        fill: false,
        pointRadius: 4,
        pointBackgroundColor: '#2b8cbe',
        tension: 0.1
      },
      {
        label: 'Lower Quartile (Q1)',
        data: retrofitCard_pricesLocationData.price_25,
        borderColor: '#a8d5e8',
        backgroundColor: 'transparent',
        borderWidth: 1,
        fill: false,
        pointRadius: 0,
        tension: 0.1
      },
      {
        label: 'Minimum Price',
        data: retrofitCard_pricesLocationData.price_min,
        borderColor: '#c0c0c0',
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderDash: [5, 5],
        fill: false,
        pointRadius: 0,
        tension: 0.1
      }
    ]
  };
  
  // Create price chart
  var pricesctx = document.getElementById('prices-chart').getContext('2d');
  retrofitCard_pricesChart = new Chart(pricesctx, {
    type: 'line',
    data: pricesData,
    options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
        y: {
          title: {
            display: true,
            text: 'Price (£)'
          },
          beginAtZero: false
        },
        x: {
          title: {
            display: true,
            text: 'Year'
          }
        }
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    }
  });
  
  // Prepare data for transactions bar chart
  const transactionsData = {
    labels: retrofitCard_pricesLocationData.year,
    datasets: [{
      label: 'Number of Transactions',
      data: retrofitCard_pricesLocationData.transactions,
      backgroundColor: '#d7191c',
      borderColor: '#d7191c',
      borderWidth: 1
    }]
  };
  
  // Create transactions chart
  var transactionsctx = document.getElementById('transactions-chart').getContext('2d');
  retrofitCard_transactionsChart = new Chart(transactionsctx, {
    type: 'bar',
    data: transactionsData,
    options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
        y: {
          title: {
            display: true,
            text: 'Number of Transactions'
          },
          beginAtZero: true
        },
        x: {
          title: {
            display: true,
            text: 'Year'
          }
        }
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    }
  });
  
}

retrofitCard_makeChartLSOA = function(){
  
  console.log("Make LSOA charts");
  
  // EPC chart
  
  epcratingData = [
  retrofitCard_lsoaLocationData.epc_A,
  retrofitCard_lsoaLocationData.epc_B,
  retrofitCard_lsoaLocationData.epc_C,
  retrofitCard_lsoaLocationData.epc_D,
  retrofitCard_lsoaLocationData.epc_E,
  retrofitCard_lsoaLocationData.epc_F,
  retrofitCard_lsoaLocationData.epc_G,
  retrofitCard_lsoaLocationData.epc_other,
  ];
 
	retrofitCard_epcratingChart = retrofitCard_makePieChart(retrofitCard_epcratingChart,'epcrating-chart','EPC rating',
  epcratingData,
  ['#0e7e58','#2aa45b','#8cbc42','#f6cc15','#f2a867','#f17e23','#e31d3e','#c0c0c0'],
  ['A','B','C','D','E','F','G','Other']);
  
  // Building type
  
  buildingtypeData = [
  retrofitCard_lsoaLocationData.type_house_detached,
  retrofitCard_lsoaLocationData.type_house_semi,
  retrofitCard_lsoaLocationData.type_house_midterrace,
  retrofitCard_lsoaLocationData.type_house_endterrace,
  retrofitCard_lsoaLocationData.type_flat,
  retrofitCard_lsoaLocationData.type_bungalow_detached,
  retrofitCard_lsoaLocationData.type_bungalow_semi,
  retrofitCard_lsoaLocationData.type_bungalow_midterrace,
  retrofitCard_lsoaLocationData.type_bungalow_endterrace,
  retrofitCard_lsoaLocationData.type_maisonette,
  retrofitCard_lsoaLocationData.type_parkhome,
  retrofitCard_lsoaLocationData.type_other,
  ];
 
	retrofitCard_buildingtypeChart = retrofitCard_makePieChart(retrofitCard_buildingtypeChart,'buildingtype-chart','Building type',
  buildingtypeData,
  ['#c2e699','#78c679','#006837','#31a354','#e31a1c','#fbb4b9','#f768a1','#7a0177','#c51b8a','#1f78b4','#fa7c00','#c0c0c0'],
  ['Detached house','Semi-detached house','Mid-terrace house','End-terrace house',
			'Flat','Detached bungalow','Semi-detached bungalow','Mid-terrace bungalow',
			'End-terrace bungalow','Maisonette','Park home','Other']);
	
  // Tenure type
  
  tenureData = [
  retrofitCard_lsoaLocationData.tenure_owner,
  retrofitCard_lsoaLocationData.tenure_privaterent,
  retrofitCard_lsoaLocationData.tenure_socialrent,
  retrofitCard_lsoaLocationData.tenure_unknown
  ];
 
  retrofitCard_tenureChart = retrofitCard_makePieChart(retrofitCard_tenureChart,'tenure-chart','Tenure',
  tenureData,
  ['#33a02c','#e31a1c','#1f78b4','#c0c0c0'],
  ['Owner','Private rent','Social rent','Unknown']);
  
  // Age

  ageData = [
  retrofitCard_lsoaLocationData.age_pre1900,
  retrofitCard_lsoaLocationData.age_19001929,
  retrofitCard_lsoaLocationData.age_19301949,
  retrofitCard_lsoaLocationData.age_19501966,
  retrofitCard_lsoaLocationData.age_19671975,
  retrofitCard_lsoaLocationData.age_19761982,
  retrofitCard_lsoaLocationData.age_19831990,
  retrofitCard_lsoaLocationData.age_19911995,
  retrofitCard_lsoaLocationData.age_19962002,
  retrofitCard_lsoaLocationData.age_20032006,
  retrofitCard_lsoaLocationData.age_20072011,
  retrofitCard_lsoaLocationData.age_20122021,
  retrofitCard_lsoaLocationData.age_post2022,
  retrofitCard_lsoaLocationData.age_unknown,
  ];
 
  retrofitCard_ageChart = retrofitCard_makePieChart(retrofitCard_ageChart,'age-chart','Building Age',
  ageData,
  ['#9e0142','#d53e4f','#f46d43','#fdae61','#fee08b','#ffffbf','#e6f598','#abdda4','#66c2a5','#3288bd','#5e4fa2','#934fa2','#c259a7','#c0c0c0'],
  ['pre-1900','1900-1929','1930-1949','1950-1966','1967-1975','1976-1982',
  '1983-1990','1991-1995','1996-2002','2003-2006','2007-2011','2012-2021','post-2022','Unknown']);
  
  
  // floor
  // TODO: Data looks wrong
  
  floorData = [
    retrofitCard_lsoaLocationData.floor_verygood,
    retrofitCard_lsoaLocationData.floor_good,
    retrofitCard_lsoaLocationData.floor_average,
    retrofitCard_lsoaLocationData.floor_poor,
    retrofitCard_lsoaLocationData.floor_verypoor,
    retrofitCard_lsoaLocationData.floor_below,
    retrofitCard_lsoaLocationData.floor_other,
  ];
 
  retrofitCard_floorChart = retrofitCard_makePieChart(retrofitCard_floorChart,'floor-chart','',
  floorData,
  ['#2c7bb6','#abd9e9','#ffffbf','#fdae61','#d7191c','#225ea8','#c0c0c0'],
  ['Very Good','Good','Average','Poor','Very Poor','Dwelling Below','Other']);
  
  // floord
  
  floordData = [
    retrofitCard_lsoaLocationData.floord_soliduninsulated,
    retrofitCard_lsoaLocationData.floord_solidinsulated,
    retrofitCard_lsoaLocationData.floord_solidlimitedinsulated,
    retrofitCard_lsoaLocationData.floord_suspendeduninsulated,
    retrofitCard_lsoaLocationData.floord_suspendedinsualted,
    retrofitCard_lsoaLocationData.floord_suspendedlimitedinsulated,
    retrofitCard_lsoaLocationData.floord_external,
    retrofitCard_lsoaLocationData.floord_below,
    retrofitCard_lsoaLocationData.floord_other
  ];
 
  retrofitCard_floordChart = retrofitCard_makePieChart(retrofitCard_floordChart,'floord-chart','',
  floordData,
  ['#238b45','#b2e2e2','#66c2a4','#ce1256','#f1b6da','#df65b0','#fdae61','#225ea8','#c0c0c0'],
  ['Solid uninsulated','Solid insulated','Solid limited insulation','Suspended uninsulated','Suspended insulated','Suspended limited insulation','Exposed to outside air','Dwelling Below','Other']);
  
  // window
  
  windowData = [
    retrofitCard_lsoaLocationData.window_verygood,
    retrofitCard_lsoaLocationData.window_good,
    retrofitCard_lsoaLocationData.window_average,
    retrofitCard_lsoaLocationData.window_poor,
    retrofitCard_lsoaLocationData.window_verypoor,
    retrofitCard_lsoaLocationData.window_other
  ];
 
  retrofitCard_windowChart = retrofitCard_makePieChart(retrofitCard_windowChart,'window-chart','',
  windowData,
  ['#2c7bb6','#abd9e9','#ffffbf','#fdae61','#d7191c','#c0c0c0'],
  ['Very Good','Good','Average','Poor','Very Poor','Other']);
  
  // water
  
  waterData = [
    retrofitCard_lsoaLocationData.water_verygood,
    retrofitCard_lsoaLocationData.water_good,
    retrofitCard_lsoaLocationData.water_average,
    retrofitCard_lsoaLocationData.water_poor,
    retrofitCard_lsoaLocationData.water_verypoor,
    retrofitCard_lsoaLocationData.water_other,

  ];
 
  retrofitCard_waterChart = retrofitCard_makePieChart(retrofitCard_waterChart,'water-chart','',
  waterData,
  ['#2c7bb6','#abd9e9','#ffffbf','#fdae61','#d7191c','#c0c0c0'],
  ['Very Good','Good','Average','Poor','Very Poor','Other']);
  
  // waterd
  
  waterdData = [
    retrofitCard_lsoaLocationData.waterd_mainsystem,
    retrofitCard_lsoaLocationData.waterd_immersion,
    retrofitCard_lsoaLocationData.waterd_community,
    retrofitCard_lsoaLocationData.waterd_instantaneous,
    retrofitCard_lsoaLocationData.waterd_gasmultipoint,
    retrofitCard_lsoaLocationData.waterd_other
  ];
 
  retrofitCard_waterdChart = retrofitCard_makePieChart(retrofitCard_waterdChart,'waterd-chart','',
  waterdData,
  ['#e41a1c','#377eb8','#4daf4a','#984ea3','#ffff33','#c0c0c0'],
  ['Main system','Immersion heater','Community system','Instantaneous water heater','Gas multipoint','Other']);
  
  // glazing
  
  glazingData = [
    retrofitCard_lsoaLocationData.glazing_single,
    retrofitCard_lsoaLocationData.glazing_double,
    retrofitCard_lsoaLocationData.glazing_triple,
    retrofitCard_lsoaLocationData.glazing_secondary,
    retrofitCard_lsoaLocationData.glazing_unknown
  ];
 
  retrofitCard_glazingChart = retrofitCard_makePieChart(retrofitCard_glazingChart,'glazing-chart','',
  glazingData,
  ['#e41a1c','#377eb8','#4daf4a','#984ea3','#c0c0c0'],
  ['single','double','triple','secondary','unknown']);
  
  // wall
  
  wallData = [
    retrofitCard_lsoaLocationData.wall_verygood,
    retrofitCard_lsoaLocationData.wall_good,
    retrofitCard_lsoaLocationData.wall_average,
    retrofitCard_lsoaLocationData.wall_poor,
    retrofitCard_lsoaLocationData.wall_verypoor,
    retrofitCard_lsoaLocationData.wall_other

  ];
 
  retrofitCard_wallChart = retrofitCard_makePieChart(retrofitCard_wallChart,'wall-chart','',
  wallData,
  ['#2c7bb6','#abd9e9','#ffffbf','#fdae61','#d7191c','#c0c0c0'],
  ['Very Good','Good','Average','Poor','Very Poor','Other']);
  
  // walld
  
  walldData = [
    retrofitCard_lsoaLocationData.walld_cavity,
    retrofitCard_lsoaLocationData.walld_solid,
    retrofitCard_lsoaLocationData.walld_timber,
    retrofitCard_lsoaLocationData.walld_sandlimestone,
    retrofitCard_lsoaLocationData.walld_granitewhinstine,
    retrofitCard_lsoaLocationData.walld_system,
    retrofitCard_lsoaLocationData.walld_other
  ];
 
  retrofitCard_walldChart = retrofitCard_makePieChart(retrofitCard_walldChart,'walld-chart','',
  walldData,
  ['#e41a1c','#377eb8','#4daf4a','#984ea3','#ff7f00','#ffff33','#c0c0c0'],
  ['Cavity','Solid','Timber','Sand/limestone','Granite/whinstine','System built','Other']);
  
  // roof
  
  roofData = [
    retrofitCard_lsoaLocationData.roof_verygood,
    retrofitCard_lsoaLocationData.roof_good,
    retrofitCard_lsoaLocationData.roof_average,
    retrofitCard_lsoaLocationData.roof_poor,
    retrofitCard_lsoaLocationData.roof_verypoor,
    retrofitCard_lsoaLocationData.roof_above,
    retrofitCard_lsoaLocationData.roof_other

  ];
 
  retrofitCard_roofChart = retrofitCard_makePieChart(retrofitCard_roofChart,'roof-chart','',
  roofData,
  ['#2c7bb6','#abd9e9','#ffffbf','#fdae61','#d7191c','#4d9221','#c0c0c0'],
  ['Very Good','Good','Average','Poor','Very Poor','Dwelling Above','Other']);
  
  // roofd
  
  roofdData = [
    retrofitCard_lsoaLocationData.roofd_pitched,
    retrofitCard_lsoaLocationData.roofd_flat,
    retrofitCard_lsoaLocationData.roofd_room,
    retrofitCard_lsoaLocationData.roofd_thatched,
    retrofitCard_lsoaLocationData.roofd_above,
    retrofitCard_lsoaLocationData.roofd_other
  ];
 
  retrofitCard_roofdChart = retrofitCard_makePieChart(retrofitCard_roofdChart,'roofd-chart','',
  roofdData,
  ['#e41a1c','#377eb8','#4daf4a','#ffff33','#4d9221','#c0c0c0'],
  ['Pitched','Flat roof','Room in roof','Thatched','Dwelling Above','Other']);
  
  // mainheatdesc
  
  mainheatdescData = [
    retrofitCard_lsoaLocationData.mainheatdesc_gasboiler,
    retrofitCard_lsoaLocationData.mainheatdesc_oilboiler,
    retrofitCard_lsoaLocationData.mainheatdesc_storageheater,
    retrofitCard_lsoaLocationData.mainheatdesc_portableheater,
    retrofitCard_lsoaLocationData.mainheatdesc_roomheater,
    retrofitCard_lsoaLocationData.mainheatdesc_heatpump,
    retrofitCard_lsoaLocationData.mainheatdesc_community,
    retrofitCard_lsoaLocationData.mainheatdesc_other
  ];
 
  retrofitCard_mainheatdescChart = retrofitCard_makePieChart(retrofitCard_mainheatdescChart,'mainheatdesc-chart','',
  mainheatdescData,
  ['#e41a1c','#984ea3','#ff7f00','#a65628','#ffff33','#4daf4a','#377eb8','#c0c0c0'],
  ['Gas boiler','Oil boiler','Storage heater','Portable heater','Room heaters','Heat pump','Community','Other']);
  
  // mainheat
  
  mainheatData = [
    retrofitCard_lsoaLocationData.mainheat_verygood,
    retrofitCard_lsoaLocationData.mainheat_good,
    retrofitCard_lsoaLocationData.mainheat_average,
    retrofitCard_lsoaLocationData.mainheat_poor,
    retrofitCard_lsoaLocationData.mainheat_verypoor,
    retrofitCard_lsoaLocationData.mainheat_other

  ];
 
  retrofitCard_mainheatChart = retrofitCard_makePieChart(retrofitCard_mainheatChart,'mainheat-chart','',
  mainheatData,
  ['#2c7bb6','#abd9e9','#ffffbf','#fdae61','#d7191c','#c0c0c0'],
  ['Very Good','Good','Average','Poor','Very Poor','Other']);
  
  
  // mainfuel
  
  mainfuelData = [
    retrofitCard_lsoaLocationData.mainfuel_mainsgas,
    retrofitCard_lsoaLocationData.mainfuel_electric,
    retrofitCard_lsoaLocationData.mainfuel_oil,
    retrofitCard_lsoaLocationData.mainfuel_coal,
    retrofitCard_lsoaLocationData.mainfuel_lpg,
    retrofitCard_lsoaLocationData.mainfuel_biomass,
    retrofitCard_lsoaLocationData.mainfuel_dualfuel,
    retrofitCard_lsoaLocationData.mainfuel_other
  ];
 
  retrofitCard_mainfuelChart = retrofitCard_makePieChart(retrofitCard_mainfuelChart,'mainfuel-chart','',
  mainfuelData,
  ['#e41a1c','#377eb8','#984ea3','#666666','#ff7f00','#4daf4a','#a65628','#c0c0c0'],
  ['Mains gas','Electric','Oil','Coal','LPG','Biomass','Dual fuel','Other']);
  
  // mainheatcontrol
  
  mainheatcontrolData = [
    retrofitCard_lsoaLocationData.mainheatcontrol_verygood,
    retrofitCard_lsoaLocationData.mainheatcontrol_good,
    retrofitCard_lsoaLocationData.mainheatcontrol_average,
    retrofitCard_lsoaLocationData.mainheatcontrol_poor,
    retrofitCard_lsoaLocationData.mainheatcontrol_verypoor,
    retrofitCard_lsoaLocationData.mainheatcontrol_other

  ];
 
  retrofitCard_mainheatcontrolChart = retrofitCard_makePieChart(retrofitCard_mainheatcontrolChart,'mainheatcontrol-chart','',
  mainheatcontrolData,
  ['#2c7bb6','#abd9e9','#ffffbf','#fdae61','#d7191c','#c0c0c0'],
  ['Very Good','Good','Average','Poor','Very Poor','Other']);
  
  // controld
  
  controldData = [
    retrofitCard_lsoaLocationData.controld_progthermtrvs,
    retrofitCard_lsoaLocationData.controld_progtherm,
    retrofitCard_lsoaLocationData.controld_progtrvsbypass,
    retrofitCard_lsoaLocationData.controld_pzones,
    retrofitCard_lsoaLocationData.controld_other
  ];
 
  retrofitCard_controldChart = retrofitCard_makePieChart(retrofitCard_controldChart,'controld-chart','',
  controldData,
  ['#e41a1c','#377eb8','#4daf4a','#984ea3','#c0c0c0'],
  ['progammer, thermostats & trvs','progammer, thermostats','progammer,trvs & bypass','zones','Other']);
  
  // light
  
  lightData = [
    retrofitCard_lsoaLocationData.light_verygood,
    retrofitCard_lsoaLocationData.light_good,
    retrofitCard_lsoaLocationData.light_average,
    retrofitCard_lsoaLocationData.light_poor,
    retrofitCard_lsoaLocationData.light_verypoor,
    retrofitCard_lsoaLocationData.light_other
  ];
 
  retrofitCard_lightChart = retrofitCard_makePieChart(retrofitCard_lightChart,'light-chart','',
  lightData,
  ['#2c7bb6','#abd9e9','#ffffbf','#fdae61','#d7191c','#c0c0c0'],
  ['Very Good','Good','Average','Poor','Very Poor','Other']);
  
  // solarpv
  
  solarpvData = [
    retrofitCard_lsoaLocationData.solarpv_yes,
    retrofitCard_lsoaLocationData.solarpv_no
  ];
 
  retrofitCard_solarpvChart = retrofitCard_makePieChart(retrofitCard_solarpvChart,'solarpv-chart','',
  solarpvData,
  ['#2c7bb6','#d7191c'],
  ['Yes','No']);
  
  // solarthermal
  
  solarthermalData = [
    retrofitCard_lsoaLocationData.solarthermal_yes,
    retrofitCard_lsoaLocationData.solarthermal_no
  ];
 
  retrofitCard_solarthermalChart = retrofitCard_makePieChart(retrofitCard_solarthermalChart,'solarthermal-chart','',
  solarthermalData,
  ['#2c7bb6','#d7191c'],
  ['Yes','No']);
  
  
  
}

retrofitCard_makePieChart = function(chartVar, name, label, data, colours, labels){
  if (chartVar) {
    chartVar.destroy();
  }
  
  // Drop any slice whose value is missing from the data, together with its
  // colour and label. Without this a renamed or not-yet-published field shows
  // as a legend entry with no wedge, which reads as a real zero.
  var keep = [];
  for (var i = 0; i < data.length; i++) {
    if (data[i] !== undefined && data[i] !== null) { keep.push(i); }
  }
  if (keep.length !== data.length) {
    data    = keep.map(function (i) { return data[i]; });
    colours = keep.map(function (i) { return colours[i]; });
    labels  = keep.map(function (i) { return labels[i]; });
  }
  
  chartVar = new Chart(document.getElementById(name).getContext('2d'), {
		type: 'pie',
		data: {
			datasets: [{
				label: label,
				data: data,
				backgroundColor: colours
				
			}],
			
			labels: labels
		},
		options: {
			responsive: true,
			maintainAspectRatio: false
		}
	});
	
	return chartVar;
}




// Function to switch chart description tabs (Overview / Policy / Methods)
// Scoped to the chart's own .chart-description-tabs container, so multiple
// chart tab groups operate independently.
switchChartTab = function (evt, tabName) {
  var tabsContainer = evt.currentTarget.closest('.chart-description-tabs');
  tabsContainer.querySelectorAll('.chart-description-tab-content').forEach(function (content) {
    content.classList.remove('active');
    content.style.display = 'none';
  });
  tabsContainer.querySelectorAll('.chart-tab-btn').forEach(function (button) {
    button.classList.remove('active');
  });
  var selectedContent = document.getElementById(tabName);
  if (selectedContent) {
    selectedContent.classList.add('active');
    selectedContent.style.display = 'block';
    evt.currentTarget.classList.add('active');
  }
};



// ---- Dwelling stock charts, ported from retrofit/ui.js ----

// Show/hide a group of chart blocks and its "no data here" note together.
// Chart rows in this tool are wrapped in a div whose id is the chart name with
// '-chartrow' appended, so a whole group can be swapped for one explanation
// without disturbing the rest of the card.
function retrofitCard_voaSetAvailable (chartNames, noteId, available)
{
	chartNames.forEach (function (name) {
		const row = document.getElementById (name + '-chartrow');
		if (row) { row.style.display = (available ? 'block' : 'none'); }
	});
	const note = document.getElementById (noteId);
	if (note) { note.style.display = (available ? 'none' : 'block'); }
}

retrofitCard_makeChartVOABands = function(){
  
  	// overview Chart
  	// Destroy old chart
	if(retrofitCard_dwellingsctChart){
		retrofitCard_dwellingsctChart.destroy();
	}
  
  	//console.log(retrofitCard_voaBandsLocationData);
 
	const years = retrofitCard_voaBandsLocationData['year'];	  
	const bA = retrofitCard_voaBandsLocationData['banda'];
  	const bB = retrofitCard_voaBandsLocationData['bandb'];
  	const bC = retrofitCard_voaBandsLocationData['bandc'];
  	const bD = retrofitCard_voaBandsLocationData['bandd'];
  	const bE = retrofitCard_voaBandsLocationData['bande'];
  	const bF = retrofitCard_voaBandsLocationData['bandf'];
  	const bG = retrofitCard_voaBandsLocationData['bandg'];
  	const bH = retrofitCard_voaBandsLocationData['bandh'];
  	const bI = retrofitCard_voaBandsLocationData['bandi'];
  
  
  var dwellingsctctx = document.getElementById('dwellingsct-chart').getContext('2d');
	retrofitCard_dwellingsctChart = new Chart(dwellingsctctx, {
		type: 'bar',
		data: {
			labels: years,
			datasets: [{
				label: 'A',
				data: bA,
				backgroundColor: 'rgba(77,146,33, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: 'B',
				data: bB,
				backgroundColor: 'rgba(127,188,65, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: 'C',
				data: bC,
				backgroundColor: 'rgba(184,225,134, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: 'D',
				data: bD,
				backgroundColor: 'rgba(230,245,208, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: 'E',
				data: bE,
				backgroundColor: 'rgba(247,247,247, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
      {
				label: 'F',
				data: bF,
				backgroundColor: 'rgba(253,224,239, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
      {
				label: 'G',
				data: bG,
				backgroundColor: 'rgba(241,182,218, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
      {
				label: 'H',
				data: bH,
				backgroundColor: 'rgba(222,119,174, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
      {
				label: 'I',
				data: bI,
				backgroundColor: 'rgba(197,27,125, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			]
		},
		options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
							y: {
								stacked: true,
								ticks: {
									beginAtZero: true
								}
							},
							x: {
								stacked: true
							}
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    }
	});
  
  
}


retrofitCard_makeChartVOAStock = function(){
  
  // Destroy old chart
	if(retrofitCard_dwellingstypeChart){
		retrofitCard_dwellingstypeChart.destroy();
	}
	
	if(retrofitCard_dwellingsbedroomsChart){
		retrofitCard_dwellingsbedroomsChart.destroy();
	}
	
	if(retrofitCard_dwellingsageChart){
		retrofitCard_dwellingsageChart.destroy();
	}
  
	const years = retrofitCard_voaStockLocationData['year'];	  

  var dwellingstypectx = document.getElementById('dwellingstype-chart').getContext('2d');
	retrofitCard_dwellingstypeChart = new Chart(dwellingstypectx, {
		type: 'bar',
		data: {
			labels: years,
			datasets: [{
				label: 'Bungalow',
				data: retrofitCard_voaStockLocationData['bungalow'],
				backgroundColor: 'rgba(105, 60, 153, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: 'Flat/Maisonette',
				data: retrofitCard_voaStockLocationData['flatmais'],
				backgroundColor: 'rgba(227, 26, 28, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: 'Terraced',
				data: retrofitCard_voaStockLocationData['terraced'],
				backgroundColor: 'rgba(17, 219, 13, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: 'Semi-Detached',
				data: retrofitCard_voaStockLocationData['semi'],
				backgroundColor: 'rgba(14, 156, 11, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: 'Detached',
				data: retrofitCard_voaStockLocationData['detached'],
				backgroundColor: 'rgba(8, 82, 7, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
      {
				label: 'Annexe',
				data: retrofitCard_voaStockLocationData['annexe'],
				backgroundColor: 'rgba(31, 120, 180, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
      {
				label: 'Caravan/Boat/Mobile home',
				data: retrofitCard_voaStockLocationData['caravanboatmobilehome'],
				backgroundColor: 'rgba(250, 124, 0, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
      {
				label: 'Unknown',
				data: retrofitCard_voaStockLocationData['unknown'],
				backgroundColor: 'rgba(135, 136, 138, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			}
			]
		},
		options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
							y: {
								stacked: true,
								ticks: {
									beginAtZero: true
								}
							},
							x: {
								stacked: true
							}
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    }
	});
	
	
	var dwellingsbedroomsctx = document.getElementById('dwellingsbedrooms-chart').getContext('2d');
	retrofitCard_dwellingsbedroomsChart = new Chart(dwellingsbedroomsctx, {
		type: 'bar',
		data: {
			labels: years,
			datasets: [{
				label: '1',
				data: retrofitCard_voaStockLocationData['bed1'],
				backgroundColor: 'rgba(204,235,197, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: '2',
				data: retrofitCard_voaStockLocationData['bed2'],
				backgroundColor: 'rgba(168,221,181, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: '3',
				data: retrofitCard_voaStockLocationData['bed3'],
				backgroundColor: 'rgba(123,204,196, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: '4',
				data: retrofitCard_voaStockLocationData['bed4'],
				backgroundColor: 'rgba(78,179,211, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: '5',
				data: retrofitCard_voaStockLocationData['bed5'],
				backgroundColor: 'rgba(43,140,190, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
      {
				label: '6+',
				data: retrofitCard_voaStockLocationData['bed6'],
				backgroundColor: 'rgba(8,88,158, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			}
			]
		},
		options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
							y: {
								stacked: true,
								ticks: {
									beginAtZero: true
								}
							},
							x: {
								stacked: true
							}
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    }
	});
	
	
	var dwellingsagectx = document.getElementById('dwellingsage-chart').getContext('2d');
	retrofitCard_dwellingsageChart = new Chart(dwellingsagectx, {
		type: 'bar',
		data: {
			labels: years,
			datasets: [{
				label: 'pre 1900',
				data: retrofitCard_voaStockLocationData['bppre1900'],
				backgroundColor: 'rgba(158, 1, 66, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: '1900-18',
				data: retrofitCard_voaStockLocationData['bp19001918'],
				backgroundColor: 'rgba(213, 62, 79, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: '1919-29',
				data: retrofitCard_voaStockLocationData['bp19191929'],
				backgroundColor: 'rgba(244, 109, 67, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
			{
				label: '1930-39',
				data: retrofitCard_voaStockLocationData['bp19301939'],
				backgroundColor: 'rgba(244, 109, 67, 0.8)',
				borderColor: 'rgba(253, 174, 97)',
				borderWidth: 1,
				order: 1
			},
			{
				label: '1945-54',
				data: retrofitCard_voaStockLocationData['bp19451954'],
				backgroundColor: 'rgba(254,224,139, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
      {
				label: '1955-64',
				data: retrofitCard_voaStockLocationData['bp19551964'],
				backgroundColor: 'rgba(255,255,191, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
      {
				label: '1965-72',
				data: retrofitCard_voaStockLocationData['bp19651972'],
				backgroundColor: 'rgba(230,245,152, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
      {
				label: '1973-82',
				data: retrofitCard_voaStockLocationData['bp19731982'],
				backgroundColor: 'rgba(171,221,164, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
      {
				label: '1983-92',
				data: retrofitCard_voaStockLocationData['bp19831992'],
				backgroundColor: 'rgba(102,194,165, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},			
      {
				label: '1993-99',
				data: retrofitCard_voaStockLocationData['bp19931999'],
				backgroundColor: 'rgba(50,136,189, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},			
      {
				label: '2000-08',
				data: retrofitCard_voaStockLocationData['bp20002008'],
				backgroundColor: 'rgba(94,79,162, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},			
      {
				label: '2009-21',
				data: retrofitCard_voaStockLocationData['bp20092021'],
				backgroundColor: 'rgba(144, 77, 159, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},			
      {
				label: '2022-24',
				data: retrofitCard_voaStockLocationData['bp20222024'],
				backgroundColor: 'rgba(217, 22, 74, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			},
      {
				label: 'Unknown',
				data: retrofitCard_voaStockLocationData['bpunkw'],
				backgroundColor: 'rgba(135, 136, 138, 0.8)',
				borderColor: 'rgb(0,0,0)',
				borderWidth: 1,
				order: 1
			}	
			]
		},
		options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
							y: {
								stacked: true,
								ticks: {
									beginAtZero: true
								}
							},
							x: {
								stacked: true
							}
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    }
	});
  
  
}

// Registration: the report page calls window.reportCards.retrofit.load(locationId)
window.reportCards = window.reportCards || {};
window.reportCards.retrofit = {
  load: function (locationId) { return retrofitCard_manageCharts(locationId, 'zones'); },
  defaultOpen: 'retrofit-defaultOpen'
};
