// GENERATED FILE - do not edit by hand.
// Regenerated by scratchpad/make_report_cards.py from retrofit/ui.js + retrofit/index.html.
// Report-card module for the retrofit tool: renders every chart from the tool's
// zones report modal into the retrofit-card.html fragment on a report page.
// Data endpoints can be redirected (e.g. to area-level aggregates) by setting
// window.REPORT_CARD_ENDPOINTS = { '<default path>': '<replacement path>' }.

function retrofitCard_fetchJSON(url) {
  return fetch(url).then(function (r) {
    if (!r.ok) { throw new Error('HTTP ' + r.status); }
    return r.json();
  });
}

function retrofitCard_endpoint(path) {
  var overrides = window.REPORT_CARD_ENDPOINTS || {};
  return 'https://pbcc.blob.core.windows.net/pbcc-data/' + (overrides[path] || path);
}

// Tab switcher scoped to this card's own fragment, so multiple tool cards can
// coexist on one report page without cross-talk.
function retrofitCard_modalTab(evt, tabName) {
  var root = evt.currentTarget.closest('.report-fullcard');
  if (!root) { return; }
  root.querySelectorAll('.tabcontent').forEach(function (el) { el.style.display = 'none'; });
  root.querySelectorAll('.tablinks').forEach(function (el) { el.className = el.className.replace(' active', ''); });
  var target = root.querySelector('#' + tabName);
  if (target) { target.style.display = 'block'; }
  evt.currentTarget.className += ' active';
}

// Local Chart Management
var retrofitCard_emissionsChart;
var retrofitCard_gasChart;
var retrofitCard_electricityChart;
var retrofitCard_metersChart;

var retrofitCard_emissionsLSOAChart;
var retrofitCard_gasLSOAChart;
var retrofitCard_electricityLSOAChart;
var retrofitCard_metersLSOAChart;
var retrofitCard_energybillsLSOAChart;

var retrofitCard_epcratingChart;
var retrofitCard_buildingtypeChart;
var retrofitCard_tenureChart;
var retrofitCard_ageChart;
var retrofitCard_floorChart;
var retrofitCard_floordChart;
var retrofitCard_windowChart;
var retrofitCard_waterChart;
var retrofitCard_waterdChart;
var retrofitCard_glazingChart;
var retrofitCard_wallChart;
var retrofitCard_walldChart;
var retrofitCard_roofChart;
var retrofitCard_roofdChart;
var retrofitCard_mainheatChart;
var retrofitCard_mainheatdescChart;
var retrofitCard_mainfuelChart;
var retrofitCard_mainheatcontrolChart;
var retrofitCard_controldChart;
var retrofitCard_lightChart;
var retrofitCard_solarpvChart;
var retrofitCard_solarthermalChart;

var retrofitCard_pricesChart;
var retrofitCard_transactionsChart;

var retrofitCard_postcodeLocationData = {};
var retrofitCard_lsoaLocationData = {};
var retrofitCard_pricesLocationData = {};
var retrofitCard_lsoaEnergyData = {};

retrofitCard_manageCharts =  function (locationId, mapLayerId){
  if(mapLayerId == 'zones'){

    const pEPC = retrofitCard_fetchJSON(retrofitCard_endpoint('epc_dom/v4/') + locationId + '.json')
      .then(data => { retrofitCard_lsoaLocationData = data[0]; retrofitCard_makeChartLSOA(); })
      .catch(err => { console.error('EPC failed:', err); });  
    
    const pEnergy = retrofitCard_fetchJSON(retrofitCard_endpoint('lsoa_gas_electric/v2/') + locationId + '.json')
      .then(data => { retrofitCard_lsoaEnergyData = data; retrofitCard_makeChartLSOAEnergy(); })
      .catch(err => { console.error('Energy failed:', err); });  
    
    const pPrices = retrofitCard_fetchJSON(retrofitCard_endpoint('prices/v1/') + locationId + '.json')
      .then(data => { retrofitCard_pricesLocationData = data; retrofitCard_makeChartPrices(); })
      .catch(err => { 
        console.error('Prices failed:', err);
        if(retrofitCard_pricesChart){
          retrofitCard_pricesChart.destroy();
        }
        if(retrofitCard_transactionsChart){
          retrofitCard_transactionsChart.destroy();
        }
      });

    return Promise.all([pEPC, pPrices, pEnergy]);
    //return p;
  } else if (mapLayerId == 'postcodes'){
    const p = retrofitCard_fetchJSON(retrofitCard_endpoint('postcode_energy/v2/') + locationId + '.json')
        .then(function (postcodeData) {
            retrofitCard_postcodeLocationData = postcodeData;
            retrofitCard_makeChartPostcode(locationId);
        })
        .catch(function (error) {
            console.warn('Failed to get access data for this location, or to process it correctly. Please try refreshing the page.');
            console.log(error);
        });

    return p;
  } else {
    console.log('Unknown layer for chart management: ' + mapLayerId);
    return Promise.resolve();
  }
}

retrofitCard_makeChartPostcode = function(locationId){
  
  console.log("Make postcode charts");
  // Access Chart
  // Destroy old chart
	if(retrofitCard_emissionsChart){
		retrofitCard_emissionsChart.destroy();
	}
	if(retrofitCard_gasChart){
		retrofitCard_gasChart.destroy();
	}
	if(retrofitCard_electricityChart){
		retrofitCard_electricityChart.destroy();
	}
  if(retrofitCard_metersChart){
		retrofitCard_metersChart.destroy();
	}

  // Set modal title
  const title = locationId + ' postcode summary';
	document.querySelector('#postcodes-chartsmodal .modal-title').innerHTML = title;
  
  // Get Control Settings
  const setting_emissions = document.getElementById("select_emissions").value;
	const setting_gas = document.getElementById("select_gas").value;
  const setting_electricity = document.getElementById("select_electricity").value;
  
  let data_emissions_gas;
  let data_emissions_elec;
  let data_elec_all;
  let data_elec_std;
  let data_elec_eco7;
  let data_gas;
  

  // Get data
  // Not doing emissions for standard and eco7 meters
  if(setting_emissions == "total"){
     data_emissions_gas = retrofitCard_postcodeLocationData['gas_totalkgco2e'];
     data_emissions_elec = retrofitCard_postcodeLocationData['elec_totalkgco2e_all'];
  } else if (setting_emissions == "mean") {
     data_emissions_gas = retrofitCard_postcodeLocationData['gas_meankgco2e'];
     data_emissions_elec = retrofitCard_postcodeLocationData['elec_meankgco2e_all'];
  } else if (setting_emissions == "median") {
     data_emissions_gas = retrofitCard_postcodeLocationData['gas_mediankgco2e'];
     data_emissions_elec = retrofitCard_postcodeLocationData['elec_mediankgco2e_all'];
  }
  
  if(setting_electricity == "total"){
     data_elec_all = retrofitCard_postcodeLocationData['elec_totalkwh_all'];
     data_elec_std = retrofitCard_postcodeLocationData['elec_totalkwh_std'];
     data_elec_eco7 = retrofitCard_postcodeLocationData['elec_totalkwh_eco7'];
  } else if (setting_electricity == "mean") {
     data_elec_all = retrofitCard_postcodeLocationData['elec_meankwh_all'];
     data_elec_std = retrofitCard_postcodeLocationData['elec_meankwh_std'];
     data_elec_eco7 = retrofitCard_postcodeLocationData['elec_meankwh_eco7'];
  } else if (setting_electricity == "median") {
     data_elec_all = retrofitCard_postcodeLocationData['elec_mediankwh_all'];
     data_elec_std = retrofitCard_postcodeLocationData['elec_mediankwh_std'];
     data_elec_eco7 = retrofitCard_postcodeLocationData['elec_mediankwh_eco7'];
  }
  
  if(setting_gas == "total"){
     data_gas = retrofitCard_postcodeLocationData['gas_totalkwh'];
  } else if (setting_gas == "mean") {
     data_gas = retrofitCard_postcodeLocationData['gas_meankwh'];
  } else if (setting_gas == "median") {
     data_gas = retrofitCard_postcodeLocationData['gas_mediankwh'];
  }
  
  
  
  const labels = retrofitCard_postcodeLocationData['year'];
  const dataMeters = {
    labels: labels,
    datasets: [
      {
        label: 'Gas',
        data: retrofitCard_postcodeLocationData['gas_meters'],
        backgroundColor: '#2b8cbe',
        stack: 'Stack 0',
      },
      {
        label: 'Electric (all)',
        data: retrofitCard_postcodeLocationData['elec_meters_all'],
        backgroundColor: '#b30000',
        stack: 'Stack 1',
      },
      {
        label: 'Electric (Standard)',
        data: retrofitCard_postcodeLocationData['elec_meters_std'],
        backgroundColor: '#e34a33',
        stack: 'Stack 2',
      },
      {
        label: 'Electric (Economy 7)',
        data: retrofitCard_postcodeLocationData['elec_meters_eco7'],
        backgroundColor: '#fdcc8a',
        stack: 'Stack 2',
      }
    ]
  };
  
  
  const dataEmissions = {
    labels: labels,
      datasets: [
        {
          label: 'Gas',
          data: data_emissions_gas,
          borderColor: '#2b8cbe',
          backgroundColor: '#2b8cbe',
        },
        {
          label: 'Electricity',
          data: data_emissions_elec,
          borderColor: '#b30000',
          backgroundColor: '#b30000',
        }
      ]
    };
	
	const dataElectricity = {
    labels: labels,
      datasets: [
        {
          label: 'All meters',
          data: data_elec_all,
          borderColor: '#b30000',
          backgroundColor: '#b30000',
        },
        {
          label: 'Standard Meters',
          data: data_elec_std,
          borderColor: '#e34a33',
          backgroundColor: '#e34a33',
        },
        {
          label: 'Economy 7 Meters',
          data: data_elec_eco7,
          borderColor: '#fdcc8a',
          backgroundColor: '#fdcc8a',
        }
      ]
    };
	
	
	const dataGas = {
    labels: labels,
      datasets: [
        {
          label: 'All meters',
          data: data_gas,
          borderColor: '#2b8cbe',
          backgroundColor: '#2b8cbe',
        }
      ]
    };
	
	var metersctx = document.getElementById('meters-chart').getContext('2d');
	retrofitCard_metersChart = new Chart(metersctx, {
    type: 'bar',
      data: dataMeters,
      options: {
        responsive: true,
        interaction: {
          intersect: false,
        },
        scales: {
          x: {
            stacked: true,
            title: {
              display: true,
              text: 'Year'
            }
          },
          y: {
            stacked: true,
            title: {
              display: true,
              text: 'Meters'
            }
          }
        }
      }
  });
	
	var emissionsctx = document.getElementById('emissions-chart').getContext('2d');
	retrofitCard_emissionsChart = new Chart(emissionsctx, {
    type: 'line',
    data: dataEmissions,
    options: {
      responsive: true,
      scales: {
        y: {
          title: {
            display: true,
            text: 'Emissions kgCO2e'
          },
          beginAtZero: true
        },
        x: {
          title: {
            display: true,
            text: 'Year'
          }
        }
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    },
  });
  
  var gasctx = document.getElementById('gas-chart').getContext('2d');
	retrofitCard_gasChart = new Chart(gasctx, {
    type: 'line',
    data: dataGas,
    options: {
      responsive: true,
      scales: {
        y: {
          title: {
            display: true,
            text: 'Gas Consumption kWh'
          },
          beginAtZero: true
        },
        x: {
          title: {
            display: true,
            text: 'Year'
          }
        }
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    },
  });
	
	var electricityctx = document.getElementById('electricity-chart').getContext('2d');
	retrofitCard_electricityChart = new Chart(electricityctx, {
    type: 'line',
    data: dataElectricity,
    options: {
      responsive: true,
      scales: {
        y: {
          title: {
            display: true,
            text: 'Consumption kWh'
          },
          beginAtZero: true
        },
        x: {
          title: {
            display: true,
            text: 'Year'
          }
        }
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    },
  });
  
}

retrofitCard_makeChartLSOAEnergy = function(locationId){
  
  console.log("Make LSOA Energy Charts charts");
  // Access Chart
  // Destroy old chart
	if(retrofitCard_emissionsLSOAChart){
		retrofitCard_emissionsLSOAChart.destroy();
	}
	if(retrofitCard_gasLSOAChart){
		retrofitCard_gasLSOAChart.destroy();
	}
	if(retrofitCard_electricityLSOAChart){
		retrofitCard_electricityLSOAChart.destroy();
	}
  if(retrofitCard_metersLSOAChart){
		retrofitCard_metersLSOAChart.destroy();
	}
  if(retrofitCard_energybillsLSOAChart){
		retrofitCard_energybillsLSOAChart.destroy();
	}

  // Get Control Settings
  const setting_emissions = document.getElementById("select_emissionsLSOA").value;
	const setting_gas = document.getElementById("select_gasLSOA").value;
  const setting_electricity = document.getElementById("select_electricityLSOA").value;
  
  let data_emissions_gas;
  let data_emissions_elec;
  let data_elec_all;

  // Get data
  
  if(setting_emissions == "total"){
     data_emissions_gas = retrofitCard_lsoaEnergyData['total_gas_kgco2e'];
     data_emissions_elec = retrofitCard_lsoaEnergyData['total_elec_kgco2e'];
     data_emissions_other = retrofitCard_lsoaEnergyData['total_other_kgco2e'];
  } else if (setting_emissions == "mean") {
     data_emissions_gas = retrofitCard_lsoaEnergyData['mean_gas_kgco2e'];
     data_emissions_elec = retrofitCard_lsoaEnergyData['mean_elec_kgco2e'];
     data_emissions_other = retrofitCard_lsoaEnergyData['mean_other_kgco2e'];
  } else if (setting_emissions == "median") {
     data_emissions_gas = retrofitCard_lsoaEnergyData['median_gas_kgco2e'];
     data_emissions_elec = retrofitCard_lsoaEnergyData['median_elec_kgco2e'];
     data_emissions_other = retrofitCard_lsoaEnergyData['mean_other_kgco2e']; // Using mean for other as median not available
  }
  
  if(setting_electricity == "total"){
     data_elec_all = retrofitCard_lsoaEnergyData['total_elec_kwh'];
  } else if (setting_electricity == "mean") {
     data_elec_all = retrofitCard_lsoaEnergyData['mean_elec_kwh'];
  } else if (setting_electricity == "median") {
     data_elec_all = retrofitCard_lsoaEnergyData['median_elec_kwh'];
  }
  
  if(setting_gas == "total"){
     data_gas = retrofitCard_lsoaEnergyData['total_gas_kwh'];
  } else if (setting_gas == "mean") {
     data_gas = retrofitCard_lsoaEnergyData['mean_gas_kwh'];
  } else if (setting_gas == "median") {
     data_gas = retrofitCard_lsoaEnergyData['median_gas_kwh'];
  }
  
  
  
  const labels = retrofitCard_lsoaEnergyData.year;
  const dataMeters = {
    labels: labels,
    datasets: [
      {
        label: 'Gas',
        data: retrofitCard_lsoaEnergyData['meters_gas'],
        backgroundColor: '#2b8cbe',
        stack: 'Stack 0',
      },
      {
        label: 'Electric',
        data: retrofitCard_lsoaEnergyData['meters_elec'],
        backgroundColor: '#b30000',
        stack: 'Stack 1',
      }
    ]
  };
  
  
  const dataEmissions = {
    labels: labels,
      datasets: [
        {
          label: 'Gas',
          data: data_emissions_gas,
          borderColor: '#2b8cbe',
          backgroundColor: '#2b8cbe',
        },
        {
          label: 'Electricity',
          data: data_emissions_elec,
          borderColor: '#b30000',
          backgroundColor: '#b30000',
        },
        {
          label: 'Other',
          data: data_emissions_other,
          borderColor: '#008000',
          backgroundColor: '#008000',
        }
      ]
    };
	
	const dataElectricity = {
    labels: labels,
      datasets: [
        {
          label: 'Domestic Electricity',
          data: data_elec_all,
          borderColor: '#b30000',
          backgroundColor: '#b30000',
        }
      ]
    };
	
	
	const dataGas = {
    labels: labels,
      datasets: [
        {
          label: 'Domestic Gas',
          data: data_gas,
          borderColor: '#2b8cbe',
          backgroundColor: '#2b8cbe',
        }
      ]
    };
	
    const dataEnergyBills = {
    labels: labels,
      datasets: [
        {
          label: 'Gas',
          data: retrofitCard_lsoaEnergyData['gas_average_bill'],
          borderColor: '#2b8cbe',
          backgroundColor: '#2b8cbe',
        },
        {
          label: 'Electricity',
          data: retrofitCard_lsoaEnergyData['elec_average_bill'],
          borderColor: '#b30000',
          backgroundColor: '#b30000',
        },
        {
          label: 'Other',
          data: retrofitCard_lsoaEnergyData['otherheating_average_bill'],
          borderColor: '#008000',
          backgroundColor: '#008000',
        },
        {
          label: 'Total',
          data: retrofitCard_lsoaEnergyData['energy_average_bill'],
          borderColor: '#420144',
          backgroundColor: '#420144',
        }
      ]
    };

	var metersctx = document.getElementById('metersLSOA-chart').getContext('2d');
	retrofitCard_metersLSOAChart = new Chart(metersctx, {
    type: 'bar',
      data: dataMeters,
      options: {
        responsive: true,
        interaction: {
          intersect: false,
        },
        scales: {
          x: {
            stacked: true,
            title: {
              display: true,
              text: 'Year'
            }
          },
          y: {
            stacked: true,
            title: {
              display: true,
              text: 'Meters'
            }
          }
        }
      }
  });
	
	var emissionsctx = document.getElementById('emissionsLSOA-chart').getContext('2d');
	retrofitCard_emissionsLSOAChart = new Chart(emissionsctx, {
    type: 'line',
    data: dataEmissions,
    options: {
      responsive: true,
      scales: {
        y: {
          title: {
            display: true,
            text: 'Emissions kgCO2e'
          },
          beginAtZero: true
        },
        x: {
          title: {
            display: true,
            text: 'Year'
          }
        }
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    },
  });

  var energybillsctx = document.getElementById('energybillsLSOA-chart').getContext('2d');
	retrofitCard_energybillsLSOAChart = new Chart(energybillsctx, {
    type: 'line',
    data: dataEnergyBills,
    options: {
      responsive: true,
      scales: {
        y: {
          title: {
            display: true,
            text: 'Average Bill (£)'
          },
          beginAtZero: true
        },
        x: {
          title: {
            display: true,
            text: 'Year'
          }
        }
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    },
  });
  
  var gasctx = document.getElementById('gasLSOA-chart').getContext('2d');
	retrofitCard_gasLSOAChart = new Chart(gasctx, {
    type: 'line',
    data: dataGas,
    options: {
      responsive: true,
      scales: {
        y: {
          title: {
            display: true,
            text: 'Gas Consumption kWh'
          },
          beginAtZero: true
        },
        x: {
          title: {
            display: true,
            text: 'Year'
          }
        }
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    },
  });
	
	var electricityctx = document.getElementById('electricityLSOA-chart').getContext('2d');
	retrofitCard_electricityLSOAChart = new Chart(electricityctx, {
    type: 'line',
    data: dataElectricity,
    options: {
      responsive: true,
      scales: {
        y: {
          title: {
            display: true,
            text: 'Consumption kWh'
          },
          beginAtZero: true
        },
        x: {
          title: {
            display: true,
            text: 'Year'
          }
        }
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    },
  });
  
}


retrofitCard_makeChartPrices = function(){
  
  console.log("Make prices charts");
  
  // Destroy old charts
  if(retrofitCard_pricesChart){
    retrofitCard_pricesChart.destroy();
  }
  if(retrofitCard_transactionsChart){
    retrofitCard_transactionsChart.destroy();
  }
  
  // Prepare data for box and whisker chart (prices)
  // Using line chart to show median with range indicators
  const pricesData = {
    labels: retrofitCard_pricesLocationData.year,
    datasets: [
      {
        label: 'Maximum Price',
        data: retrofitCard_pricesLocationData.price_max,
        borderColor: '#c0c0c0',
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderDash: [5, 5],
        fill: false,
        pointRadius: 0,
        tension: 0.1,
        hidden: true
      },
      {
        label: 'Upper Quartile (Q3)',
        data: retrofitCard_pricesLocationData.price_75,
        borderColor: '#a8d5e8',
        backgroundColor: 'transparent',
        borderWidth: 1,
        fill: false,
        pointRadius: 0,
        tension: 0.1
      },
      {
        label: 'Median Price',
        data: retrofitCard_pricesLocationData.price_median,
        borderColor: '#2b8cbe',
        backgroundColor: '#2b8cbe',
        borderWidth: 2,
        fill: false,
        pointRadius: 4,
        pointBackgroundColor: '#2b8cbe',
        tension: 0.1
      },
      {
        label: 'Lower Quartile (Q1)',
        data: retrofitCard_pricesLocationData.price_25,
        borderColor: '#a8d5e8',
        backgroundColor: 'transparent',
        borderWidth: 1,
        fill: false,
        pointRadius: 0,
        tension: 0.1
      },
      {
        label: 'Minimum Price',
        data: retrofitCard_pricesLocationData.price_min,
        borderColor: '#c0c0c0',
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderDash: [5, 5],
        fill: false,
        pointRadius: 0,
        tension: 0.1
      }
    ]
  };
  
  // Create price chart
  var pricesctx = document.getElementById('prices-chart').getContext('2d');
  retrofitCard_pricesChart = new Chart(pricesctx, {
    type: 'line',
    data: pricesData,
    options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
        y: {
          title: {
            display: true,
            text: 'Price (£)'
          },
          beginAtZero: false
        },
        x: {
          title: {
            display: true,
            text: 'Year'
          }
        }
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    }
  });
  
  // Prepare data for transactions bar chart
  const transactionsData = {
    labels: retrofitCard_pricesLocationData.year,
    datasets: [{
      label: 'Number of Transactions',
      data: retrofitCard_pricesLocationData.transactions,
      backgroundColor: '#d7191c',
      borderColor: '#d7191c',
      borderWidth: 1
    }]
  };
  
  // Create transactions chart
  var transactionsctx = document.getElementById('transactions-chart').getContext('2d');
  retrofitCard_transactionsChart = new Chart(transactionsctx, {
    type: 'bar',
    data: transactionsData,
    options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
        y: {
          title: {
            display: true,
            text: 'Number of Transactions'
          },
          beginAtZero: true
        },
        x: {
          title: {
            display: true,
            text: 'Year'
          }
        }
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    }
  });
  
}

retrofitCard_makeChartLSOA = function(){
  
  console.log("Make LSOA charts");
  
  // EPC chart
  
  epcratingData = [
  retrofitCard_lsoaLocationData.epc_A,
  retrofitCard_lsoaLocationData.epc_B,
  retrofitCard_lsoaLocationData.epc_C,
  retrofitCard_lsoaLocationData.epc_D,
  retrofitCard_lsoaLocationData.epc_E,
  retrofitCard_lsoaLocationData.epc_F,
  retrofitCard_lsoaLocationData.epc_G,
  retrofitCard_lsoaLocationData.epc_o,
  ];
 
	retrofitCard_epcratingChart = retrofitCard_makePieChart(retrofitCard_epcratingChart,'epcrating-chart','EPC rating',
  epcratingData,
  ['#0e7e58','#2aa45b','#8cbc42','#f6cc15','#f2a867','#f17e23','#e31d3e','#333333'],
  ['A','B','C','D','E','F','G','Other']);
  
  // Building type
  
  buildingtypeData = [
  retrofitCard_lsoaLocationData.type_house_detached,
  retrofitCard_lsoaLocationData.type_house_semi,
  retrofitCard_lsoaLocationData.type_house_midterrace,
  retrofitCard_lsoaLocationData.type_house_endterrace,
  retrofitCard_lsoaLocationData.type_flat,
  retrofitCard_lsoaLocationData.type_bungalow_detached,
  retrofitCard_lsoaLocationData.type_bungalow_semi,
  retrofitCard_lsoaLocationData.type_bungalow_midterrace,
  retrofitCard_lsoaLocationData.type_bungalow_endterrace,
  retrofitCard_lsoaLocationData.type_maisonette,
  retrofitCard_lsoaLocationData.type_parkhome,
  retrofitCard_lsoaLocationData.type_other,
  ];
 
	retrofitCard_buildingtypeChart = retrofitCard_makePieChart(retrofitCard_buildingtypeChart,'buildingtype-chart','Building type',
  buildingtypeData,
  ['#c2e699','#78c679','#31a354','#006837','#e31a1c','#fbb4b9','#7a0177','#f768a1','#c51b8a','#1f78b4','#fa7c00','#c0c0c0'],
  ['Detached house','Semi-detached house','Mid-terrace house','End-terrace house',
			'Flat','Detached bungalow','Semi-detached bungalow','Mid-terrace bungalow',
			'End-terrace bungalow','Maisonette','Park home','Other']);
	
  // Tenure type
  
  tenureData = [
  retrofitCard_lsoaLocationData.tenure_owner,
  retrofitCard_lsoaLocationData.tenure_privaterent,
  retrofitCard_lsoaLocationData.tenure_socialrent,
  retrofitCard_lsoaLocationData.tenure_unknown
  ];
 
  retrofitCard_tenureChart = retrofitCard_makePieChart(retrofitCard_tenureChart,'tenure-chart','Tenure',
  tenureData,
  ['#c2e699','#78c679','#31a354','#c0c0c0'],
  ['Owner','Private rent','Social rent','Unknown']);
  
  // Age

  ageData = [
  retrofitCard_lsoaLocationData.age_pre1900,
  retrofitCard_lsoaLocationData.age_19001929,
  retrofitCard_lsoaLocationData.age_19301949,
  retrofitCard_lsoaLocationData.age_19501966,
  retrofitCard_lsoaLocationData.age_19671975,
  retrofitCard_lsoaLocationData.age_19761982,
  retrofitCard_lsoaLocationData.age_19831990,
  retrofitCard_lsoaLocationData.age_19911995,
  retrofitCard_lsoaLocationData.age_19962002,
  retrofitCard_lsoaLocationData.age_20032006,
  retrofitCard_lsoaLocationData.age_20072011,
  retrofitCard_lsoaLocationData.age_20122021,
  retrofitCard_lsoaLocationData.age_post2022,
  retrofitCard_lsoaLocationData.age_unknown,
  ];
 
  retrofitCard_ageChart = retrofitCard_makePieChart(retrofitCard_ageChart,'age-chart','Building Age',
  ageData,
  ['#9e0142','#d53e4f','#f46d43','#fdae61','#fee08b','#ffffbf','#e6f598','#abdda4','#66c2a5','#3288bd','#5e4fa2','#934fa2','#c259a7','#c0c0c0'],
  ['pre-1900','1900-1929','1930-1949','1950-1966','1967-1975','1976-1982',
  '1983-1990','1991-1995','1996-2002','2003-2006','2007-2011','2012-2021','post-2022','Unknown']);
  
  
  // floor
  // TODO: Data looks wrong
  
  floorData = [
    retrofitCard_lsoaLocationData.floor_verygood,
    retrofitCard_lsoaLocationData.floor_good,
    retrofitCard_lsoaLocationData.floor_average,
    retrofitCard_lsoaLocationData.floor_poor,
    retrofitCard_lsoaLocationData.floor_verypoor,
    retrofitCard_lsoaLocationData.floor_below,
    retrofitCard_lsoaLocationData.floor_other,
  ];
 
  retrofitCard_floorChart = retrofitCard_makePieChart(retrofitCard_floorChart,'floor-chart','',
  floorData,
  ['#2c7bb6','#abd9e9','#ffffbf','#fdae61','#d7191c','#8b21b5','#c0c0c0'],
  ['Very Good','Good','Average','Poor','Very Poor','Dwelling Below','Other']);
  
  // floord
  
  floordData = [
    retrofitCard_lsoaLocationData.floord_soliduninsulated,
    retrofitCard_lsoaLocationData.floord_solidinsulated,
    retrofitCard_lsoaLocationData.floord_solidlimitedinsulated,
    retrofitCard_lsoaLocationData.floord_suspendeduninsulated,
    retrofitCard_lsoaLocationData.floord_suspendedinsualted,
    retrofitCard_lsoaLocationData.floord_suspendedlimitedinsulated,
    retrofitCard_lsoaLocationData.floord_below,
    retrofitCard_lsoaLocationData.floor_other
  ];
 
  retrofitCard_floordChart = retrofitCard_makePieChart(retrofitCard_floordChart,'floord-chart','',
  floordData,
  ['#b2e2e2','#66c2a4','#238b45','#fde0ef', '#e9a3c9', '#c51b7d','#225ea8','#c0c0c0'],
  ['Solid uninsulated','Solid insulated','Solid limited insulation','Suspended uninsulated','Suspended insualted','Suspended limited insulation','Dwelling Below','Other']);
  
  // window
  
  windowData = [
    retrofitCard_lsoaLocationData.window_verygood,
    retrofitCard_lsoaLocationData.window_good,
    retrofitCard_lsoaLocationData.window_average,
    retrofitCard_lsoaLocationData.window_poor,
    retrofitCard_lsoaLocationData.window_verypoor,
    retrofitCard_lsoaLocationData.window_other
  ];
 
  retrofitCard_windowChart = retrofitCard_makePieChart(retrofitCard_windowChart,'window-chart','',
  windowData,
  ['#2c7bb6','#abd9e9','#ffffbf','#fdae61','#d7191c','#c0c0c0'],
  ['Very Good','Good','Average','Poor','Very Poor','Other']);
  
  // water
  
  waterData = [
    retrofitCard_lsoaLocationData.water_verygood,
    retrofitCard_lsoaLocationData.water_good,
    retrofitCard_lsoaLocationData.water_average,
    retrofitCard_lsoaLocationData.water_poor,
    retrofitCard_lsoaLocationData.water_verypoor,
    retrofitCard_lsoaLocationData.water_other,

  ];
 
  retrofitCard_waterChart = retrofitCard_makePieChart(retrofitCard_waterChart,'water-chart','',
  waterData,
  ['#2c7bb6','#abd9e9','#ffffbf','#fdae61','#d7191c','#c0c0c0'],
  ['Very Good','Good','Average','Poor','Very Poor','Other']);
  
  // waterd
  
  waterdData = [
    retrofitCard_lsoaLocationData.waterd_mainsystem,
    retrofitCard_lsoaLocationData.waterd_immersion,
    retrofitCard_lsoaLocationData.waterd_community,
    retrofitCard_lsoaLocationData.waterd_instantaneous,
    retrofitCard_lsoaLocationData.waterd_gasmultipoint,
    retrofitCard_lsoaLocationData.walld_other
  ];
 
  retrofitCard_waterdChart = retrofitCard_makePieChart(retrofitCard_waterdChart,'waterd-chart','',
  waterdData,
  ['#e41a1c','#377eb8','#4daf4a','#984ea3','#ffff33','#c0c0c0'],
  ['Main system','Immersion heater','Community system','Instantaneous water heater','Gas multipoint','Other']);
  
  // glazing
  
  glazingData = [
    retrofitCard_lsoaLocationData.glazing_single,
    retrofitCard_lsoaLocationData.glazing_double,
    retrofitCard_lsoaLocationData.glazing_triple,
    retrofitCard_lsoaLocationData.glazing_secondary,
    retrofitCard_lsoaLocationData.glazing_unknown
  ];
 
  retrofitCard_glazingChart = retrofitCard_makePieChart(retrofitCard_glazingChart,'glazing-chart','',
  glazingData,
  ['#e41a1c','#377eb8','#4daf4a','#984ea3','#c0c0c0'],
  ['single','double','triple','secondary','unknown']);
  
  // wall
  
  wallData = [
    retrofitCard_lsoaLocationData.wall_verygood,
    retrofitCard_lsoaLocationData.wall_good,
    retrofitCard_lsoaLocationData.wall_average,
    retrofitCard_lsoaLocationData.wall_poor,
    retrofitCard_lsoaLocationData.wall_verypoor,
    retrofitCard_lsoaLocationData.wall_other

  ];
 
  retrofitCard_wallChart = retrofitCard_makePieChart(retrofitCard_wallChart,'wall-chart','',
  wallData,
  ['#2c7bb6','#abd9e9','#ffffbf','#fdae61','#d7191c','#c0c0c0'],
  ['Very Good','Good','Average','Poor','Very Poor','Other']);
  
  // walld
  
  walldData = [
    retrofitCard_lsoaLocationData.walld_cavity,
    retrofitCard_lsoaLocationData.walld_solid,
    retrofitCard_lsoaLocationData.walld_timber,
    retrofitCard_lsoaLocationData.walld_sandlimestone,
    retrofitCard_lsoaLocationData.walld_granitewhinstine,
    retrofitCard_lsoaLocationData.walld_system,
    retrofitCard_lsoaLocationData.walld_other
  ];
 
  retrofitCard_walldChart = retrofitCard_makePieChart(retrofitCard_walldChart,'walld-chart','',
  walldData,
  ['#e41a1c','#377eb8','#4daf4a','#984ea3','#ff7f00','#ffff33','#c0c0c0'],
  ['Cavity','Solid','Timber','Sand/limestone','Granite/whinstine','System built','Other']);
  
  // roof
  
  roofData = [
    retrofitCard_lsoaLocationData.roof_verygood,
    retrofitCard_lsoaLocationData.roof_good,
    retrofitCard_lsoaLocationData.roof_average,
    retrofitCard_lsoaLocationData.roof_poor,
    retrofitCard_lsoaLocationData.roof_verypoor,
    retrofitCard_lsoaLocationData.roof_above,
    retrofitCard_lsoaLocationData.roof_other

  ];
 
  retrofitCard_roofChart = retrofitCard_makePieChart(retrofitCard_roofChart,'roof-chart','',
  roofData,
  ['#2c7bb6','#abd9e9','#ffffbf','#fdae61','#d7191c','#8b21b5','#c0c0c0'],
  ['Very Good','Good','Average','Poor','Very Poor','Dwelling Above','Other']);
  
  // roofd
  
  roofdData = [
    retrofitCard_lsoaLocationData.roofd_pitched,
    retrofitCard_lsoaLocationData.roofd_flat,
    retrofitCard_lsoaLocationData.roofd_room,
    retrofitCard_lsoaLocationData.roofd_thatched,
    retrofitCard_lsoaLocationData.roofd_above,
    retrofitCard_lsoaLocationData.roofd_other
  ];
 
  retrofitCard_roofdChart = retrofitCard_makePieChart(retrofitCard_roofdChart,'roofd-chart','',
  roofdData,
  ['#e41a1c','#377eb8','#4daf4a','#ffff33','#8b21b5','#c0c0c0'],
  ['Pitched','Flat roof','Room in roof','Thatched','Dwelling Above','Other']);
  
  // mainheatdesc
  
  mainheatdescData = [
    retrofitCard_lsoaLocationData.mainheatdesc_gasboiler,
    retrofitCard_lsoaLocationData.mainheatdesc_oilboiler,
    retrofitCard_lsoaLocationData.mainheatdesc_storageheater,
    retrofitCard_lsoaLocationData.mainheatdesc_portableheater,
    retrofitCard_lsoaLocationData.mainheatdesc_roomheater,
    retrofitCard_lsoaLocationData.mainheatdesc_heatpump,
    retrofitCard_lsoaLocationData.mainheatdesc_community,
    retrofitCard_lsoaLocationData.mainheatdesc_other
  ];
 
  retrofitCard_mainheatdescChart = retrofitCard_makePieChart(retrofitCard_mainheatdescChart,'mainheatdesc-chart','',
  mainheatdescData,
  ['#e41a1c','#377eb8','#4daf4a','#984ea3','#ff7f00','#ffff33','#a65628','#c0c0c0'],
  ['Gas boiler','Oil boiler','Storage heater','Portable heater','Room heaters','Heat pump','Community','Other']);
  
  // mainheat
  
  mainheatData = [
    retrofitCard_lsoaLocationData.mainheat_verygood,
    retrofitCard_lsoaLocationData.mainheat_good,
    retrofitCard_lsoaLocationData.mainheat_average,
    retrofitCard_lsoaLocationData.mainheat_poor,
    retrofitCard_lsoaLocationData.mainheat_verypoor,
    retrofitCard_lsoaLocationData.mainheat_other

  ];
 
  retrofitCard_mainheatChart = retrofitCard_makePieChart(retrofitCard_mainheatChart,'mainheat-chart','',
  roofdData,
  ['#2c7bb6','#abd9e9','#ffffbf','#fdae61','#d7191c','#c0c0c0'],
  ['Very Good','Good','Average','Poor','Very Poor','Other']);
  
  
  // mainfuel
  
  mainfuelData = [
    retrofitCard_lsoaLocationData.mainfuel_mainsgas,
    retrofitCard_lsoaLocationData.mainfuel_electric,
    retrofitCard_lsoaLocationData.mainfuel_oil,
    retrofitCard_lsoaLocationData.mainfuel_coal,
    retrofitCard_lsoaLocationData.mainfuel_lpg,
    retrofitCard_lsoaLocationData.mainfuel_biomass,
    retrofitCard_lsoaLocationData.mainfuel_dualfuel
  ];
 
  retrofitCard_mainfuelChart = retrofitCard_makePieChart(retrofitCard_mainfuelChart,'mainfuel-chart','',
  mainfuelData,
  ['#e41a1c','#377eb8','#4daf4a','#984ea3','#ff7f00','#ffff33','#a65628'],
  ['Mains gas','Electric','Oil','Coal','LPG','Biomass','Dual fuel']);
  
  // mainheatcontrol
  
  mainheatcontrolData = [
    retrofitCard_lsoaLocationData.mainheatcontrol_verygood,
    retrofitCard_lsoaLocationData.mainheatcontrol_good,
    retrofitCard_lsoaLocationData.mainheatcontrol_average,
    retrofitCard_lsoaLocationData.mainheatcontrol_poor,
    retrofitCard_lsoaLocationData.mainheatcontrol_verypoor,
    retrofitCard_lsoaLocationData.mainheatcontrol_other

  ];
 
  retrofitCard_mainheatcontrolChart = retrofitCard_makePieChart(retrofitCard_mainheatcontrolChart,'mainheatcontrol-chart','',
  mainheatcontrolData,
  ['#2c7bb6','#abd9e9','#ffffbf','#fdae61','#d7191c','#c0c0c0'],
  ['Very Good','Good','Average','Poor','Very Poor','Other']);
  
  // controld
  
  controldData = [
    retrofitCard_lsoaLocationData.controld_progthermtrvs,
    retrofitCard_lsoaLocationData.controld_progtherm,
    retrofitCard_lsoaLocationData.controld_progtrvsbypass,
    retrofitCard_lsoaLocationData.controld_pzones,
    retrofitCard_lsoaLocationData.controld_other
  ];
 
  retrofitCard_controldChart = retrofitCard_makePieChart(retrofitCard_controldChart,'controld-chart','',
  controldData,
  ['#e41a1c','#377eb8','#4daf4a','#984ea3','#c0c0c0'],
  ['progammer, thermostats & trvs','progammer, thermostats','progammer,trvs & bypass','zones','Other']);
  
  // light
  
  lightData = [
    retrofitCard_lsoaLocationData.light_verygood,
    retrofitCard_lsoaLocationData.light_good,
    retrofitCard_lsoaLocationData.light_average,
    retrofitCard_lsoaLocationData.light_poor,
    retrofitCard_lsoaLocationData.light_verypoor,
    retrofitCard_lsoaLocationData.light_other
  ];
 
  retrofitCard_lightChart = retrofitCard_makePieChart(retrofitCard_lightChart,'light-chart','',
  lightData,
  ['#2c7bb6','#abd9e9','#ffffbf','#fdae61','#d7191c','#c0c0c0'],
  ['Very Good','Good','Average','Poor','Very Poor','Other']);
  
  // solarpv
  
  solarpvData = [
    retrofitCard_lsoaLocationData.solarpv_yes,
    retrofitCard_lsoaLocationData.solarpv_no
  ];
 
  retrofitCard_solarpvChart = retrofitCard_makePieChart(retrofitCard_solarpvChart,'solarpv-chart','',
  solarpvData,
  ['#2c7bb6','#d7191c'],
  ['Yes','No']);
  
  // solarthermal
  
  solarthermalData = [
    retrofitCard_lsoaLocationData.solarthermal_yes,
    retrofitCard_lsoaLocationData.solarthermal_no
  ];
 
  retrofitCard_solarthermalChart = retrofitCard_makePieChart(retrofitCard_solarthermalChart,'solarthermal-chart','',
  solarthermalData,
  ['#2c7bb6','#d7191c'],
  ['Yes','No']);
  
  
  
}

retrofitCard_makePieChart = function(chartVar, name, label, data, colours, labels){
  if (chartVar) {
    chartVar.destroy();
  }
  
  chartVar = new Chart(document.getElementById(name).getContext('2d'), {
		type: 'pie',
		data: {
			datasets: [{
				label: label,
				data: data,
				backgroundColor: colours
				
			}],
			
			labels: labels
		},
		options: {
			responsive: true,
			maintainAspectRatio: false
		}
	});
	
	return chartVar;
}




// Function to switch chart description tabs (Overview / Policy / Methods)
// Scoped to the chart's own .chart-description-tabs container, so multiple
// chart tab groups operate independently.
switchChartTab = function (evt, tabName) {
  var tabsContainer = evt.currentTarget.closest('.chart-description-tabs');
  tabsContainer.querySelectorAll('.chart-description-tab-content').forEach(function (content) {
    content.classList.remove('active');
    content.style.display = 'none';
  });
  tabsContainer.querySelectorAll('.chart-tab-btn').forEach(function (button) {
    button.classList.remove('active');
  });
  var selectedContent = document.getElementById(tabName);
  if (selectedContent) {
    selectedContent.classList.add('active');
    selectedContent.style.display = 'block';
    evt.currentTarget.classList.add('active');
  }
};


// Registration: the report page calls window.reportCards.retrofit.load(locationId)
window.reportCards = window.reportCards || {};
window.reportCards.retrofit = {
  load: function (locationId) { return retrofitCard_manageCharts(locationId, 'zones'); },
  defaultOpen: 'retrofit-defaultOpen'
};
