// GENERATED FILE - do not edit by hand.
// Regenerated by scratchpad/make_report_cards.py from transport/ui.js + transport/index.html.
// Report-card module for the transport tool: renders every chart from the tool's
// zones report modal into the transport-card.html fragment on a report page.
// Data endpoints can be redirected (e.g. to area-level aggregates) by setting
// window.REPORT_CARD_ENDPOINTS = { '<default path>': <override> } where the
// override is either '<replacement path>' (another pbcc-data folder) or
// { bin: '<dataset>' } (a capBin single-binary dataset, which the page must
// have capBin.register()ed - see reports/la-report.js).

function transportCard_fetchJSON(url) {
  // 'bin:<dataset>/<id>.json' pseudo-URLs come from the { bin: ... } override
  // form of REPORT_CARD_ENDPOINTS and are served by capBin range requests.
  if (url.lastIndexOf('bin:', 0) === 0) {
    var rest = url.slice(4);
    var slash = rest.indexOf('/');
    return capBin.fetchRecord(rest.slice(0, slash), rest.slice(slash + 1).replace(/\.json$/, ''));
  }
  return fetch(url).then(function (r) {
    if (!r.ok) { throw new Error('HTTP ' + r.status); }
    return r.json();
  });
}

function transportCard_endpoint(path) {
  var override = (window.REPORT_CARD_ENDPOINTS || {})[path];
  if (override && typeof override === 'object' && override.bin) { return 'bin:' + override.bin + '/'; }
  return 'https://pbcc.blob.core.windows.net/pbcc-data/' + (override || path);
}

// Tab switcher scoped to this card's own fragment, so multiple tool cards can
// coexist on one report page without cross-talk.
function transportCard_modalTab(evt, tabName) {
  var root = evt.currentTarget.closest('.report-fullcard');
  if (!root) { return; }
  root.querySelectorAll('.tabcontent').forEach(function (el) { el.style.display = 'none'; });
  root.querySelectorAll('.tablinks').forEach(function (el) { el.className = el.className.replace(' active', ''); });
  var target = root.querySelector('#' + tabName);
  if (target) { target.style.display = 'block'; }
  evt.currentTarget.className += ' active';
}

// Local Chart Mangement
var transportCard_accessChart;
var transportCard_frequencyChart;
var transportCard_privateVehicleBodyChart;
var transportCard_privateVehicleFuelChart;
var transportCard_companyVehicleBodyChart;
var transportCard_companyVehicleFuelChart;
var transportCard_vehiclePPChart;
var transportCard_accessLocationData = {};
var transportCard_frequencyLocationData = {};
var transportCard_vehicleLocationData = {};

// The bands the accessibility scatter can be drawn at. The two axes must
// always come from the SAME band - a 30-minute isochrone and a 3-mile circle
// describe different journeys, so plotting one against the other would compare
// two unrelated catchments. Keeping the pair in one object, selected by one
// drop-down, makes a mismatched pair impossible to produce.
// `value` matches the <option value> in the report card markup and the numeric
// suffix of the access_*/proximity_* fields in the access bin.
const transportCard_ACCESS_BANDS = [
	{ value: '15', minutes: 15, miles: '0.75' },
	{ value: '30', minutes: 30, miles: '1.5' },
	{ value: '45', minutes: 45, miles: '2.25' },
	{ value: '60', minutes: 60, miles: '3' }
];
const transportCard_ACCESS_BAND_DEFAULT = '30';

// Resolve the drop-down to a band, falling back to the default if the control
// is missing (report cards render the fragment lazily) or holds a stale value
function transportCard_getAccessBand () {
	const select = document.getElementById('access-band');
	const wanted = (select ? select.value : transportCard_ACCESS_BAND_DEFAULT);
	return transportCard_ACCESS_BANDS.find(b => b.value === wanted) ||
		transportCard_ACCESS_BANDS.find(b => b.value === transportCard_ACCESS_BAND_DEFAULT);
}

// Show or hide the whole Accessibility & Proximity section, swapping in a
// short explanation in its place. Mirrors voaSetAvailable() in retrofit/ui.js,
// which does the same for the England-and-Wales-only dwelling stock charts.
//
// The analysis is built from the ONS Travel Area Isochrones around 2021 Output
// Area centroids and straight-line buffers around 2021 LSOA population-weighted
// centroids, both of which are published for England and Wales only, so the
// access bin holds no record at all for a Scottish Data Zone and fetchRecord()
// rejects. That is the expected outcome, not a failure, so say why rather than
// leaving an empty chart and an empty table on screen.
function transportCard_accessSetAvailable (available, locationId)
{
	const content = document.getElementById('access-content');
	if (content) { content.style.display = (available ? 'block' : 'none'); }

	const note = document.getElementById('access-nodata');
	if (!note) { return; }
	note.style.display = (available ? 'none' : 'block');
	if (available) { return; }

	// Scottish zone codes start with S. Anything else reaching this branch is a
	// genuine lookup failure, so don't blame the geography for it.
	const isScotland = (typeof locationId === 'string' && locationId.charAt(0) === 'S');
	note.innerHTML = (isScotland
		? 'Accessibility and proximity scores are not available for Scotland. They are built from the ' +
		  'ONS travel area isochrones and population-weighted centroids, which are published for ' +
		  'England and Wales only, and there is no equivalent Scottish dataset. Every other tab on ' +
		  'this report card does cover Scotland.'
		: 'Accessibility and proximity scores are not available for this area.');
}


transportCard_manageCharts = function (locationId) {
  // England and Wales only: a Scottish zone has no record here at all, so this
  // rejects and the whole section is replaced by a note (see
  // transportCard_accessSetAvailable). Expected outcome, not an error.
  const p1 = transportCard_fetchJSON(transportCard_endpoint('Access/') + locationId + '.json')
    .then(function (accessData) {
      transportCard_accessLocationData = accessData;
      transportCard_accessSetAvailable(true, locationId);
      transportCard_makeChartAccess();
      transportCard_makeTableAccess();
    })
    .catch(function (error) {
      transportCard_accessLocationData = {};
      if (transportCard_accessChart) { transportCard_accessChart.destroy(); transportCard_accessChart = undefined; }
      const table = document.getElementById('access-table');
      if (table) { table.innerHTML = ''; }
      transportCard_accessSetAvailable(false, locationId);
      console.log(error);
    });

  const p2 = transportCard_fetchJSON(transportCard_endpoint('PTfrequency/v2/') + locationId + '.json')
    .then(function (frequencyData) {
      transportCard_frequencyLocationData = frequencyData;
      transportCard_makeChartFrequency();
    })
    .catch(function (error) {
      console.warn('Failed to get frequnecy data for this location, or to process it correctly. Please try refreshing the page.');
      console.log(error);
    });

  const p3 = transportCard_fetchJSON(transportCard_endpoint('vehicle_summary/v1/') + locationId + '.json')
    .then(function (vehicleData) {
      transportCard_vehicleLocationData = vehicleData;
      transportCard_makeChartVehicles();
    })
    .catch(function (error) {
      console.warn('Failed to get vehicle data for this location, or to process it correctly. Please try refreshing the page.');
      console.log(error);
    });

  // Return a promise that resolves once both fetches have settled
  return Promise.all([p1, p2, p3]);
};


transportCard_makeChartAccess = function(){

  // Guard: do nothing until access data has loaded
  if (!transportCard_accessLocationData || !transportCard_accessLocationData['categoryname']) { return; }

  // Access Chart
  // Destroy old chart
	if(transportCard_accessChart){
		transportCard_accessChart.destroy();
	}

  // Bind the band drop-down the first time we draw. Done here rather than on
  // page load because the report cards inject this markup lazily; the guard
  // stops a second listener being added on the next zone click.
  const bandSelect = document.getElementById('access-band');
  if (bandSelect && !bandSelect.dataset.bound) {
    bandSelect.dataset.bound = 'true';
    bandSelect.addEventListener('change', function () { transportCard_makeChartAccess(); });
  }

  // Get data muliple datasets for each category. Both axes come from the same
  // band (see transportCard_ACCESS_BANDS) so the scatter compares like with like.
  const band = transportCard_getAccessBand();

  const category = transportCard_accessLocationData["categoryname"];
  const datax = transportCard_accessLocationData["proximity_" + band.value];
	const datay = transportCard_accessLocationData["access_" + band.value];
	const labels = transportCard_accessLocationData["classname"];
	//const data  = datax.map((xVal, index) => ({ x: xVal, y: datay[index] }));
	
	
	// Create an object to store data for each category
  const categoryData = {};
  for (let i = 0; i < category.length; i++) {
    const cat = category[i];
    if (!categoryData[cat]) {
      categoryData[cat] = [];
    }
    categoryData[cat].push({ x: datax[i], y: datay[i] });
  }
  
  const lableData = {};
  for (let i = 0; i < category.length; i++) {
    const cat = category[i];
    if (!lableData[cat]) {
      lableData[cat] = [];
    }
    //lableData[cat].push({ label: labels[i] });
    lableData[cat].push([labels[i]]);
  }
  
  // Create the datasets object
  const data = {
    datasets: Object.keys(categoryData).map((cat) => ({
      backgroundColor: '#00000',
      borderColor: '#00000',
      label: cat,
      labels: lableData[cat],
      data: categoryData[cat],
    })),
  };
  
  // Add colours
  const colours = ['#FF5733','#4CAF50','#2196F3','#FFC107','#E91E63','#9C27B0',
                  '#FF9800','#00BCD4','#8BC34A','#673AB7','#F44336','#3F51B5',
                  '#FFEB3B','#009688','#FF5722','#607D8B','#CDDC39','#795548',
                  '#FFCDD2','#9E9E9E','#FF9800','#FFC107','#FFEB3B','#4CAF50',
                  '#03A9F4','#FF4081','#8BC34A','#9C27B0','#FF5252','#00BCD4',
                  '#FF5722','#607D8B','#CDDC39','#795548','#FFCDD2','#9E9E9E',
                  '#FF9800','#FFC107','#FFEB3B','#4CAF50','#03A9F4','#FF4081'];

  for (let i = 0; i < data.datasets.length; i++) {
    data.datasets[i].borderColor = colours[i]
    data.datasets[i].backgroundColor = colours[i]
  }                
  
  var accessctx = document.getElementById('access-chart').getContext('2d');
	transportCard_accessChart = new Chart(accessctx, {
    type: 'scatter',
    data: {
      datasets: data.datasets
    },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
        x: {
          min: -3,
          max: 3,
          title: {
            display: true,
            text: 'Proximity: services within ' + band.miles + ' miles (SD from GB average)'
          }
        },
        y: {
          min: -3,
          max: 3,
          title: {
            display: true,
            text: 'Accessibility: services within ' + band.minutes + ' minutes (SD from GB average)'
          }
        },
      },
      plugins: {
        tooltip: {
            callbacks: {
                label: function(ctx) {
                    let label = ctx.dataset.labels[ctx.dataIndex];
                    label += " (" + ctx.parsed.x + ", " + ctx.parsed.y + ")";
                    return label;
                }
            }
        },
        legend: {
          position: 'top',
          display: true,
          labels: {
                  font: {
                      size: 10
                  }
          }
        }
      }
    }
  });
	
  
}


transportCard_makeTableAccess = function(){

    // Guard: do nothing until access data has loaded
    if (!transportCard_accessLocationData || !transportCard_accessLocationData['categoryname']) { return; }

    const tab = document.getElementById('access-table');
    tab.innerHTML = ''

    const labels = transportCard_accessLocationData["classname"];
    const category = transportCard_accessLocationData["categoryname"];
    const access_15 = transportCard_accessLocationData["access_15"];
    const access_30 = transportCard_accessLocationData["access_30"];
    const access_45 = transportCard_accessLocationData["access_45"];
    const access_60 = transportCard_accessLocationData["access_60"];
    const proximity_15 = transportCard_accessLocationData["proximity_15"];
    const proximity_30 = transportCard_accessLocationData["proximity_30"];
    const proximity_45 = transportCard_accessLocationData["proximity_45"];
    const proximity_60 = transportCard_accessLocationData["proximity_60"];
  

// Group data by category
const groupedData = {};
for (let i = 0; i < labels.length; i++) {
    const group = category[i];
    if (!groupedData[group]) {
        groupedData[group] = [];
    }
    groupedData[group].push(i);
}

// Create tables for each group
for (const group in groupedData) {
    const groupIndices = groupedData[group];
    const groupTable = document.createElement('table');
    groupTable.innerHTML = `
        <tr>
            <th colspan="9">${group}</th>
        </tr>
        <tr>
            <th>Type</th>
            <th style="width:42px;">15<br>min</th>
            <th style="width:42px;">30<br>min</th>
            <th style="width:42px;">45<br>min</th>
            <th style="width:42px;">60<br>min</th>
            <th style="width:42px;">0.75<br>mile</th>
            <th style="width:42px;">1.5<br>mile</th>
            <th style="width:42px;">2.25<br>mile</th>
            <th style="width:42px;">3<br>mile</th>
        </tr>
        ${groupIndices.map(i => `
            <tr>
                <td>${labels[i]}</td>
                <td>${access_15[i]}</td>
                <td>${access_30[i]}</td>
                <td>${access_45[i]}</td>
                <td>${access_60[i]}</td>
                <td>${proximity_15[i]}</td>
                <td>${proximity_30[i]}</td>
                <td>${proximity_45[i]}</td>
                <td>${proximity_60[i]}</td>
            </tr>
        `).join('')}
    `;
    tab.appendChild(groupTable);
}

const cells = tab.getElementsByTagName('td');

  for (let cell of cells) {
    const value = parseFloat(cell.textContent);
    if (value == -3) {
      cell.classList.add('insufficient');
      cell.textContent = 'Insf'
    } else if (value < -1.5) {
      cell.classList.add('very-poor');
    } else if (value < -1 & value >= -1.5 ) {
      cell.classList.add('poor');
    } else if (value < -0.3 & value >= -1 ) {
      cell.classList.add('below-average');
    } else if (value < 0.3 & value >= -0.3 ) {
      cell.classList.add('average');
    } else if (value < 1 & value >= 0.3 ) {
      cell.classList.add('above-average');
    } else if (value < 1.5 & value >= 1 ) {
      cell.classList.add('good');
    } else if (value > 1.5) {
      cell.classList.add('very-good');
    }
  }
  
  
  
}

transportCard_makeChartFrequency = function(){

  // Guard: do nothing until frequency data has loaded
  if (!transportCard_frequencyLocationData || !transportCard_frequencyLocationData['year']) { return; }

  // Access Chart
  // Destroy old chart
	if(transportCard_frequencyChart){
		transportCard_frequencyChart.destroy();
	}
	
	md = document.getElementById("select_mode").value;
	day = document.getElementById("select_day").value;
  
  // Get data muliple datasets for each category
  
  
  const MorningPeak = transportCard_frequencyLocationData[day + '_MorningPeak_' + md];
  const Midday = transportCard_frequencyLocationData[day + '_Midday_' + md];
	const AfternoonPeak = transportCard_frequencyLocationData[day + '_AfternoonPeak_' + md];
	const Evening = transportCard_frequencyLocationData[day + '_Evening_' + md];
	const Night = transportCard_frequencyLocationData[day + '_Night_' + md];
	const years = transportCard_frequencyLocationData['year']
	
	//console.log(MorningPeak);
	
	var freqencyctx = document.getElementById('frequency-chart').getContext('2d');
	transportCard_frequencyChart = new Chart(freqencyctx, {
		type: 'line',
		data: {
			labels: years,
			datasets: [{
				label: 'Morning Peak',
				data: MorningPeak,
				backgroundColor: 'rgba(232,243,83, 0.8)',
				borderColor: 'rgba(232,243,83, 1)',
				borderWidth: 1,
				order: 1
			},
			{
				label: 'Midday',
				data: Midday,
				backgroundColor: 'rgba(228,125,27, 0.8)',
				borderColor: 'rgba(228,125,27, 1)',
				borderWidth: 1,
				order: 1
			},
			{
				label: 'Afternoon Peak',
				data: AfternoonPeak,
				backgroundColor: 'rgba(230,25,124, 0.8)',
				borderColor: 'rgba(230,25,124, 1)',
				borderWidth: 1,
				order: 1
			},
			{
				label: 'Evening',
				data: Evening,
				backgroundColor: 'rgba(174,44,211, 0.8)',
				borderColor: 'rgba(174,44,211, 1)',
				borderWidth: 1,
				order: 1
			},
			{
				label: 'Night',
				data: Night,
				backgroundColor: 'rgba(0,0,0, 0.8)',
				borderColor: 'rgba(0,0,0, 1)',
				borderWidth: 1,
				order: 1
			}

			]
		},
		options: {
      responsive: true,
      maintainAspectRatio: false,
      plugins: {
        legend: {
          position: 'top',
        }
      }
    }
	});

}

transportCard_makeChartVehicles = function(){

  // Guard: do nothing until vehicle data has actually loaded (avoids a crash if
  // called with the empty default object, e.g. before a location is selected)
  if (!transportCard_vehicleLocationData || !transportCard_vehicleLocationData['year']) { return; }

  // Access Chart
  // Destroy old chart
	if(transportCard_privateVehicleBodyChart){
    transportCard_privateVehicleBodyChart.destroy();
  }
  if(transportCard_privateVehicleFuelChart){
    transportCard_privateVehicleFuelChart.destroy();
  }
  if(transportCard_companyVehicleBodyChart){
    transportCard_companyVehicleBodyChart.destroy();
  }
  if(transportCard_companyVehicleFuelChart){
    transportCard_companyVehicleFuelChart.destroy();
  }
  if(transportCard_vehiclePPChart){
    transportCard_vehiclePPChart.destroy();
  }
  
  const labels = transportCard_vehicleLocationData['year'];
  const dataprivateVehicleBody = {
    labels: labels,
    datasets: [
      {
        label: 'Cars (Licensed)',
        data: transportCard_vehicleLocationData['Cars_Licensed_PRIVATE'],
        backgroundColor: '#2b8cbe',
        stack: 'Stack 0',
      },
      {
        label: 'Cars (SORN)',
        data: transportCard_vehicleLocationData['Cars_SORN_PRIVATE'],
        backgroundColor: '#9ed4f0',
        stack: 'Stack 1',
      },
      {
        label: 'Motorcycles (Licensed)',
        data: transportCard_vehicleLocationData['Motorcycles_Licensed_PRIVATE'],
        backgroundColor: '#b30000',
        stack: 'Stack 0',
      },
      {
        label: 'Motorcycles (SORN)',
        data: transportCard_vehicleLocationData['Motorcycles_SORN_PRIVATE'],
        backgroundColor: '#ee8f8f',
        stack: 'Stack 1',
      },
      {
        label: 'Other (Licensed)',
        data: transportCard_vehicleLocationData['Other_Licensed_PRIVATE'],
        backgroundColor: '#1c8607',
        stack: 'Stack 0',
      },     
      {
        label: 'Other (SORN)',
        data: transportCard_vehicleLocationData['Other_SORN_PRIVATE'],
        backgroundColor: '#89f18e',
        stack: 'Stack 1',
      },
    ]
  };

  const datacompanyVehicleBody = {
    labels: labels,
    datasets: [
      {
        label: 'Cars (Licensed)',
        data: transportCard_vehicleLocationData['Cars_Licensed_COMPANY'],
        backgroundColor: '#2b8cbe',
        stack: 'Stack 0',
      },
      {
        label: 'Cars (SORN)',
        data: transportCard_vehicleLocationData['Cars_SORN_COMPANY'],
        backgroundColor: '#9ed4f0',
        stack: 'Stack 1',
      },
      {
        label: 'Motorcycles (Licensed)',
        data: transportCard_vehicleLocationData['Motorcycles_Licensed_COMPANY'],
        backgroundColor: '#b30000',
        stack: 'Stack 0',
      },
      {
        label: 'Motorcycles (SORN)',
        data: transportCard_vehicleLocationData['Motorcycles_SORN_COMPANY'],
        backgroundColor: '#ee8f8f',
        stack: 'Stack 1',
      },
      {
        label: 'Other (Licensed)',
        data: transportCard_vehicleLocationData['Other_Licensed_COMPANY'],
        backgroundColor: '#1c8607',
        stack: 'Stack 0',
      },     
      {
        label: 'Other (SORN)',
        data: transportCard_vehicleLocationData['Other_SORN_COMPANY'],
        backgroundColor: '#89f18e',
        stack: 'Stack 1',
      },
    ]
  };
  
  const dataprivateVehicleFuel = {
      labels: labels,
      datasets: [
        {
          label: 'Battery Electric',
          data: transportCard_vehicleLocationData['BEV_PRIVATE'],
          backgroundColor: '#07c220',
          stack: 'Stack 0',
        },
        {
          label: 'Hybrid',
          data: transportCard_vehicleLocationData['HEV_PRIVATE'],
          backgroundColor: '#0042f7',
          stack: 'Stack 0',
        },
        {
          label: 'Plug-in Hybrid',
          data: transportCard_vehicleLocationData['PHEV_PRIVATE'],
          backgroundColor: '#17d9f3',
          stack: 'Stack 0',
        },
        {
          label: 'Range Extended Electric',
          data: transportCard_vehicleLocationData['REEV_PRIVATE'],
          backgroundColor: '#e7e40e',
          stack: 'Stack 0',
        },
        {
          label: 'Fuel Cell',
          data: transportCard_vehicleLocationData['fuelcell_PRIVATE'],
          backgroundColor: '#9b0386',
          stack: 'Stack 0',
        },
        {
          label: 'Petrol/Diesel (ULEV)',
          data: transportCard_vehicleLocationData['iceULEV_PRIVATE'],
          backgroundColor: '#da7a0c',
          stack: 'Stack 0',
        },
        {
          label: 'Petrol/Diesel',
          data: transportCard_vehicleLocationData['ice_PRIVATE'],
          backgroundColor: '#ee2405',
          stack: 'Stack 0',
        },
      ]
    };

    const datacompanyVehicleFuel = {
      labels: labels,
      datasets: [
        {
          label: 'Battery Electric',
          data: transportCard_vehicleLocationData['BEV_COMPANY'],

          backgroundColor: '#07c220',
          stack: 'Stack 0',
        },
        {
          label: 'Hybrid',
          data: transportCard_vehicleLocationData['HEV_COMPANY'],
          backgroundColor: '#0042f7',
          stack: 'Stack 0',
        },
        {
          label: 'Plug-in Hybrid',
          data: transportCard_vehicleLocationData['PHEV_COMPANY'],
          backgroundColor: '#17d9f3',
          stack: 'Stack 0',
        },
        {
          label: 'Range Extended Electric',
          data: transportCard_vehicleLocationData['REEV_COMPANY'],
          backgroundColor: '#e7e40e',
          stack: 'Stack 0',
        },
        {
          label: 'Fuel Cell',
          data: transportCard_vehicleLocationData['fuelcell_COMPANY'],
          backgroundColor: '#9b0386',
          stack: 'Stack 0',
        },
        {
          label: 'Petrol/Diesel (ULEV)',
          data: transportCard_vehicleLocationData['iceULEV_COMPANY'],
          backgroundColor: '#da7a0c',
          stack: 'Stack 0',
        },
        {
          label: 'Petrol/Diesel',
          data: transportCard_vehicleLocationData['ice_COMPANY'],
          backgroundColor: '#ee2405',
          stack: 'Stack 0',
        },
      ]
    };
  
    const dataVehiclePP = {
      labels: labels.slice(0, 15), // Miss last year as no data
      datasets: [
        {
          label: 'Per Person',
          data: transportCard_vehicleLocationData['vehiclesPPers'].slice(0, 15),
          backgroundColor: '#07c220',
        },
        {
          label: 'Per Adult',
          data: transportCard_vehicleLocationData['vehiclesPAdult'].slice(0, 15),
          backgroundColor: '#0042f7',
        },
        {
          label: 'Per Household',
          data: transportCard_vehicleLocationData['vehiclesPHousehold'].slice(0, 15),
          backgroundColor: '#f50c0c',
        }
      ]
    };

  var vehiclePPctx = document.getElementById('vehiclePP-chart').getContext('2d');
	transportCard_vehiclePPChart = new Chart(vehiclePPctx, {
    type: 'line',
    data: dataVehiclePP,
    options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
        y: {
          title: {
            display: true,
            text: 'Number of Vehicles'
          },
          beginAtZero: true
        },
        x: {
          title: {
            display: true,
            text: 'Year'
          }
        }
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    },
  });

  var privateVehicleBodyctx = document.getElementById('privateVehicleBody-chart').getContext('2d');
	transportCard_privateVehicleBodyChart = new Chart(privateVehicleBodyctx, {
    type: 'bar',
    data: dataprivateVehicleBody,
    options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
        y: {
          title: {
            display: true,
            text: 'Number of Vehicles'
          },
          beginAtZero: true
        },
        x: {
          title: {
            display: true,
            text: 'Year'
          }
        }
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    },
  });
	
  var privateVehicleFuelctx = document.getElementById('privateVehicleFuel-chart').getContext('2d');
  transportCard_privateVehicleFuelChart = new Chart(privateVehicleFuelctx, {
    type: 'bar',
    data: dataprivateVehicleFuel,
    options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
        y: {
          title: {
            display: true,
            text: 'Number of Vehicles'
          },
          beginAtZero: true
        },
        x: {
          title: {
            display: true,
            text: 'Year'
          }
        }
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    },
  });

  var companyVehicleBodyctx = document.getElementById('companyVehicleBody-chart').getContext('2d');
  transportCard_companyVehicleBodyChart = new Chart(companyVehicleBodyctx, {
    type: 'bar',
    data: datacompanyVehicleBody,
    options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
        y: {
          title: {
            display: true,
            text: 'Number of Vehicles'
          },
          beginAtZero: true
        },
        x: {
          title: {
            display: true,
            text: 'Year'
          }
        }
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    },
  });

  var companyVehicleFuelctx = document.getElementById('companyVehicleFuel-chart').getContext('2d');
  transportCard_companyVehicleFuelChart = new Chart(companyVehicleFuelctx, {
    type: 'bar',
    data: datacompanyVehicleFuel,
    options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
        y: {
          title: {
            display: true,
            text: 'Number of Vehicles'
          },
          beginAtZero: true
        },
        x: {
          title: {
            display: true,
            text: 'Year'
          }
        }
      },
      plugins: {
        legend: {
          position: 'top',
        }
      }
    },
  });



};







// Function to switch chart description tabs (Overview / Policy / Methods)
// Scoped to the chart's own .chart-description-tabs container, so multiple
// chart tab groups operate independently.
switchChartTab = function (evt, tabName) {
  var tabsContainer = evt.currentTarget.closest('.chart-description-tabs');
  tabsContainer.querySelectorAll('.chart-description-tab-content').forEach(function (content) {
    content.classList.remove('active');
    content.style.display = 'none';
  });
  tabsContainer.querySelectorAll('.chart-tab-btn').forEach(function (button) {
    button.classList.remove('active');
  });
  var selectedContent = document.getElementById(tabName);
  if (selectedContent) {
    selectedContent.classList.add('active');
    selectedContent.style.display = 'block';
    evt.currentTarget.classList.add('active');
  }
};


// Registration: the report page calls window.reportCards.transport.load(locationId)
window.reportCards = window.reportCards || {};
window.reportCards.transport = {
  load: function (locationId) { return transportCard_manageCharts(locationId, 'zones'); },
  defaultOpen: 'transport-defaultOpen'
};
